# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swanlab/record/v1/record.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swanlab/record/v1/record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from swanlab.proto.swanlab.run.v1 import run_pb2 as swanlab_dot_run_dot_v1_dot_run__pb2
from swanlab.proto.swanlab.metric.data.v1 import data_pb2 as swanlab_dot_metric_dot_data_dot_v1_dot_data__pb2
from swanlab.proto.swanlab.metric.column.v1 import column_pb2 as swanlab_dot_metric_dot_column_dot_v1_dot_column__pb2
from swanlab.proto.swanlab.config.v1 import config_pb2 as swanlab_dot_config_dot_v1_dot_config__pb2
from swanlab.proto.swanlab.env.v1 import env_pb2 as swanlab_dot_env_dot_v1_dot_env__pb2
from swanlab.proto.swanlab.terminal.v1 import log_pb2 as swanlab_dot_terminal_dot_v1_dot_log__pb2
from swanlab.proto.swanlab.save.v1 import save_pb2 as swanlab_dot_save_dot_v1_dot_save__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eswanlab/record/v1/record.proto\x12\x11swanlab.record.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18swanlab/run/v1/run.proto\x1a!swanlab/metric/data/v1/data.proto\x1a%swanlab/metric/column/v1/column.proto\x1a\x1eswanlab/config/v1/config.proto\x1a\x18swanlab/env/v1/env.proto\x1a\x1dswanlab/terminal/v1/log.proto\x1a\x1aswanlab/save/v1/save.proto\"\x86\x05\n\x06Record\x12\x0b\n\x03num\x18\x01 \x01(\x03\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x05start\x18\n \x01(\x0b\x32\x1b.swanlab.run.v1.StartRecordH\x00\x12.\n\x06\x66inish\x18\x0b \x01(\x0b\x32\x1c.swanlab.run.v1.FinishRecordH\x00\x12\x38\n\x06\x63olumn\x18\x0c \x01(\x0b\x32&.swanlab.metric.column.v1.ColumnRecordH\x00\x12\x36\n\x06scalar\x18\r \x01(\x0b\x32$.swanlab.metric.data.v1.ScalarRecordH\x00\x12\x34\n\x05media\x18\x0e \x01(\x0b\x32#.swanlab.metric.data.v1.MediaRecordH\x00\x12\x31\n\x06\x63onfig\x18\x0f \x01(\x0b\x32\x1f.swanlab.config.v1.ConfigRecordH\x00\x12-\n\x03log\x18\x10 \x01(\x0b\x32\x1e.swanlab.terminal.v1.LogRecordH\x00\x12\x32\n\x08metadata\x18\x11 \x01(\x0b\x32\x1e.swanlab.env.v1.MetadataRecordH\x00\x12:\n\x0crequirements\x18\x12 \x01(\x0b\x32\".swanlab.env.v1.RequirementsRecordH\x00\x12,\n\x05\x63onda\x18\x13 \x01(\x0b\x32\x1b.swanlab.env.v1.CondaRecordH\x00\x12+\n\x04save\x18\x14 \x01(\x0b\x32\x1b.swanlab.save.v1.SaveRecordH\x00\x42\r\n\x0brecord_typeBCZAgithub.com/swanhubx/swanlab/core/proto/swanlab/record/v1;recordv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swanlab.record.v1.record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/swanhubx/swanlab/core/proto/swanlab/record/v1;recordv1'
  _globals['_RECORD']._serialized_start=304
  _globals['_RECORD']._serialized_end=950
# @@protoc_insertion_point(module_scope)
