"""
@author: cunyue
@file: init.py
@time: 2026/3/6 21:47
@description: SwanLab SDK 初始化方法
我们在设计上将init前后作为分界线，在init之前出现的错误（如登录失败）被视为critical错误，一旦报错直接退出（大多数情况下）
在init之后的swanlab内部错误被视为non-critical错误，会尝试继续运行，但会记录错误日志
init函数执行时被视为init之前
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import yaml

from swanlab.sdk.internal.core_python import client
from swanlab.sdk.internal.pkg import console
from swanlab.sdk.utils import helper

from ..internal.settings import Settings
from ..internal.settings import settings as global_settings
from ..typings.run import ModeType, ResumeType
from .login import interactive_login


def set_nested_value(d: dict, key: str, value: Any):
    """
    根据点分隔的键路径设置嵌套字典中的值
    例如: set_nested_value(d, "a.b.c", 1) 会设置 d["a"]["b"]["c"] = 1
    注意: 如果 value 为 None，则不会设置该值
    :param d: 要操作的字典
    :param key: 键路径，使用点分隔
    :param value: 要设置的值，如果为 None 则不设置
    """
    if value is None:
        return
    keys = key.split(".")
    current_dict = d
    for k in keys[:-1]:
        if k not in current_dict:
            current_dict[k] = {}
        current_dict = current_dict[k]
    current_dict[keys[-1]] = value


def compatible_kwargs(model_dict: dict, **kwargs) -> dict:
    """
    由于不同库的参数名不同，并且照顾到用户习惯，我们需要针对一些参数进行兼容性处理。
    将一些额外的参数合并到 model_dict 中
    """
    # experiment_name --> name
    set_nested_value(model_dict, "experiment.name", kwargs.pop("experiment_name", None))
    # notes --> description
    set_nested_value(model_dict, "experiment.description", kwargs.pop("notes", None))
    return model_dict


ConfigLike = Union[Dict[str, Any], str, os.PathLike]


def init(
    *,
    reinit: Optional[bool] = None,
    logdir: Optional[str] = None,
    mode: Optional[ModeType] = None,
    settings: Optional[Settings] = None,
    workspace: Optional[str] = None,
    project: Optional[str] = None,
    public: Optional[bool] = None,
    name: Optional[str] = None,
    color: Optional[str] = None,
    description: Optional[str] = None,
    job_type: Optional[str] = None,
    group: Optional[str] = None,
    tags: Optional[List[str]] = None,
    id: Optional[str] = None,
    resume: Optional[Union[ResumeType, bool]] = None,
    config: Optional[ConfigLike] = None,
    **kwargs,
):
    """
    Start a new run to track and log. Once you have called this function, you can use 'swanlab.log' to log data to
    the current run. Meanwhile, you can use 'swanlab.finish' to finish the current run and close the current
    experiment. After calling this function, SwanLab will begin to record the console output of the current process,
    and register a callback function to the exit function.

    :param reinit: Whether to reinitialize SwanLabRun, the default is False.

    :param logdir: The folder will store all the log information generated during the execution of SwanLab.
        If the parameter is None,
        SwanLab will generate a folder named "swanlog" in the same path as the code execution to store the data.
        If you want to visualize the generated log files,
        simply run the command `swanlab watch` in the same path where the code is executed
        (without entering the "swanlog" folder).
        You can also specify your own folder, but you must ensure that the folder exists and preferably does not contain
        anything other than data generated by Swanlab.
        In this case, if you want to view the logs,
        you must use something like `swanlab watch -l ./your_specified_folder` to specify the folder path.
        Note that `swanlab watch` only available in local mode.

    :param mode: The mode of the current experiment. Allowed values are 'cloud', 'local', 'disabled', 'offline'.
        If the value is 'cloud', data will be uploaded to the cloud and the local log will be saved.
        If the value is 'local', data will only be saved locally and will not be uploaded to the cloud.
        If the value is 'disabled', data will not be saved or uploaded, just parsing the data.
        If the value is 'offline', data will be saved locally without uploading to the cloud.
        BTW, 'online' is an alias for 'cloud'.

    :param settings: The settings for the current experiment.

    :param workspace: Where the current project is located, it can be an organization or a user.
        The default is None, which means the current entity is the same as the current user.

    :param project: The project name of the current experiment.

    :param public: Whether the project can be seen by anyone, the default is None, which means the project is private.
        Only available in cloud mode while the first time you create the project.

    :param name: The experiment name you currently have open.
        If this parameter is not provided, SwanLab will generate one for you by default.

    :param color: The color of the experiment, used for distinguishing different experiments.
        SwanLab will automatically generate a color for you if you do not provide this parameter.

    :param resume: Resume the previous run or not:
        - must: You must pass the `id` parameter and the run must exist.
        - allow: If the run exists, it will be resumed, otherwise a new run will be created.
        - never: You cannot pass the `id` parameter, and a new run will be created.
        You can also pass a boolean value, where `True` is equivalent to 'allow' and `False` is equivalent to 'never'.
        [Notice that] This parameter is only valid when mode='cloud'

    :param id: The run ID of the previous run, which is used to resume the previous run.
        If you do not provide this parameter, a new run will be created.

    :param description: The experiment description you currently have open,
        used for a more detailed introduction or labeling of the current experiment.
        If you do not provide this parameter, you can modify it later in the web interface.

    :param job_type: The job type of the current experiment, used to distinguish different types of experiments.

    :param group: The experiment group of the current experiment, used for grouping experiments.

    :param tags: The tags of the experiment, used for labeling the current experiment.
        If you do not provide this parameter, you can modify it later in the web interface.

    :param config: The configuration of the current experiment.
        If you provide a string, it will be loaded from a file.

    :return: The SwanLabRun object.
    """
    if reinit:
        ...
    # 运行时配置
    run_settings = Settings()
    # --------------------- 第一次处理，合并配置，检查格式，与业务无关 ----------------------------
    # 配置具有优先级，从低到高依次是：全局配置 --> 自定义配置 --> 传入的参数
    # 1. 合并全局配置
    run_settings.merge_settings(global_settings)
    # 2. 合并自定义配置
    if settings:
        run_settings.merge_settings(settings)
    # 3. 基于传入的参数，合并当前配置，此步骤必须在合并全局配置之后，因为传入的参数的优先级是高于全局配置的
    args_dict = compatible_kwargs({}, **kwargs)
    for key, value in {
        "logdir": logdir,
        "mode": mode,
        "project.name": project,
        "project.workspace": workspace,
        "project.public": public,
        "experiment.name": name,
        "experiment.color": color,
        "experiment.description": description,
        "experiment.job_type": job_type,
        "experiment.group": group,
        "experiment.tags": tags,
        "run.resume": resume,
        "run.id": id,
        "run.config": Path(config) if isinstance(config, (str, os.PathLike)) else None,
    }.items():
        set_nested_value(args_dict, key, value)
    run_settings.merge_settings(args_dict)
    # 执行初始化
    _init(run_settings, config)


@helper.rich.with_loading_animation()
def _init(run_settings: Settings, config: Optional[ConfigLike]):
    """
    初始化运行时配置，在这之前，所有引导式交互都已经完成
    """
    _ = load_config(run_settings, config)
    mode, _ = prompt_init_mode(run_settings)
    if mode == "cloud":
        pass


def load_config(run_settings: Settings, config: Optional[ConfigLike]) -> Dict[str, Any]:
    """
    优雅地加载配置：支持字典直接返回，或从 JSON/YAML 文件加载。
    """
    config = config or run_settings.run.config
    # 1. 如果 config 为 None，则返回空字典
    if config is None:
        return {}

    # 2. 如果 config 是字典，则直接返回
    if isinstance(config, dict):
        return config

    # 3. 处理路径类型（包括字符串字面量）
    if isinstance(config, (str, os.PathLike)):
        path = Path(config)

        if not path.exists():
            raise FileNotFoundError(f"Config file not found: {path}")

        # 根据后缀名选择加载器
        suffix = path.suffix.lower()
        try:
            with open(path, "r", encoding="utf-8") as f:
                if suffix == ".json":
                    return json.load(f)
                elif suffix in (".yaml", ".yml"):
                    # 使用 safe_load 保证安全
                    return yaml.safe_load(f)
                else:
                    # 如果没有后缀或者后缀未知，尝试先按 JSON 读，失败再按 YAML 读
                    content = f.read()
                    try:
                        return json.loads(content)
                    except json.JSONDecodeError:
                        return yaml.safe_load(content)
        except Exception as e:
            raise ValueError(f"Error parsing config file {path}: {e}")

    # 4. 如果 config 不是上述类型，直接报错
    raise ValueError(f"Invalid config type: {type(config).__name__}. Expected dict, str, or PathLike.")


def prompt_init_mode(settings: Settings) -> Tuple[ModeType, bool]:
    """
    在 swanlab.init 阶段，针对 cloud 模式且未登录的用户进行交互式引导。

    规则：
    1. 只有在 settings.interactive 为 True 且 settings.mode 为 'cloud' 时触发 。
    2. 如果 client 已存在（已登录），直接跳过 。
    3. 提供三个选项：(1) 注册 (2) 登录 (3) 切换为 offline 模式。

    :param settings: 当前的 Settings 实例 。
    :return: (最终确定的 mode, 是否成功登录)
    """
    # 如果不是云模式，或者已经登录，或者非交互环境，直接返回当前状态
    if settings.mode != "cloud" or client.exists() or not settings.interactive:
        return settings.mode, client.exists()

    console.info("Using SwanLab to track your experiments. For more information, please visit:", "yellow")
    console.info(f"Docs: {settings.web_host}/docs", "blue")

    console.info("(1) Create a SwanLab account.")
    console.info("(2) Use an existing SwanLab account.")
    console.info("(3) Don't visualize my results (Offline mode).")

    while True:
        choice = input("Enter your choice (1/2/3): ").strip()

        if choice == "3":
            console.info("Switching to 'offline' mode. Results will be saved locally.")
            return "offline", False

        if choice == "1":
            console.info("Create a SwanLab account here:", "yellow")
            console.info(f"{settings.web_host}/login", "blue")
            # 注册后紧接着触发登录循环
            success = interactive_login(save=True)
            return "cloud", success

        if choice == "2":
            console.info(f"Logging into {settings.web_host}...")
            # 触发带循环容错的登录接口
            success = interactive_login(save=True)
            return "cloud", success

        console.warning("Invalid choice, please enter 1, 2, or 3.")
