"""
@author: cunyue
@file: init.py
@time: 2026/3/6 21:47
@description: SwanLab SDK 初始化方法
"""

from functools import wraps
from typing import Any, List, Optional, Union

from rich.status import Status

from ..internal.context import get_context, has_context
from ..internal.settings import Settings
from ..internal.settings import settings as global_settings
from ..typing.run import ModeType, ResumeType


def with_loading_animation(message: str = "Initializing SwanLab...", spinner_name: str = "dots"):
    """
    一个使用 rich 包装的加载动画装饰器
    :param message: 动画旁边显示的文字
    :param spinner_name: 动画样式（如 'dots', 'bouncingBar', 'point' 等）
    """

    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            # 使用 rich 的 status 作为上下文管理器包裹函数的执行
            with Status(f"[bold green]{message}[/bold green]", spinner=spinner_name):
                return func(*args, **kwargs)

        return wrapper

    return decorator


def set_nested_value(d: dict, key: str, value: Any):
    """
    根据点分隔的键路径设置嵌套字典中的值
    例如: set_nested_value(d, "a.b.c", 1) 会设置 d["a"]["b"]["c"] = 1
    注意: 如果 value 为 None，则不会设置该值
    :param d: 要操作的字典
    :param key: 键路径，使用点分隔
    :param value: 要设置的值，如果为 None 则不设置
    """
    if value is None:
        return
    keys = key.split(".")
    current_dict = d
    for k in keys[:-1]:
        if k not in current_dict:
            current_dict[k] = {}
        current_dict = current_dict[k]
    current_dict[keys[-1]] = value


def compatible_kwargs(model_dict: dict, **kwargs) -> dict:
    """
    由于不同库的参数名不同，并且照顾到用户习惯，我们需要针对一些参数进行兼容性处理。
    将一些额外的参数合并到 model_dict 中
    """
    # name --> experiment_name
    set_nested_value(model_dict, "experiment.name", kwargs.pop("name", None))
    # notes --> description
    set_nested_value(model_dict, "experiment.description", kwargs.pop("notes", None))
    return model_dict


def strip_none(data: dict) -> dict:
    """
    递归剔除字典中的 None 值和空字典，主要用于配置项合并时的空值处理
    """
    clean_data = {}
    for k, v in data.items():
        if isinstance(v, dict):
            cleaned_v = strip_none(v)
            # 只有当嵌套字典里真的有非 None 的值时，才保留这个 key
            if cleaned_v:
                clean_data[k] = cleaned_v
        elif v is not None:
            clean_data[k] = v
    return clean_data


@with_loading_animation()
def init(
    *,
    reinit: Optional[bool] = None,
    logdir: Optional[str] = None,
    mode: Optional[ModeType] = None,
    settings: Optional[Settings] = None,
    workspace: Optional[str] = None,
    project: Optional[str] = None,
    public: Optional[bool] = None,
    experiment_name: Optional[str] = None,
    description: Optional[str] = None,
    job_type: Optional[str] = None,
    group: Optional[str] = None,
    tags: Optional[List[str]] = None,
    id: Optional[str] = None,
    resume: Optional[Union[ResumeType, bool]] = None,
    config: Optional[Union[dict, str]] = None,
    **kwargs,
):
    """
    Start a new run to track and log. Once you have called this function, you can use 'swanlab.log' to log data to
    the current run. Meanwhile, you can use 'swanlab.finish' to finish the current run and close the current
    experiment. After calling this function, SwanLab will begin to record the console output of the current process,
    and register a callback function to the exit function.
    :param reinit: Whether to reinitialize SwanLabRun, the default is False.
    :param logdir: The folder will store all the log information generated during the execution of SwanLab.
        If the parameter is None,
        SwanLab will generate a folder named "swanlog" in the same path as the code execution to store the data.
        If you want to visualize the generated log files,
        simply run the command `swanlab watch` in the same path where the code is executed
        (without entering the "swanlog" folder).
        You can also specify your own folder, but you must ensure that the folder exists and preferably does not contain
        anything other than data generated by Swanlab.
        In this case, if you want to view the logs,
        you must use something like `swanlab watch -l ./your_specified_folder` to specify the folder path.
        Note that `swanlab watch` only available in local mode.
    :param mode: The mode of the current experiment. Allowed values are 'cloud', 'local', 'disabled', 'offline'.
        If the value is 'cloud', data will be uploaded to the cloud and the local log will be saved.
        If the value is 'local', data will only be saved locally and will not be uploaded to the cloud.
        If the value is 'disabled', data will not be saved or uploaded, just parsing the data.
        If the value is 'offline', data will be saved locally without uploading to the cloud.
        BTW, 'online' is an alias for 'cloud'.
    :param settings: The settings for the current experiment.
    :param workspace: Where the current project is located, it can be an organization or a user.
        The default is None, which means the current entity is the same as the current user.
    :param project: The project name of the current experiment.
    :param public: Whether the project can be seen by anyone, the default is None, which means the project is private.
        Only available in cloud mode while the first time you create the project.
    :param experiment_name: The experiment name you currently have open.
        If this parameter is not provided, SwanLab will generate one for you by default.
    :param resume: Resume the previous run or not:
        - must: You must pass the `id` parameter and the run must exist.
        - allow: If the run exists, it will be resumed, otherwise a new run will be created.
        - never: You cannot pass the `id` parameter, and a new run will be created.
        You can also pass a boolean value, where `True` is equivalent to 'allow' and `False` is equivalent to 'never'.
        [Notice that] This parameter is only valid when mode='cloud'
    :param id: The run ID of the previous run, which is used to resume the previous run.
        If you do not provide this parameter, a new run will be created.
    :param description: The experiment description you currently have open,
        used for a more detailed introduction or labeling of the current experiment.
        If you do not provide this parameter, you can modify it later in the web interface.
    :param job_type: The job type of the current experiment, used to distinguish different types of experiments.
    :param group: The experiment group of the current experiment, used for grouping experiments.
    :param tags: The tags of the experiment, used for labeling the current experiment.
        If you do not provide this parameter, you can modify it later in the web interface.
    :param config: The configuration of the current experiment.
    :return: The SwanLabRun object.
    """
    if reinit:
        ...
    # 运行时配置
    run_settings = Settings()
    # --------------------- 第一次处理，合并配置，检查格式，与业务无关 ----------------------------
    # 配置具有优先级，从低到高依次是：全局配置 --> 自定义配置 --> 传入的参数 --> 上下文中已有配置
    # 1. 合并全局配置
    run_settings.merge_settings(global_settings)
    # 2. 合并自定义配置
    if settings:
        run_settings.merge_settings(settings)
    # 3. 基于传入的参数，合并当前配置，此步骤必须在合并全局配置之后，因为传入的参数的优先级是高于全局配置的
    args_dict = compatible_kwargs({}, **kwargs)
    for key, value in {
        "logdir": logdir,
        "mode": mode,
        "project.name": project,
        "project.workspace": workspace,
        "project.public": public,
        "experiment.name": experiment_name,
        "experiment.description": description,
        "experiment.job_type": job_type,
        "experiment.group": group,
        "experiment.tags": tags,
        "run.resume": resume,
        "run.id": id,
    }.items():
        set_nested_value(args_dict, key, value)
    # 4. 获取上下文中已有的配置
    if has_context():
        context_settings = get_context().config.settings
        run_settings.merge_settings(context_settings)
    # ------------------- 如果是云端版本，提示输入API Key或自动登录 ---------------------------
    if run_settings.mode == "cloud":
        ...
    # ---------------------------------- 根据业务校验参数 ----------------------------------
