# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swanlab/grpc/probe/v1/probe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swanlab/grpc/probe/v1/probe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from swanlab.proto.swanlab.settings.probe.v1 import probe_pb2 as swanlab_dot_settings_dot_probe_dot_v1_dot_probe__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!swanlab/grpc/probe/v1/probe.proto\x12\x15swanlab.grpc.probe.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a%swanlab/settings/probe/v1/probe.proto\"\\\n\x18\x44\x65liverProbeStartRequest\x12@\n\x0eprobe_settings\x18\x01 \x01(\x0b\x32(.swanlab.settings.probe.v1.ProbeSettings2\xb2\x01\n\x0cProbeService\x12\\\n\x11\x44\x65liverProbeStart\x12/.swanlab.grpc.probe.v1.DeliverProbeStartRequest\x1a\x16.google.protobuf.Empty\x12\x44\n\x12\x44\x65liverProbeFinish\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBFZDgithub.com/swanhubx/swanlab/core/proto/swanlab/grpc/probe/v1;probev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swanlab.grpc.probe.v1.probe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZDgithub.com/swanhubx/swanlab/core/proto/swanlab/grpc/probe/v1;probev1'
  _globals['_DELIVERPROBESTARTREQUEST']._serialized_start=128
  _globals['_DELIVERPROBESTARTREQUEST']._serialized_end=220
  _globals['_PROBESERVICE']._serialized_start=223
  _globals['_PROBESERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
