# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from swanlab.proto.swanlab.grpc.core.v1 import core_pb2 as swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swanlab/grpc/core/v1/core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub(object):
    """CoreService 是核心业务接口，用于同步或异步地接收实验记录。

    生命周期约定：

    1. Core 与 run 级生命周期严格分离：SpinupService / TeardownService 作用于整个 core 服务进程；
    2. 所有 run 级 RPC 通过显式 run_handle 路由到具体会话，不依赖 channel 隐式绑定 run；
    3. ConfirmRunFinish 确认单个 run 已排空并释放其资源，不关闭 gRPC Server；
    须在对应 run 的 DeliverRunFinish 之后调用，提前调用返回 FAILED_PRECONDITION 且会话保留；
    4. GetOperationStats / ConfirmRunFinish 输入使用专用 request，由 run_handle 指定目标 run。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpinupService = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/SpinupService',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.SpinupServiceRequest.SerializeToString,
                response_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.SpinupServiceResponse.FromString,
                _registered_method=True)
        self.TeardownService = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/TeardownService',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.TeardownServiceRequest.SerializeToString,
                response_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.TeardownServiceResponse.FromString,
                _registered_method=True)
        self.DeliverRunStart = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/DeliverRunStart',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartRequest.SerializeToString,
                response_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartResponse.FromString,
                _registered_method=True)
        self.UpsertColumns = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertColumns',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertColumnsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertScalars = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertScalars',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertScalarsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertMedia = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertMedia',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMediaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertLogs = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertLogs',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertLogsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertSaves = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertSaves',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertSavesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeliverRunFinish = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/DeliverRunFinish',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishRequest.SerializeToString,
                response_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishResponse.FromString,
                _registered_method=True)
        self.GetOperationStats = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/GetOperationStats',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.GetOperationStatsRequest.SerializeToString,
                response_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.GetOperationStatsResponse.FromString,
                _registered_method=True)
        self.ConfirmRunFinish = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/ConfirmRunFinish',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.ConfirmRunFinishRequest.SerializeToString,
                response_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.ConfirmRunFinishResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """CoreService 是核心业务接口，用于同步或异步地接收实验记录。

    生命周期约定：

    1. Core 与 run 级生命周期严格分离：SpinupService / TeardownService 作用于整个 core 服务进程；
    2. 所有 run 级 RPC 通过显式 run_handle 路由到具体会话，不依赖 channel 隐式绑定 run；
    3. ConfirmRunFinish 确认单个 run 已排空并释放其资源，不关闭 gRPC Server；
    须在对应 run 的 DeliverRunFinish 之后调用，提前调用返回 FAILED_PRECONDITION 且会话保留；
    4. GetOperationStats / ConfirmRunFinish 输入使用专用 request，由 run_handle 指定目标 run。
    """

    def SpinupService(self, request, context):
        """SpinupService 完成服务级初始化并把服务置为 READY，不负责创建 run 级 datastore 和 transport
        启动失败 RPC 返回 FAILED_PRECONDITION；重复 Spinup 在 READY 下幂等成功，共享一个 core 服务进程。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TeardownService(self, request, context):
        """TeardownService 关闭整个服务进程。不同于 ConfirmRunFinish ，能连接 core 的 client 都可调用。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverRunStart(self, request, context):
        """DeliverRunStart 接收单条 StartRecord，用于实验开始，并返回必要的信息。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertColumns(self, request, context):
        """UpsertColumns 接收一组 ColumnRecord 并写入，每一条记录用于定义某一个指标
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertScalars(self, request, context):
        """UpsertScalars 接收一组 ScalarRecord 并写入，每一条记录用于记录某一个指标的值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertMedia(self, request, context):
        """UpsertMedia 接收一组 MediaRecord 并写入，每一条记录用于记录某一个指标的值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertLogs(self, request, context):
        """UpsertLogs 接收一组 LogRecord 并写入，每一条记录对应一行用户的终端输出
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertSaves(self, request, context):
        """UpsertSaves 接收一组 SaveRecord 并写入，每一条记录对应一次 swanlab.save() 的文件保存或者swanlab内部保存操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverRunFinish(self, request, context):
        """DeliverRunFinish 接收单条 FinishRecord，用于实验结束。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperationStats(self, request, context):
        """GetOperationStats 返回指定 run 当前运行状态和上传进度快照。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmRunFinish(self, request, context):
        """ConfirmRunFinish 确认指定 run 已排空并释放其资源，不关闭 gRPC Server。
        前置条件：该 run 的 DeliverRunFinish 已上传完成，提前调用返回 FAILED_PRECONDITION。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpinupService': grpc.unary_unary_rpc_method_handler(
                    servicer.SpinupService,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.SpinupServiceRequest.FromString,
                    response_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.SpinupServiceResponse.SerializeToString,
            ),
            'TeardownService': grpc.unary_unary_rpc_method_handler(
                    servicer.TeardownService,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.TeardownServiceRequest.FromString,
                    response_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.TeardownServiceResponse.SerializeToString,
            ),
            'DeliverRunStart': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverRunStart,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartRequest.FromString,
                    response_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartResponse.SerializeToString,
            ),
            'UpsertColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertColumns,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertColumnsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertScalars': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertScalars,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertScalarsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertMedia,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMediaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertLogs,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertLogsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertSaves': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertSaves,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertSavesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeliverRunFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverRunFinish,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishRequest.FromString,
                    response_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishResponse.SerializeToString,
            ),
            'GetOperationStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperationStats,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.GetOperationStatsRequest.FromString,
                    response_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.GetOperationStatsResponse.SerializeToString,
            ),
            'ConfirmRunFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmRunFinish,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.ConfirmRunFinishRequest.FromString,
                    response_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.ConfirmRunFinishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swanlab.grpc.core.v1.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swanlab.grpc.core.v1.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """CoreService 是核心业务接口，用于同步或异步地接收实验记录。

    生命周期约定：

    1. Core 与 run 级生命周期严格分离：SpinupService / TeardownService 作用于整个 core 服务进程；
    2. 所有 run 级 RPC 通过显式 run_handle 路由到具体会话，不依赖 channel 隐式绑定 run；
    3. ConfirmRunFinish 确认单个 run 已排空并释放其资源，不关闭 gRPC Server；
    须在对应 run 的 DeliverRunFinish 之后调用，提前调用返回 FAILED_PRECONDITION 且会话保留；
    4. GetOperationStats / ConfirmRunFinish 输入使用专用 request，由 run_handle 指定目标 run。
    """

    @staticmethod
    def SpinupService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/SpinupService',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.SpinupServiceRequest.SerializeToString,
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.SpinupServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TeardownService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/TeardownService',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.TeardownServiceRequest.SerializeToString,
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.TeardownServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverRunStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/DeliverRunStart',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartRequest.SerializeToString,
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertColumns',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertColumnsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertScalars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertScalars',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertScalarsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertMedia',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMediaRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertLogs',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertLogsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertSaves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertSaves',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertSavesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverRunFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/DeliverRunFinish',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishRequest.SerializeToString,
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperationStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/GetOperationStats',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.GetOperationStatsRequest.SerializeToString,
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.GetOperationStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmRunFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/ConfirmRunFinish',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.ConfirmRunFinishRequest.SerializeToString,
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.ConfirmRunFinishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
