# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from swanlab.proto.swanlab.grpc.core.v1 import core_pb2 as swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swanlab/grpc/core/v1/core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub(object):
    """CoreService 是核心业务接口，用于同步或异步地接收实验记录
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeliverRunStart = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/DeliverRunStart',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartRequest.SerializeToString,
                response_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartResponse.FromString,
                _registered_method=True)
        self.UpsertColumns = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertColumns',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertColumnsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertScalars = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertScalars',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertScalarsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertMedia = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertMedia',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMediaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertConfigs = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertConfigs',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertConfigsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertLogs = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertLogs',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertLogsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertRequirements = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertRequirements',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertRequirementsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertConda = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertConda',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertCondaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertMetadata = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertMetadata',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMetadataRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpsertSaves = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/UpsertSaves',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertSavesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeliverRunFinish = channel.unary_unary(
                '/swanlab.grpc.core.v1.CoreService/DeliverRunFinish',
                request_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishRequest.SerializeToString,
                response_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishResponse.FromString,
                _registered_method=True)


class CoreServiceServicer(object):
    """CoreService 是核心业务接口，用于同步或异步地接收实验记录
    """

    def DeliverRunStart(self, request, context):
        """DeliverRunStart 接收单条 StartRecord，用于实验开始，并返回必要的信息。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertColumns(self, request, context):
        """UpsertColumns 接收一组 ColumnRecord 并写入，每一条记录用于定义某一个指标
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertScalars(self, request, context):
        """UpsertScalars 接收一组 ScalarRecord 并写入，每一条记录用于记录某一个指标的值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertMedia(self, request, context):
        """UpsertMedia 接收一组 MediaRecord 并写入，每一条记录用于记录某一个指标的值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertConfigs(self, request, context):
        """UpsertConfigs 接收一组 ConfigRecord 并写入，每一条记录对应一次用户对 config 的修改
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertLogs(self, request, context):
        """UpsertLogs 接收一组 LogRecord 并写入，每一条记录对应一行用户的终端输出
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertRequirements(self, request, context):
        """UpsertRequirements 接收一组 RequirementsRecord 并写入，每一条记录对应一次用户/系统对 requirements 的修改
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertConda(self, request, context):
        """UpsertConda 接收一组 CondaRecord 并写入，每一条记录对应一次用户/系统对 conda 的修改
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertMetadata(self, request, context):
        """UpsertMetadata 接收一组 MetadataRecord 并写入，每一条记录对应一次用户/系统对 metadata 的修改
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertSaves(self, request, context):
        """UpsertSaves 接收一组 SaveRecord 并写入，每一条记录对应一次 swanlab.save() 的文件保存
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverRunFinish(self, request, context):
        """DeliverRunFinish 接收单条 FinishRecord，用于实验结束。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeliverRunStart': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverRunStart,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartRequest.FromString,
                    response_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartResponse.SerializeToString,
            ),
            'UpsertColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertColumns,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertColumnsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertScalars': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertScalars,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertScalarsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertMedia,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMediaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertConfigs,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertConfigsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertLogs,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertLogsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertRequirements': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertRequirements,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertRequirementsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertConda': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertConda,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertCondaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertMetadata,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMetadataRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpsertSaves': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertSaves,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertSavesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeliverRunFinish': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverRunFinish,
                    request_deserializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishRequest.FromString,
                    response_serializer=swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swanlab.grpc.core.v1.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swanlab.grpc.core.v1.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """CoreService 是核心业务接口，用于同步或异步地接收实验记录
    """

    @staticmethod
    def DeliverRunStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/DeliverRunStart',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartRequest.SerializeToString,
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertColumns',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertColumnsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertScalars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertScalars',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertScalarsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertMedia',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMediaRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertConfigs',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertConfigsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertLogs',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertLogsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertRequirements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertRequirements',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertRequirementsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertConda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertConda',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertCondaRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertMetadata',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertMetadataRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertSaves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/UpsertSaves',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.UpsertSavesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverRunFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.grpc.core.v1.CoreService/DeliverRunFinish',
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishRequest.SerializeToString,
            swanlab_dot_grpc_dot_core_dot_v1_dot_core__pb2.DeliverRunFinishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
