// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/data/v1/column.proto

package datav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColumnClass 列的来源类别
type ColumnClass int32

const (
	ColumnClass_COLUMN_CLASS_UNSPECIFIED ColumnClass = 0
	ColumnClass_COLUMN_CLASS_CUSTOM      ColumnClass = 1 // 用户自定义列（默认）
)

// Enum value maps for ColumnClass.
var (
	ColumnClass_name = map[int32]string{
		0: "COLUMN_CLASS_UNSPECIFIED",
		1: "COLUMN_CLASS_CUSTOM",
	}
	ColumnClass_value = map[string]int32{
		"COLUMN_CLASS_UNSPECIFIED": 0,
		"COLUMN_CLASS_CUSTOM":      1,
	}
)

func (x ColumnClass) Enum() *ColumnClass {
	p := new(ColumnClass)
	*p = x
	return p
}

func (x ColumnClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnClass) Descriptor() protoreflect.EnumDescriptor {
	return file_swanlab_data_v1_column_proto_enumTypes[0].Descriptor()
}

func (ColumnClass) Type() protoreflect.EnumType {
	return &file_swanlab_data_v1_column_proto_enumTypes[0]
}

func (x ColumnClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnClass.Descriptor instead.
func (ColumnClass) EnumDescriptor() ([]byte, []int) {
	return file_swanlab_data_v1_column_proto_rawDescGZIP(), []int{0}
}

// ColumnType 列的数据类型
type ColumnType int32

const (
	ColumnType_COLUMN_TYPE_UNSPECIFIED ColumnType = 0
	ColumnType_COLUMN_TYPE_FLOAT       ColumnType = 1
	ColumnType_COLUMN_TYPE_IMAGE       ColumnType = 2
	ColumnType_COLUMN_TYPE_AUDIO       ColumnType = 3
	ColumnType_COLUMN_TYPE_TEXT        ColumnType = 4
	ColumnType_COLUMN_TYPE_ANY         ColumnType = 5 // 任意类型，需配合 error 字段
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "COLUMN_TYPE_UNSPECIFIED",
		1: "COLUMN_TYPE_FLOAT",
		2: "COLUMN_TYPE_IMAGE",
		3: "COLUMN_TYPE_AUDIO",
		4: "COLUMN_TYPE_TEXT",
		5: "COLUMN_TYPE_ANY",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_UNSPECIFIED": 0,
		"COLUMN_TYPE_FLOAT":       1,
		"COLUMN_TYPE_IMAGE":       2,
		"COLUMN_TYPE_AUDIO":       3,
		"COLUMN_TYPE_TEXT":        4,
		"COLUMN_TYPE_ANY":         5,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_swanlab_data_v1_column_proto_enumTypes[1].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_swanlab_data_v1_column_proto_enumTypes[1]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_swanlab_data_v1_column_proto_rawDescGZIP(), []int{1}
}

// SectionType section 类型
type SectionType int32

const (
	SectionType_SECTION_TYPE_UNSPECIFIED SectionType = 0
	SectionType_SECTION_TYPE_PINNED      SectionType = 1 // 固定，仅允许一个同类 section
	SectionType_SECTION_TYPE_HIDDEN      SectionType = 2 // 隐藏，仅允许一个同类 section
	SectionType_SECTION_TYPE_PUBLIC      SectionType = 3 // 公开，允许多个（默认）
	SectionType_SECTION_TYPE_SYSTEM      SectionType = 4 // 系统，允许多个，可自定义 section_name
)

// Enum value maps for SectionType.
var (
	SectionType_name = map[int32]string{
		0: "SECTION_TYPE_UNSPECIFIED",
		1: "SECTION_TYPE_PINNED",
		2: "SECTION_TYPE_HIDDEN",
		3: "SECTION_TYPE_PUBLIC",
		4: "SECTION_TYPE_SYSTEM",
	}
	SectionType_value = map[string]int32{
		"SECTION_TYPE_UNSPECIFIED": 0,
		"SECTION_TYPE_PINNED":      1,
		"SECTION_TYPE_HIDDEN":      2,
		"SECTION_TYPE_PUBLIC":      3,
		"SECTION_TYPE_SYSTEM":      4,
	}
)

func (x SectionType) Enum() *SectionType {
	p := new(SectionType)
	*p = x
	return p
}

func (x SectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_swanlab_data_v1_column_proto_enumTypes[2].Descriptor()
}

func (SectionType) Type() protoreflect.EnumType {
	return &file_swanlab_data_v1_column_proto_enumTypes[2]
}

func (x SectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SectionType.Descriptor instead.
func (SectionType) EnumDescriptor() ([]byte, []int) {
	return file_swanlab_data_v1_column_proto_rawDescGZIP(), []int{2}
}

// ColumnError 当 type=ANY 时描述错误信息，必填
type ColumnError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnError) Reset() {
	*x = ColumnError{}
	mi := &file_swanlab_data_v1_column_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnError) ProtoMessage() {}

func (x *ColumnError) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_data_v1_column_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnError.ProtoReflect.Descriptor instead.
func (*ColumnError) Descriptor() ([]byte, []int) {
	return file_swanlab_data_v1_column_proto_rawDescGZIP(), []int{0}
}

func (x *ColumnError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ColumnError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// YRange Y 轴显示范围
type YRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float64                `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YRange) Reset() {
	*x = YRange{}
	mi := &file_swanlab_data_v1_column_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YRange) ProtoMessage() {}

func (x *YRange) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_data_v1_column_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YRange.ProtoReflect.Descriptor instead.
func (*YRange) Descriptor() ([]byte, []int) {
	return file_swanlab_data_v1_column_proto_rawDescGZIP(), []int{1}
}

func (x *YRange) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *YRange) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// ColumnRecord 列定义，描述一个 metric key 的显示配置和归类规则。
// 通常在该 key 首次出现时随 LogRecord 之前发送一次。
//
// Section 归类优先级规则：
//  1. PINNED / HIDDEN / SCALAR / MEDIA 同类只允许一个 section；
//     PUBLIC / SYSTEM 允许多个。
//  2. PINNED / HIDDEN 只能放入各自默认 section，忽略 section_name。
//  3. SYSTEM 可通过 section_name 指定 section。
//  4. CUSTOM 列未设 section_name 时，归入 MEDIA 或 SCALAR 下；
//     设了 section_name 则放入 PUBLIC 类型下。
type ColumnRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 列类别，默认 CUSTOM
	Class ColumnClass `protobuf:"varint,1,opt,name=class,proto3,enum=swanlab.data.v1.ColumnClass" json:"class,omitempty"`
	// 数据类型，必填
	Type ColumnType `protobuf:"varint,2,opt,name=type,proto3,enum=swanlab.data.v1.ColumnType" json:"type,omitempty"`
	// 键名，必填，须与 MetricItem.key 对应
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// 显示名称，可选，不填时默认取 key
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// 错误信息，type=ANY 时必填
	Error *ColumnError `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// 自定义 section 名称，优先级高于由 key 推断的 section
	SectionName string `protobuf:"bytes,6,opt,name=section_name,json=sectionName,proto3" json:"section_name,omitempty"`
	// Section 类型，默认 PUBLIC
	SectionType SectionType `protobuf:"varint,7,opt,name=section_type,json=sectionType,proto3,enum=swanlab.data.v1.SectionType" json:"section_type,omitempty"`
	// Y 轴范围 [min, max]，可选
	YRange *YRange `protobuf:"bytes,8,opt,name=y_range,json=yRange,proto3" json:"y_range,omitempty"`
	// 图表索引，相同 chart_index 的列归入同一图表；不填则新建图表
	ChartIndex string `protobuf:"bytes,9,opt,name=chart_index,json=chartIndex,proto3" json:"chart_index,omitempty"`
	// 图表名称，仅对单实验图表生效
	ChartName string `protobuf:"bytes,10,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	// 指标名称，仅对单实验图表生效
	MetricName string `protobuf:"bytes,11,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	// 指标颜色列表，十六进制颜色值，如 "#FF5733"
	MetricColors  []string `protobuf:"bytes,12,rep,name=metric_colors,json=metricColors,proto3" json:"metric_colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnRecord) Reset() {
	*x = ColumnRecord{}
	mi := &file_swanlab_data_v1_column_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnRecord) ProtoMessage() {}

func (x *ColumnRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_data_v1_column_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnRecord.ProtoReflect.Descriptor instead.
func (*ColumnRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_data_v1_column_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnRecord) GetClass() ColumnClass {
	if x != nil {
		return x.Class
	}
	return ColumnClass_COLUMN_CLASS_UNSPECIFIED
}

func (x *ColumnRecord) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_UNSPECIFIED
}

func (x *ColumnRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ColumnRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnRecord) GetError() *ColumnError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ColumnRecord) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *ColumnRecord) GetSectionType() SectionType {
	if x != nil {
		return x.SectionType
	}
	return SectionType_SECTION_TYPE_UNSPECIFIED
}

func (x *ColumnRecord) GetYRange() *YRange {
	if x != nil {
		return x.YRange
	}
	return nil
}

func (x *ColumnRecord) GetChartIndex() string {
	if x != nil {
		return x.ChartIndex
	}
	return ""
}

func (x *ColumnRecord) GetChartName() string {
	if x != nil {
		return x.ChartName
	}
	return ""
}

func (x *ColumnRecord) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *ColumnRecord) GetMetricColors() []string {
	if x != nil {
		return x.MetricColors
	}
	return nil
}

var File_swanlab_data_v1_column_proto protoreflect.FileDescriptor

const file_swanlab_data_v1_column_proto_rawDesc = "" +
	"\n" +
	"\x1cswanlab/data/v1/column.proto\x12\x0fswanlab.data.v1\";\n" +
	"\vColumnError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x06YRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\"\xe9\x03\n" +
	"\fColumnRecord\x122\n" +
	"\x05class\x18\x01 \x01(\x0e2\x1c.swanlab.data.v1.ColumnClassR\x05class\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.swanlab.data.v1.ColumnTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1c.swanlab.data.v1.ColumnErrorR\x05error\x12!\n" +
	"\fsection_name\x18\x06 \x01(\tR\vsectionName\x12?\n" +
	"\fsection_type\x18\a \x01(\x0e2\x1c.swanlab.data.v1.SectionTypeR\vsectionType\x120\n" +
	"\ay_range\x18\b \x01(\v2\x17.swanlab.data.v1.YRangeR\x06yRange\x12\x1f\n" +
	"\vchart_index\x18\t \x01(\tR\n" +
	"chartIndex\x12\x1d\n" +
	"\n" +
	"chart_name\x18\n" +
	" \x01(\tR\tchartName\x12\x1f\n" +
	"\vmetric_name\x18\v \x01(\tR\n" +
	"metricName\x12#\n" +
	"\rmetric_colors\x18\f \x03(\tR\fmetricColors*D\n" +
	"\vColumnClass\x12\x1c\n" +
	"\x18COLUMN_CLASS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COLUMN_CLASS_CUSTOM\x10\x01*\x99\x01\n" +
	"\n" +
	"ColumnType\x12\x1b\n" +
	"\x17COLUMN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COLUMN_TYPE_FLOAT\x10\x01\x12\x15\n" +
	"\x11COLUMN_TYPE_IMAGE\x10\x02\x12\x15\n" +
	"\x11COLUMN_TYPE_AUDIO\x10\x03\x12\x14\n" +
	"\x10COLUMN_TYPE_TEXT\x10\x04\x12\x13\n" +
	"\x0fCOLUMN_TYPE_ANY\x10\x05*\x8f\x01\n" +
	"\vSectionType\x12\x1c\n" +
	"\x18SECTION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SECTION_TYPE_PINNED\x10\x01\x12\x17\n" +
	"\x13SECTION_TYPE_HIDDEN\x10\x02\x12\x17\n" +
	"\x13SECTION_TYPE_PUBLIC\x10\x03\x12\x17\n" +
	"\x13SECTION_TYPE_SYSTEM\x10\x04B?Z=github.com/swanhubx/swanlab/core/proto/swanlab/data/v1;datav1b\x06proto3"

var (
	file_swanlab_data_v1_column_proto_rawDescOnce sync.Once
	file_swanlab_data_v1_column_proto_rawDescData []byte
)

func file_swanlab_data_v1_column_proto_rawDescGZIP() []byte {
	file_swanlab_data_v1_column_proto_rawDescOnce.Do(func() {
		file_swanlab_data_v1_column_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_data_v1_column_proto_rawDesc), len(file_swanlab_data_v1_column_proto_rawDesc)))
	})
	return file_swanlab_data_v1_column_proto_rawDescData
}

var file_swanlab_data_v1_column_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_swanlab_data_v1_column_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_swanlab_data_v1_column_proto_goTypes = []any{
	(ColumnClass)(0),     // 0: swanlab.data.v1.ColumnClass
	(ColumnType)(0),      // 1: swanlab.data.v1.ColumnType
	(SectionType)(0),     // 2: swanlab.data.v1.SectionType
	(*ColumnError)(nil),  // 3: swanlab.data.v1.ColumnError
	(*YRange)(nil),       // 4: swanlab.data.v1.YRange
	(*ColumnRecord)(nil), // 5: swanlab.data.v1.ColumnRecord
}
var file_swanlab_data_v1_column_proto_depIdxs = []int32{
	0, // 0: swanlab.data.v1.ColumnRecord.class:type_name -> swanlab.data.v1.ColumnClass
	1, // 1: swanlab.data.v1.ColumnRecord.type:type_name -> swanlab.data.v1.ColumnType
	3, // 2: swanlab.data.v1.ColumnRecord.error:type_name -> swanlab.data.v1.ColumnError
	2, // 3: swanlab.data.v1.ColumnRecord.section_type:type_name -> swanlab.data.v1.SectionType
	4, // 4: swanlab.data.v1.ColumnRecord.y_range:type_name -> swanlab.data.v1.YRange
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_swanlab_data_v1_column_proto_init() }
func file_swanlab_data_v1_column_proto_init() {
	if File_swanlab_data_v1_column_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_data_v1_column_proto_rawDesc), len(file_swanlab_data_v1_column_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_data_v1_column_proto_goTypes,
		DependencyIndexes: file_swanlab_data_v1_column_proto_depIdxs,
		EnumInfos:         file_swanlab_data_v1_column_proto_enumTypes,
		MessageInfos:      file_swanlab_data_v1_column_proto_msgTypes,
	}.Build()
	File_swanlab_data_v1_column_proto = out.File
	file_swanlab_data_v1_column_proto_goTypes = nil
	file_swanlab_data_v1_column_proto_depIdxs = nil
}
