// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: swanlab/data/v1/image.proto

package datav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 一个 key 在某个 step 下记录的全部图像（1..N 张）。
type ImageValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 存储目录，相对于 run_dir，如 "media/images"
	Path          string       `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Items         []*ImageItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageValue) Reset() {
	*x = ImageValue{}
	mi := &file_swanlab_data_v1_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageValue) ProtoMessage() {}

func (x *ImageValue) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_data_v1_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageValue.ProtoReflect.Descriptor instead.
func (*ImageValue) Descriptor() ([]byte, []int) {
	return file_swanlab_data_v1_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageValue) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ImageValue) GetItems() []*ImageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单张图像的文件引用与元数据。
type ImageItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件名，如 "pred_10_a3f2.png"
	Filename      string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Sha256        string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`    // 文件大小（bytes）
	Format        string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"` // "png" | "jpeg" | "gif" | "webp"
	Width         int32  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Channels      int32  `protobuf:"varint,7,opt,name=channels,proto3" json:"channels,omitempty"` // 1=灰度, 3=RGB, 4=RGBA
	Caption       string `protobuf:"bytes,8,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageItem) Reset() {
	*x = ImageItem{}
	mi := &file_swanlab_data_v1_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageItem) ProtoMessage() {}

func (x *ImageItem) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_data_v1_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageItem.ProtoReflect.Descriptor instead.
func (*ImageItem) Descriptor() ([]byte, []int) {
	return file_swanlab_data_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageItem) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageItem) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ImageItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageItem) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImageItem) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageItem) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageItem) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *ImageItem) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

var File_swanlab_data_v1_image_proto protoreflect.FileDescriptor

const file_swanlab_data_v1_image_proto_rawDesc = "" +
	"\n" +
	"\x1bswanlab/data/v1/image.proto\x12\x0fswanlab.data.v1\"R\n" +
	"\n" +
	"ImageValue\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.swanlab.data.v1.ImageItemR\x05items\"\xcf\x01\n" +
	"\tImageItem\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x1a\n" +
	"\bchannels\x18\a \x01(\x05R\bchannels\x12\x18\n" +
	"\acaption\x18\b \x01(\tR\acaptionB?Z=github.com/swanhubx/swanlab/core/proto/swanlab/data/v1;datav1b\x06proto3"

var (
	file_swanlab_data_v1_image_proto_rawDescOnce sync.Once
	file_swanlab_data_v1_image_proto_rawDescData []byte
)

func file_swanlab_data_v1_image_proto_rawDescGZIP() []byte {
	file_swanlab_data_v1_image_proto_rawDescOnce.Do(func() {
		file_swanlab_data_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_data_v1_image_proto_rawDesc), len(file_swanlab_data_v1_image_proto_rawDesc)))
	})
	return file_swanlab_data_v1_image_proto_rawDescData
}

var file_swanlab_data_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_swanlab_data_v1_image_proto_goTypes = []any{
	(*ImageValue)(nil), // 0: swanlab.data.v1.ImageValue
	(*ImageItem)(nil),  // 1: swanlab.data.v1.ImageItem
}
var file_swanlab_data_v1_image_proto_depIdxs = []int32{
	1, // 0: swanlab.data.v1.ImageValue.items:type_name -> swanlab.data.v1.ImageItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_swanlab_data_v1_image_proto_init() }
func file_swanlab_data_v1_image_proto_init() {
	if File_swanlab_data_v1_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_data_v1_image_proto_rawDesc), len(file_swanlab_data_v1_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_data_v1_image_proto_goTypes,
		DependencyIndexes: file_swanlab_data_v1_image_proto_depIdxs,
		MessageInfos:      file_swanlab_data_v1_image_proto_msgTypes,
	}.Build()
	File_swanlab_data_v1_image_proto = out.File
	file_swanlab_data_v1_image_proto_goTypes = nil
	file_swanlab_data_v1_image_proto_depIdxs = nil
}
