// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/operation/v1/operation.proto

package operationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core 的生命周期状态。
type CoreState int32

const (
	CoreState_CORE_STATE_NOT_STARTED CoreState = 0 // Core 尚未启动
	CoreState_CORE_STATE_RUNNING     CoreState = 1 // Core 正在运行（处理数据）
	CoreState_CORE_STATE_FINISHED    CoreState = 2 // Core 已完成所有处理，可以安全退出
)

// Enum value maps for CoreState.
var (
	CoreState_name = map[int32]string{
		0: "CORE_STATE_NOT_STARTED",
		1: "CORE_STATE_RUNNING",
		2: "CORE_STATE_FINISHED",
	}
	CoreState_value = map[string]int32{
		"CORE_STATE_NOT_STARTED": 0,
		"CORE_STATE_RUNNING":     1,
		"CORE_STATE_FINISHED":    2,
	}
)

func (x CoreState) Enum() *CoreState {
	p := new(CoreState)
	*p = x
	return p
}

func (x CoreState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreState) Descriptor() protoreflect.EnumDescriptor {
	return file_swanlab_operation_v1_operation_proto_enumTypes[0].Descriptor()
}

func (CoreState) Type() protoreflect.EnumType {
	return &file_swanlab_operation_v1_operation_proto_enumTypes[0]
}

func (x CoreState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoreState.Descriptor instead.
func (CoreState) EnumDescriptor() ([]byte, []int) {
	return file_swanlab_operation_v1_operation_proto_rawDescGZIP(), []int{0}
}

// 当前/待上传文件进度显示快照。
// 仅在当前处理的 records 触发文件上传时填充；普通 record 同步保持为空。
type FileProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`          // 当前或待上传文件路径
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`       // 当前文件总量（通常为字节数）
	Uploaded      int64                  `protobuf:"varint,3,opt,name=uploaded,proto3" json:"uploaded,omitempty"` // 当前文件已完成量
	Rate          float64                `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`        // 当前文件处理速率（单位/秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileProgress) Reset() {
	*x = FileProgress{}
	mi := &file_swanlab_operation_v1_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProgress) ProtoMessage() {}

func (x *FileProgress) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_operation_v1_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProgress.ProtoReflect.Descriptor instead.
func (*FileProgress) Descriptor() ([]byte, []int) {
	return file_swanlab_operation_v1_operation_proto_rawDescGZIP(), []int{0}
}

func (x *FileProgress) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileProgress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FileProgress) GetUploaded() int64 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *FileProgress) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// Core 运行状态快照。
type OperationStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           CoreState              `protobuf:"varint,1,opt,name=state,proto3,enum=swanlab.operation.v1.CoreState" json:"state,omitempty"`        // Core 生命周期状态
	TotalNumber     int64                  `protobuf:"varint,2,opt,name=total_number,json=totalNumber,proto3" json:"total_number,omitempty"`             // 总文件数
	UploadedNumber  int64                  `protobuf:"varint,3,opt,name=uploaded_number,json=uploadedNumber,proto3" json:"uploaded_number,omitempty"`    // 已完成文件数
	TotalRecords    int64                  `protobuf:"varint,4,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`          // 已知总 Record 数；0 表示未知或未设置
	UploadedRecords int64                  `protobuf:"varint,5,opt,name=uploaded_records,json=uploadedRecords,proto3" json:"uploaded_records,omitempty"` // 已终止处理 Record 数
	TotalSize       int64                  `protobuf:"varint,6,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`                   // 总文件大小 (字节数)
	UploadedSize    int64                  `protobuf:"varint,7,opt,name=uploaded_size,json=uploadedSize,proto3" json:"uploaded_size,omitempty"`          // 已完成文件大小 (字节数)
	Rate            float64                `protobuf:"fixed64,8,opt,name=rate,proto3" json:"rate,omitempty"`                                             // 速率 (字节数/秒)
	Files           []*FileProgress        `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`                                             // 当前/待上传文件显示快照
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OperationStats) Reset() {
	*x = OperationStats{}
	mi := &file_swanlab_operation_v1_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStats) ProtoMessage() {}

func (x *OperationStats) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_operation_v1_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStats.ProtoReflect.Descriptor instead.
func (*OperationStats) Descriptor() ([]byte, []int) {
	return file_swanlab_operation_v1_operation_proto_rawDescGZIP(), []int{1}
}

func (x *OperationStats) GetState() CoreState {
	if x != nil {
		return x.State
	}
	return CoreState_CORE_STATE_NOT_STARTED
}

func (x *OperationStats) GetTotalNumber() int64 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (x *OperationStats) GetUploadedNumber() int64 {
	if x != nil {
		return x.UploadedNumber
	}
	return 0
}

func (x *OperationStats) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *OperationStats) GetUploadedRecords() int64 {
	if x != nil {
		return x.UploadedRecords
	}
	return 0
}

func (x *OperationStats) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *OperationStats) GetUploadedSize() int64 {
	if x != nil {
		return x.UploadedSize
	}
	return 0
}

func (x *OperationStats) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *OperationStats) GetFiles() []*FileProgress {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_swanlab_operation_v1_operation_proto protoreflect.FileDescriptor

const file_swanlab_operation_v1_operation_proto_rawDesc = "" +
	"\n" +
	"$swanlab/operation/v1/operation.proto\x12\x14swanlab.operation.v1\"h\n" +
	"\fFileProgress\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1a\n" +
	"\buploaded\x18\x03 \x01(\x03R\buploaded\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x01R\x04rate\"\xf5\x02\n" +
	"\x0eOperationStats\x125\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1f.swanlab.operation.v1.CoreStateR\x05state\x12!\n" +
	"\ftotal_number\x18\x02 \x01(\x03R\vtotalNumber\x12'\n" +
	"\x0fuploaded_number\x18\x03 \x01(\x03R\x0euploadedNumber\x12#\n" +
	"\rtotal_records\x18\x04 \x01(\x03R\ftotalRecords\x12)\n" +
	"\x10uploaded_records\x18\x05 \x01(\x03R\x0fuploadedRecords\x12\x1d\n" +
	"\n" +
	"total_size\x18\x06 \x01(\x03R\ttotalSize\x12#\n" +
	"\ruploaded_size\x18\a \x01(\x03R\fuploadedSize\x12\x12\n" +
	"\x04rate\x18\b \x01(\x01R\x04rate\x128\n" +
	"\x05files\x18\t \x03(\v2\".swanlab.operation.v1.FileProgressR\x05files*X\n" +
	"\tCoreState\x12\x1a\n" +
	"\x16CORE_STATE_NOT_STARTED\x10\x00\x12\x16\n" +
	"\x12CORE_STATE_RUNNING\x10\x01\x12\x17\n" +
	"\x13CORE_STATE_FINISHED\x10\x02BIZGgithub.com/swanhubx/swanlab/core/proto/swanlab/operation/v1;operationv1b\x06proto3"

var (
	file_swanlab_operation_v1_operation_proto_rawDescOnce sync.Once
	file_swanlab_operation_v1_operation_proto_rawDescData []byte
)

func file_swanlab_operation_v1_operation_proto_rawDescGZIP() []byte {
	file_swanlab_operation_v1_operation_proto_rawDescOnce.Do(func() {
		file_swanlab_operation_v1_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_operation_v1_operation_proto_rawDesc), len(file_swanlab_operation_v1_operation_proto_rawDesc)))
	})
	return file_swanlab_operation_v1_operation_proto_rawDescData
}

var file_swanlab_operation_v1_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_swanlab_operation_v1_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_swanlab_operation_v1_operation_proto_goTypes = []any{
	(CoreState)(0),         // 0: swanlab.operation.v1.CoreState
	(*FileProgress)(nil),   // 1: swanlab.operation.v1.FileProgress
	(*OperationStats)(nil), // 2: swanlab.operation.v1.OperationStats
}
var file_swanlab_operation_v1_operation_proto_depIdxs = []int32{
	0, // 0: swanlab.operation.v1.OperationStats.state:type_name -> swanlab.operation.v1.CoreState
	1, // 1: swanlab.operation.v1.OperationStats.files:type_name -> swanlab.operation.v1.FileProgress
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_swanlab_operation_v1_operation_proto_init() }
func file_swanlab_operation_v1_operation_proto_init() {
	if File_swanlab_operation_v1_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_operation_v1_operation_proto_rawDesc), len(file_swanlab_operation_v1_operation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_operation_v1_operation_proto_goTypes,
		DependencyIndexes: file_swanlab_operation_v1_operation_proto_depIdxs,
		EnumInfos:         file_swanlab_operation_v1_operation_proto_enumTypes,
		MessageInfos:      file_swanlab_operation_v1_operation_proto_msgTypes,
	}.Build()
	File_swanlab_operation_v1_operation_proto = out.File
	file_swanlab_operation_v1_operation_proto_goTypes = nil
	file_swanlab_operation_v1_operation_proto_depIdxs = nil
}
