name: Bug report
description: Create a bug report
labels:
  - 🐛 bug
  - 🤔 unconfirmed
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!

        **Please note:**
        1. General usage questions are not bug reports. If you're looking for support with your train, you can consider asking for help on the [community](https://docs.swanlab.cn/guide_cloud/community/online-support.html) instead.
        2. `swanlab` can be integrated into other AI training frameworks, therefore bugs in other frameworks might cause errors in training that use `swanlab`. Please make sure that the bug you're experiencing is _caused by_ by `swanlab`.
        3. If your issue appears to be network-related, you might want to [Report a network-related problem](https://github.com/SwanHubX/SwanLab/issues/new/choose) instead.
        4. Bug reports without a reproduction may be closed immediately.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Verifications
      options:
        - label: I've verified that the problem I'm experiencing isn't covered in [the docs](https://docs.swanlab.cn).
          required: true
        - label: I've searched for similar, existing issues on [GitHub](https://github.com/SwanHubX/SwanLab/issues).
          required: true
        - label: I have confirmed that this issue was not caused by a network error.
          required: true
  - type: textarea
    attributes:
      label: Mandatory reproduction Code
      description: |
        Please attach the code that can reproduce the bug, which can be a snippet, file, or repository. Our [template](https://github.com/SwanHubX/swanlab-bug-repro) might help you quickly create a new repository/snippet.
      value: |
        The core code is …
        
        Steps to reproduce:
        1. Open reproduction
        2. Click on …
        3. See error: …
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Creating a good reproduction takes time.**

        To help us resolve the issue quickly, please simplify the reproduction as much as possible by removing any unnecessary code, files, and dependencies that are not directly related to the problem. The easier it is for us to see the issue, the faster we can help you.
  - type: textarea
    attributes:
      label: Error message
      description: Please provide a complete error stack trace so we can quickly identify the issue.
    validations:
      required: true