name: Network report
description: Report a network-related problem
labels:
  - 👾 network
  - 🤔 unconfirmed
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a network issue!

        **Critical Notes for Network Issues:**
        1. Network problems often involve local environment (proxies, firewalls), server status, or client configs. Please provide detailed context.
        2. Ensure the issue is SwanLab-specific: e.g., you can access [https://swanlab.cn](https://swanlab.cn) via a browser, but SwanLab SDK fails.
        3. Include network test results (ping/traceroute/curl) and raw error logs.
        4. Reports without sufficient network details may be closed temporarily.
  - type: checkboxes
    attributes:
      label: Verifications
      options:
        - label: I've searched [GitHub Issues](https://github.com/SwanHubX/SwanLab/issues) for similar network problems.
          required: true
        - label: I've tested basic connectivity to SwanLab services.
          required: true
        - label: I have attempted basic troubleshooting steps, including restarting the device, switching networks (Wi-Fi/mobile data), and temporarily disabling VPN/proxy.
          required: true
  - type: textarea
    attributes:
      label: Problem Description
      description: A clear, concise summary of the network issue.
    validations:
      required: true
  - type: input
    attributes:
      label: SwanLab Version
      description: E.g., 0.6.11 (run `swanlab --version` or `pip show swanlab`)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Network Environment
      description: E.g., OS, network type, proxy/VPN, firewall, corporate network, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ping Results
      description: Run `ping swanlab.cn` and paste the complete results.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Traceroute Results
      description: Run `traceroute swanlab.cn` (Windows `tracert swanlab.cn`) and paste the complete results.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Curl Results
      description: Run `curl -v https://swanlab.cn` and paste the complete results.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Why This Matters:**
        Network issues require context about your environment and connectivity. Logs like `curl -v` or `traceroute` help us distinguish between client misconfigurations, proxy blocks, or server-side problems. Thank you for your patience—we’ll prioritize resolving this once we have enough details!
