blank_issues_enabled: false
contact_links:
  - name: 报告自托管问题
    url: https://github.com/SwanHubX/self-hosted/issues
    about: 报告与自托管 SwanLab 相关的问题
  - name: 查看文档
    url: https://docs.swanlab.cn
    about: 查阅官方文档获取常见问题解答
  - name: 获取 AI 支持
    url: https://chat.swanlab.cn
    about: 与我们的 AI 助手交流，快速获取问题解答
  - name: 获取社区支持
    url: https://docs.swanlab.cn/guide_cloud/community/online-support.html
    about: 在有经验的开发者可以提供帮助的社区发布您的问题