blank_issues_enabled: false
contact_links:
  - name: Report self-hosting issue
    url: https://github.com/SwanHubX/self-hosted/issues
    about: Report issues related to self-hosting SwanLab
  - name: View documentation
    url: https://docs.swanlab.cn
    about: Check out the official docs for answers to common questions
  - name: Get AI support
    url: https://chat.swanlab.cn
    about: Chat with our AI assistant for quick answers to your questions
  - name: Get community support
    url: https://docs.swanlab.cn/guide_cloud/community/online-support.html
    about: Post your question where experienced developers can offer assistance