# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swanlab/system/v1/console.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swanlab/system/v1/console.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fswanlab/system/v1/console.proto\x12\x11swanlab.system.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"{\n\rConsoleRecord\x12\x0c\n\x04line\x18\x01 \x01(\t\x12-\n\x06stream\x18\x02 \x01(\x0e\x32\x1d.swanlab.system.v1.StreamType\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*Y\n\nStreamType\x12\x1b\n\x17STREAM_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12STREAM_TYPE_STDOUT\x10\x01\x12\x16\n\x12STREAM_TYPE_STDERR\x10\x02\x42\x43ZAgithub.com/swanhubx/swanlab/core/proto/swanlab/system/v1;systemv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swanlab.system.v1.console_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/swanhubx/swanlab/core/proto/swanlab/system/v1;systemv1'
  _globals['_STREAMTYPE']._serialized_start=212
  _globals['_STREAMTYPE']._serialized_end=301
  _globals['_CONSOLERECORD']._serialized_start=87
  _globals['_CONSOLERECORD']._serialized_end=210
# @@protoc_insertion_point(module_scope)
