# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swanlab/system/v1/env.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swanlab/system/v1/env.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bswanlab/system/v1/env.proto\x12\x11swanlab.system.v1\"\x1e\n\x0eMetadataRecord\x12\x0c\n\x04path\x18\x01 \x01(\t\"\"\n\x12RequirementsRecord\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1b\n\x0b\x43ondaRecord\x12\x0c\n\x04path\x18\x01 \x01(\tBCZAgithub.com/swanhubx/swanlab/core/proto/swanlab/system/v1;systemv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swanlab.system.v1.env_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/swanhubx/swanlab/core/proto/swanlab/system/v1;systemv1'
  _globals['_METADATARECORD']._serialized_start=50
  _globals['_METADATARECORD']._serialized_end=80
  _globals['_REQUIREMENTSRECORD']._serialized_start=82
  _globals['_REQUIREMENTSRECORD']._serialized_end=116
  _globals['_CONDARECORD']._serialized_start=118
  _globals['_CONDARECORD']._serialized_end=145
# @@protoc_insertion_point(module_scope)
