// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: swanlab/grpc/probe/v1/probe.proto

package probev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProbeService_DeliverProbeStart_FullMethodName  = "/swanlab.grpc.probe.v1.ProbeService/DeliverProbeStart"
	ProbeService_DeliverProbeFinish_FullMethodName = "/swanlab.grpc.probe.v1.ProbeService/DeliverProbeFinish"
)

// ProbeServiceClient is the client API for ProbeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProbeService 用于启动硬件信息采集服务
type ProbeServiceClient interface {
	// DeliverProbeStart 接收 ProbeSettings，启动硬件信息采集
	DeliverProbeStart(ctx context.Context, in *DeliverProbeStartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeliverProbeFinish 结束硬件信息采集
	DeliverProbeFinish(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type probeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProbeServiceClient(cc grpc.ClientConnInterface) ProbeServiceClient {
	return &probeServiceClient{cc}
}

func (c *probeServiceClient) DeliverProbeStart(ctx context.Context, in *DeliverProbeStartRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProbeService_DeliverProbeStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeServiceClient) DeliverProbeFinish(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProbeService_DeliverProbeFinish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProbeServiceServer is the server API for ProbeService service.
// All implementations must embed UnimplementedProbeServiceServer
// for forward compatibility.
//
// ProbeService 用于启动硬件信息采集服务
type ProbeServiceServer interface {
	// DeliverProbeStart 接收 ProbeSettings，启动硬件信息采集
	DeliverProbeStart(context.Context, *DeliverProbeStartRequest) (*emptypb.Empty, error)
	// DeliverProbeFinish 结束硬件信息采集
	DeliverProbeFinish(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedProbeServiceServer()
}

// UnimplementedProbeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProbeServiceServer struct{}

func (UnimplementedProbeServiceServer) DeliverProbeStart(context.Context, *DeliverProbeStartRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverProbeStart not implemented")
}
func (UnimplementedProbeServiceServer) DeliverProbeFinish(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverProbeFinish not implemented")
}
func (UnimplementedProbeServiceServer) mustEmbedUnimplementedProbeServiceServer() {}
func (UnimplementedProbeServiceServer) testEmbeddedByValue()                      {}

// UnsafeProbeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProbeServiceServer will
// result in compilation errors.
type UnsafeProbeServiceServer interface {
	mustEmbedUnimplementedProbeServiceServer()
}

func RegisterProbeServiceServer(s grpc.ServiceRegistrar, srv ProbeServiceServer) {
	// If the following call panics, it indicates UnimplementedProbeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProbeService_ServiceDesc, srv)
}

func _ProbeService_DeliverProbeStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverProbeStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).DeliverProbeStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_DeliverProbeStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).DeliverProbeStart(ctx, req.(*DeliverProbeStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeService_DeliverProbeFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).DeliverProbeFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_DeliverProbeFinish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).DeliverProbeFinish(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ProbeService_ServiceDesc is the grpc.ServiceDesc for ProbeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProbeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swanlab.grpc.probe.v1.ProbeService",
	HandlerType: (*ProbeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverProbeStart",
			Handler:    _ProbeService_DeliverProbeStart_Handler,
		},
		{
			MethodName: "DeliverProbeFinish",
			Handler:    _ProbeService_DeliverProbeFinish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swanlab/grpc/probe/v1/probe.proto",
}
