// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/terminal/v1/log.proto

package terminalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 终端日志级别。
// LOG_LEVEL_INFO 为默认级别，表示普通终端输出。
// 注意：stderr 不一定代表错误，默认仍按 LOG_LEVEL_INFO 处理，
// 例如进度条、警告信息等。
// LOG_LEVEL_ERROR 表示实验错误输出，通常用于最终实验报错信息。
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_INFO  LogLevel = 0
	LogLevel_LOG_LEVEL_ERROR LogLevel = 1
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_INFO",
		1: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_INFO":  0,
		"LOG_LEVEL_ERROR": 1,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_swanlab_terminal_v1_log_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_swanlab_terminal_v1_log_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_swanlab_terminal_v1_log_proto_rawDescGZIP(), []int{0}
}

// 终端代理捕获的单行输出。
// 由 console.proxy_type 配置决定捕获 stdout、stderr 或两者。
// 超出 console.max_log_length 的部分由 SDK 在写入前截断。
type LogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=swanlab.terminal.v1.LogLevel" json:"level,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Epoch         int64                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_swanlab_terminal_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_terminal_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_terminal_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogRecord) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_INFO
}

func (x *LogRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRecord) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_swanlab_terminal_v1_log_proto protoreflect.FileDescriptor

const file_swanlab_terminal_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x1dswanlab/terminal/v1/log.proto\x12\x13swanlab.terminal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\tLogRecord\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x123\n" +
	"\x05level\x18\x02 \x01(\x0e2\x1d.swanlab.terminal.v1.LogLevelR\x05level\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x03R\x05epoch*3\n" +
	"\bLogLevel\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x01BGZEgithub.com/swanhubx/swanlab/core/proto/swanlab/terminal/v1;terminalv1b\x06proto3"

var (
	file_swanlab_terminal_v1_log_proto_rawDescOnce sync.Once
	file_swanlab_terminal_v1_log_proto_rawDescData []byte
)

func file_swanlab_terminal_v1_log_proto_rawDescGZIP() []byte {
	file_swanlab_terminal_v1_log_proto_rawDescOnce.Do(func() {
		file_swanlab_terminal_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_terminal_v1_log_proto_rawDesc), len(file_swanlab_terminal_v1_log_proto_rawDesc)))
	})
	return file_swanlab_terminal_v1_log_proto_rawDescData
}

var file_swanlab_terminal_v1_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_swanlab_terminal_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_swanlab_terminal_v1_log_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: swanlab.terminal.v1.LogLevel
	(*LogRecord)(nil),             // 1: swanlab.terminal.v1.LogRecord
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_swanlab_terminal_v1_log_proto_depIdxs = []int32{
	0, // 0: swanlab.terminal.v1.LogRecord.level:type_name -> swanlab.terminal.v1.LogLevel
	2, // 1: swanlab.terminal.v1.LogRecord.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_swanlab_terminal_v1_log_proto_init() }
func file_swanlab_terminal_v1_log_proto_init() {
	if File_swanlab_terminal_v1_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_terminal_v1_log_proto_rawDesc), len(file_swanlab_terminal_v1_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_terminal_v1_log_proto_goTypes,
		DependencyIndexes: file_swanlab_terminal_v1_log_proto_depIdxs,
		EnumInfos:         file_swanlab_terminal_v1_log_proto_enumTypes,
		MessageInfos:      file_swanlab_terminal_v1_log_proto_msgTypes,
	}.Build()
	File_swanlab_terminal_v1_log_proto = out.File
	file_swanlab_terminal_v1_log_proto_goTypes = nil
	file_swanlab_terminal_v1_log_proto_depIdxs = nil
}
