// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/run/v1/run.proto

package runv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunState int32

const (
	RunState_RUN_STATE_RUNNING  RunState = 0
	RunState_RUN_STATE_FINISHED RunState = 1 // 正常结束
	RunState_RUN_STATE_CRASHED  RunState = 2 // 异常退出
	RunState_RUN_STATE_ABORTED  RunState = 3 // 用户主动中断（KeyboardInterrupt 等）
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_RUNNING",
		1: "RUN_STATE_FINISHED",
		2: "RUN_STATE_CRASHED",
		3: "RUN_STATE_ABORTED",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_RUNNING":  0,
		"RUN_STATE_FINISHED": 1,
		"RUN_STATE_CRASHED":  2,
		"RUN_STATE_ABORTED":  3,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_swanlab_run_v1_run_proto_enumTypes[0].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_swanlab_run_v1_run_proto_enumTypes[0]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_swanlab_run_v1_run_proto_rawDescGZIP(), []int{0}
}

type ResumeMode int32

const (
	ResumeMode_RESUME_MODE_NEVER ResumeMode = 0
	ResumeMode_RESUME_MODE_ALLOW ResumeMode = 1
	ResumeMode_RESUME_MODE_MUST  ResumeMode = 2
)

// Enum value maps for ResumeMode.
var (
	ResumeMode_name = map[int32]string{
		0: "RESUME_MODE_NEVER",
		1: "RESUME_MODE_ALLOW",
		2: "RESUME_MODE_MUST",
	}
	ResumeMode_value = map[string]int32{
		"RESUME_MODE_NEVER": 0,
		"RESUME_MODE_ALLOW": 1,
		"RESUME_MODE_MUST":  2,
	}
)

func (x ResumeMode) Enum() *ResumeMode {
	p := new(ResumeMode)
	*p = x
	return p
}

func (x ResumeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResumeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_swanlab_run_v1_run_proto_enumTypes[1].Descriptor()
}

func (ResumeMode) Type() protoreflect.EnumType {
	return &file_swanlab_run_v1_run_proto_enumTypes[1]
}

func (x ResumeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResumeMode.Descriptor instead.
func (ResumeMode) EnumDescriptor() ([]byte, []int) {
	return file_swanlab_run_v1_run_proto_rawDescGZIP(), []int{1}
}

// Run 创建记录，对应 swanlab.init(...) 调用，由sdk前端生成并同步交给后端，部分字段如果为空需要sdk后端填充
type StartRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"` // 组织或用户名
	Public        bool                   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Group         string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	JobType       string                 `protobuf:"bytes,8,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Color         string                 `protobuf:"bytes,9,opt,name=color,proto3" json:"color,omitempty"` // 十六进制颜色，如 "#FF5733"，如果为空则由sdk后端生成
	Id            string                 `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	Resume        ResumeMode             `protobuf:"varint,11,opt,name=resume,proto3,enum=swanlab.run.v1.ResumeMode" json:"resume,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecord) Reset() {
	*x = StartRecord{}
	mi := &file_swanlab_run_v1_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecord) ProtoMessage() {}

func (x *StartRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_run_v1_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecord.ProtoReflect.Descriptor instead.
func (*StartRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_run_v1_run_proto_rawDescGZIP(), []int{0}
}

func (x *StartRecord) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *StartRecord) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *StartRecord) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *StartRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StartRecord) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StartRecord) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *StartRecord) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *StartRecord) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *StartRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartRecord) GetResume() ResumeMode {
	if x != nil {
		return x.Resume
	}
	return ResumeMode_RESUME_MODE_NEVER
}

func (x *StartRecord) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// Run 创建响应
type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 请求是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 请求失败的响应
	Run           *StartRecord           `protobuf:"bytes,3,opt,name=run,proto3" json:"run,omitempty"`          // 最终创建的 Run 记录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_swanlab_run_v1_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_run_v1_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_run_v1_run_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartResponse) GetRun() *StartRecord {
	if x != nil {
		return x.Run
	}
	return nil
}

// Run 结束记录，对应 swanlab.finish() 或进程退出，由sdk前端生成并同步交给后端
type FinishRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State RunState               `protobuf:"varint,1,opt,name=state,proto3,enum=swanlab.run.v1.RunState" json:"state,omitempty"`
	// 异常信息，state=CRASHED 时填充
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRecord) Reset() {
	*x = FinishRecord{}
	mi := &file_swanlab_run_v1_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRecord) ProtoMessage() {}

func (x *FinishRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_run_v1_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRecord.ProtoReflect.Descriptor instead.
func (*FinishRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_run_v1_run_proto_rawDescGZIP(), []int{2}
}

func (x *FinishRecord) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_RUNNING
}

func (x *FinishRecord) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FinishRecord) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// Run 结束响应
type FinishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 请求是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 请求失败的响应
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishResponse) Reset() {
	*x = FinishResponse{}
	mi := &file_swanlab_run_v1_run_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishResponse) ProtoMessage() {}

func (x *FinishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_run_v1_run_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishResponse.ProtoReflect.Descriptor instead.
func (*FinishResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_run_v1_run_proto_rawDescGZIP(), []int{3}
}

func (x *FinishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinishResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_swanlab_run_v1_run_proto protoreflect.FileDescriptor

const file_swanlab_run_v1_run_proto_rawDesc = "" +
	"\n" +
	"\x18swanlab/run/v1/run.proto\x12\x0eswanlab.run.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x02\n" +
	"\vStartRecord\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\x12\x19\n" +
	"\bjob_type\x18\b \x01(\tR\ajobType\x12\x14\n" +
	"\x05color\x18\t \x01(\tR\x05color\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x122\n" +
	"\x06resume\x18\v \x01(\x0e2\x1a.swanlab.run.v1.ResumeModeR\x06resume\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"r\n" +
	"\rStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x03run\x18\x03 \x01(\v2\x1b.swanlab.run.v1.StartRecordR\x03run\"\x91\x01\n" +
	"\fFinishRecord\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.swanlab.run.v1.RunStateR\x05state\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12;\n" +
	"\vfinished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"D\n" +
	"\x0eFinishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*g\n" +
	"\bRunState\x12\x15\n" +
	"\x11RUN_STATE_RUNNING\x10\x00\x12\x16\n" +
	"\x12RUN_STATE_FINISHED\x10\x01\x12\x15\n" +
	"\x11RUN_STATE_CRASHED\x10\x02\x12\x15\n" +
	"\x11RUN_STATE_ABORTED\x10\x03*P\n" +
	"\n" +
	"ResumeMode\x12\x15\n" +
	"\x11RESUME_MODE_NEVER\x10\x00\x12\x15\n" +
	"\x11RESUME_MODE_ALLOW\x10\x01\x12\x14\n" +
	"\x10RESUME_MODE_MUST\x10\x02B=Z;github.com/swanhubx/swanlab/core/proto/swanlab/run/v1;runv1b\x06proto3"

var (
	file_swanlab_run_v1_run_proto_rawDescOnce sync.Once
	file_swanlab_run_v1_run_proto_rawDescData []byte
)

func file_swanlab_run_v1_run_proto_rawDescGZIP() []byte {
	file_swanlab_run_v1_run_proto_rawDescOnce.Do(func() {
		file_swanlab_run_v1_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_run_v1_run_proto_rawDesc), len(file_swanlab_run_v1_run_proto_rawDesc)))
	})
	return file_swanlab_run_v1_run_proto_rawDescData
}

var file_swanlab_run_v1_run_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_swanlab_run_v1_run_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_swanlab_run_v1_run_proto_goTypes = []any{
	(RunState)(0),                 // 0: swanlab.run.v1.RunState
	(ResumeMode)(0),               // 1: swanlab.run.v1.ResumeMode
	(*StartRecord)(nil),           // 2: swanlab.run.v1.StartRecord
	(*StartResponse)(nil),         // 3: swanlab.run.v1.StartResponse
	(*FinishRecord)(nil),          // 4: swanlab.run.v1.FinishRecord
	(*FinishResponse)(nil),        // 5: swanlab.run.v1.FinishResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_swanlab_run_v1_run_proto_depIdxs = []int32{
	1, // 0: swanlab.run.v1.StartRecord.resume:type_name -> swanlab.run.v1.ResumeMode
	6, // 1: swanlab.run.v1.StartRecord.started_at:type_name -> google.protobuf.Timestamp
	2, // 2: swanlab.run.v1.StartResponse.run:type_name -> swanlab.run.v1.StartRecord
	0, // 3: swanlab.run.v1.FinishRecord.state:type_name -> swanlab.run.v1.RunState
	6, // 4: swanlab.run.v1.FinishRecord.finished_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_swanlab_run_v1_run_proto_init() }
func file_swanlab_run_v1_run_proto_init() {
	if File_swanlab_run_v1_run_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_run_v1_run_proto_rawDesc), len(file_swanlab_run_v1_run_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_run_v1_run_proto_goTypes,
		DependencyIndexes: file_swanlab_run_v1_run_proto_depIdxs,
		EnumInfos:         file_swanlab_run_v1_run_proto_enumTypes,
		MessageInfos:      file_swanlab_run_v1_run_proto_msgTypes,
	}.Build()
	File_swanlab_run_v1_run_proto = out.File
	file_swanlab_run_v1_run_proto_goTypes = nil
	file_swanlab_run_v1_run_proto_depIdxs = nil
}
