// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/metric/data/v1/data.proto

package datav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColumnType 列的数据类型
type ColumnType int32

const (
	ColumnType_COLUMN_TYPE_UNSPECIFIED ColumnType = 0
	ColumnType_COLUMN_TYPE_FLOAT       ColumnType = 1 // 标量
	ColumnType_COLUMN_TYPE_IMAGE       ColumnType = 2 // 图像
	ColumnType_COLUMN_TYPE_AUDIO       ColumnType = 3 // 音频
	ColumnType_COLUMN_TYPE_TEXT        ColumnType = 4 // 文本
	ColumnType_COLUMN_TYPE_VIDEO       ColumnType = 5 // 视频
	ColumnType_COLUMN_TYPE_ECHARTS     ColumnType = 6 // ECharts 图表
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0: "COLUMN_TYPE_UNSPECIFIED",
		1: "COLUMN_TYPE_FLOAT",
		2: "COLUMN_TYPE_IMAGE",
		3: "COLUMN_TYPE_AUDIO",
		4: "COLUMN_TYPE_TEXT",
		5: "COLUMN_TYPE_VIDEO",
		6: "COLUMN_TYPE_ECHARTS",
	}
	ColumnType_value = map[string]int32{
		"COLUMN_TYPE_UNSPECIFIED": 0,
		"COLUMN_TYPE_FLOAT":       1,
		"COLUMN_TYPE_IMAGE":       2,
		"COLUMN_TYPE_AUDIO":       3,
		"COLUMN_TYPE_TEXT":        4,
		"COLUMN_TYPE_VIDEO":       5,
		"COLUMN_TYPE_ECHARTS":     6,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_swanlab_metric_data_v1_data_proto_enumTypes[0].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_swanlab_metric_data_v1_data_proto_enumTypes[0]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_swanlab_metric_data_v1_data_proto_rawDescGZIP(), []int{0}
}

// 对应一次 swanlab.log({...}, step=N) 调用中的单条数据记录。
// 一次调用可产生多条 DataRecord，每条对应 dict 中的一个 key。
type DataRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 记录的 key，如 "train/loss"
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 用户显式传入或由 SDK 自动递增的全局步数
	Step int64 `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	// 数据类型
	Type ColumnType `protobuf:"varint,3,opt,name=type,proto3,enum=swanlab.metric.data.v1.ColumnType" json:"type,omitempty"`
	// 记录的时间戳
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*DataRecord_Scalar
	//	*DataRecord_Images
	//	*DataRecord_Audios
	//	*DataRecord_Videos
	//	*DataRecord_Texts
	//	*DataRecord_Echarts
	Value         isDataRecord_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRecord) Reset() {
	*x = DataRecord{}
	mi := &file_swanlab_metric_data_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRecord) ProtoMessage() {}

func (x *DataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_metric_data_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRecord.ProtoReflect.Descriptor instead.
func (*DataRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_metric_data_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *DataRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataRecord) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *DataRecord) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_COLUMN_TYPE_UNSPECIFIED
}

func (x *DataRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataRecord) GetValue() isDataRecord_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DataRecord) GetScalar() *ScalarValue {
	if x != nil {
		if x, ok := x.Value.(*DataRecord_Scalar); ok {
			return x.Scalar
		}
	}
	return nil
}

func (x *DataRecord) GetImages() *ImageValue {
	if x != nil {
		if x, ok := x.Value.(*DataRecord_Images); ok {
			return x.Images
		}
	}
	return nil
}

func (x *DataRecord) GetAudios() *AudioValue {
	if x != nil {
		if x, ok := x.Value.(*DataRecord_Audios); ok {
			return x.Audios
		}
	}
	return nil
}

func (x *DataRecord) GetVideos() *VideoValue {
	if x != nil {
		if x, ok := x.Value.(*DataRecord_Videos); ok {
			return x.Videos
		}
	}
	return nil
}

func (x *DataRecord) GetTexts() *TextValue {
	if x != nil {
		if x, ok := x.Value.(*DataRecord_Texts); ok {
			return x.Texts
		}
	}
	return nil
}

func (x *DataRecord) GetEcharts() *EChartsValue {
	if x != nil {
		if x, ok := x.Value.(*DataRecord_Echarts); ok {
			return x.Echarts
		}
	}
	return nil
}

type isDataRecord_Value interface {
	isDataRecord_Value()
}

type DataRecord_Scalar struct {
	Scalar *ScalarValue `protobuf:"bytes,10,opt,name=scalar,proto3,oneof"`
}

type DataRecord_Images struct {
	Images *ImageValue `protobuf:"bytes,11,opt,name=images,proto3,oneof"`
}

type DataRecord_Audios struct {
	Audios *AudioValue `protobuf:"bytes,12,opt,name=audios,proto3,oneof"`
}

type DataRecord_Videos struct {
	Videos *VideoValue `protobuf:"bytes,13,opt,name=videos,proto3,oneof"`
}

type DataRecord_Texts struct {
	Texts *TextValue `protobuf:"bytes,14,opt,name=texts,proto3,oneof"`
}

type DataRecord_Echarts struct {
	Echarts *EChartsValue `protobuf:"bytes,15,opt,name=echarts,proto3,oneof"`
}

func (*DataRecord_Scalar) isDataRecord_Value() {}

func (*DataRecord_Images) isDataRecord_Value() {}

func (*DataRecord_Audios) isDataRecord_Value() {}

func (*DataRecord_Videos) isDataRecord_Value() {}

func (*DataRecord_Texts) isDataRecord_Value() {}

func (*DataRecord_Echarts) isDataRecord_Value() {}

var File_swanlab_metric_data_v1_data_proto protoreflect.FileDescriptor

const file_swanlab_metric_data_v1_data_proto_rawDesc = "" +
	"\n" +
	"!swanlab/metric/data/v1/data.proto\x12\x16swanlab.metric.data.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*swanlab/metric/data/v1/scalar/scalar.proto\x1a(swanlab/metric/data/v1/media/image.proto\x1a(swanlab/metric/data/v1/media/audio.proto\x1a(swanlab/metric/data/v1/media/video.proto\x1a'swanlab/metric/data/v1/media/text.proto\x1a*swanlab/metric/data/v1/media/echarts.proto\"\xa3\x04\n" +
	"\n" +
	"DataRecord\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04step\x18\x02 \x01(\x03R\x04step\x126\n" +
	"\x04type\x18\x03 \x01(\x0e2\".swanlab.metric.data.v1.ColumnTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12=\n" +
	"\x06scalar\x18\n" +
	" \x01(\v2#.swanlab.metric.data.v1.ScalarValueH\x00R\x06scalar\x12<\n" +
	"\x06images\x18\v \x01(\v2\".swanlab.metric.data.v1.ImageValueH\x00R\x06images\x12<\n" +
	"\x06audios\x18\f \x01(\v2\".swanlab.metric.data.v1.AudioValueH\x00R\x06audios\x12<\n" +
	"\x06videos\x18\r \x01(\v2\".swanlab.metric.data.v1.VideoValueH\x00R\x06videos\x129\n" +
	"\x05texts\x18\x0e \x01(\v2!.swanlab.metric.data.v1.TextValueH\x00R\x05texts\x12@\n" +
	"\aecharts\x18\x0f \x01(\v2$.swanlab.metric.data.v1.EChartsValueH\x00R\aechartsB\a\n" +
	"\x05value*\xb4\x01\n" +
	"\n" +
	"ColumnType\x12\x1b\n" +
	"\x17COLUMN_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COLUMN_TYPE_FLOAT\x10\x01\x12\x15\n" +
	"\x11COLUMN_TYPE_IMAGE\x10\x02\x12\x15\n" +
	"\x11COLUMN_TYPE_AUDIO\x10\x03\x12\x14\n" +
	"\x10COLUMN_TYPE_TEXT\x10\x04\x12\x15\n" +
	"\x11COLUMN_TYPE_VIDEO\x10\x05\x12\x17\n" +
	"\x13COLUMN_TYPE_ECHARTS\x10\x06BFZDgithub.com/swanhubx/swanlab/core/proto/swanlab/metric/data/v1;datav1b\x06proto3"

var (
	file_swanlab_metric_data_v1_data_proto_rawDescOnce sync.Once
	file_swanlab_metric_data_v1_data_proto_rawDescData []byte
)

func file_swanlab_metric_data_v1_data_proto_rawDescGZIP() []byte {
	file_swanlab_metric_data_v1_data_proto_rawDescOnce.Do(func() {
		file_swanlab_metric_data_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_metric_data_v1_data_proto_rawDesc), len(file_swanlab_metric_data_v1_data_proto_rawDesc)))
	})
	return file_swanlab_metric_data_v1_data_proto_rawDescData
}

var file_swanlab_metric_data_v1_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_swanlab_metric_data_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_swanlab_metric_data_v1_data_proto_goTypes = []any{
	(ColumnType)(0),               // 0: swanlab.metric.data.v1.ColumnType
	(*DataRecord)(nil),            // 1: swanlab.metric.data.v1.DataRecord
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*ScalarValue)(nil),           // 3: swanlab.metric.data.v1.ScalarValue
	(*ImageValue)(nil),            // 4: swanlab.metric.data.v1.ImageValue
	(*AudioValue)(nil),            // 5: swanlab.metric.data.v1.AudioValue
	(*VideoValue)(nil),            // 6: swanlab.metric.data.v1.VideoValue
	(*TextValue)(nil),             // 7: swanlab.metric.data.v1.TextValue
	(*EChartsValue)(nil),          // 8: swanlab.metric.data.v1.EChartsValue
}
var file_swanlab_metric_data_v1_data_proto_depIdxs = []int32{
	0, // 0: swanlab.metric.data.v1.DataRecord.type:type_name -> swanlab.metric.data.v1.ColumnType
	2, // 1: swanlab.metric.data.v1.DataRecord.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: swanlab.metric.data.v1.DataRecord.scalar:type_name -> swanlab.metric.data.v1.ScalarValue
	4, // 3: swanlab.metric.data.v1.DataRecord.images:type_name -> swanlab.metric.data.v1.ImageValue
	5, // 4: swanlab.metric.data.v1.DataRecord.audios:type_name -> swanlab.metric.data.v1.AudioValue
	6, // 5: swanlab.metric.data.v1.DataRecord.videos:type_name -> swanlab.metric.data.v1.VideoValue
	7, // 6: swanlab.metric.data.v1.DataRecord.texts:type_name -> swanlab.metric.data.v1.TextValue
	8, // 7: swanlab.metric.data.v1.DataRecord.echarts:type_name -> swanlab.metric.data.v1.EChartsValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_swanlab_metric_data_v1_data_proto_init() }
func file_swanlab_metric_data_v1_data_proto_init() {
	if File_swanlab_metric_data_v1_data_proto != nil {
		return
	}
	file_swanlab_metric_data_v1_scalar_scalar_proto_init()
	file_swanlab_metric_data_v1_media_image_proto_init()
	file_swanlab_metric_data_v1_media_audio_proto_init()
	file_swanlab_metric_data_v1_media_video_proto_init()
	file_swanlab_metric_data_v1_media_text_proto_init()
	file_swanlab_metric_data_v1_media_echarts_proto_init()
	file_swanlab_metric_data_v1_data_proto_msgTypes[0].OneofWrappers = []any{
		(*DataRecord_Scalar)(nil),
		(*DataRecord_Images)(nil),
		(*DataRecord_Audios)(nil),
		(*DataRecord_Videos)(nil),
		(*DataRecord_Texts)(nil),
		(*DataRecord_Echarts)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_metric_data_v1_data_proto_rawDesc), len(file_swanlab_metric_data_v1_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_metric_data_v1_data_proto_goTypes,
		DependencyIndexes: file_swanlab_metric_data_v1_data_proto_depIdxs,
		EnumInfos:         file_swanlab_metric_data_v1_data_proto_enumTypes,
		MessageInfos:      file_swanlab_metric_data_v1_data_proto_msgTypes,
	}.Build()
	File_swanlab_metric_data_v1_data_proto = out.File
	file_swanlab_metric_data_v1_data_proto_goTypes = nil
	file_swanlab_metric_data_v1_data_proto_depIdxs = nil
}
