# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swanlab/env/v1/env.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swanlab/env/v1/env.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18swanlab/env/v1/env.proto\x12\x0eswanlab.env.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n\x0eMetadataRecord\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"C\n\x12RequirementsRecord\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"<\n\x0b\x43ondaRecord\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB=Z;github.com/swanhubx/swanlab/core/proto/swanlab/env/v1;envv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swanlab.env.v1.env_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/swanhubx/swanlab/core/proto/swanlab/env/v1;envv1'
  _globals['_METADATARECORD']._serialized_start=77
  _globals['_METADATARECORD']._serialized_end=140
  _globals['_REQUIREMENTSRECORD']._serialized_start=142
  _globals['_REQUIREMENTSRECORD']._serialized_end=209
  _globals['_CONDARECORD']._serialized_start=211
  _globals['_CONDARECORD']._serialized_end=271
# @@protoc_insertion_point(module_scope)
