# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swanlab/operation/v1/operation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swanlab/operation/v1/operation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$swanlab/operation/v1/operation.proto\x12\x14swanlab.operation.v1\"K\n\x0c\x46ileProgress\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05total\x18\x02 \x01(\x03\x12\x10\n\x08uploaded\x18\x03 \x01(\x03\x12\x0c\n\x04rate\x18\x04 \x01(\x01\"\x8c\x02\n\x0eOperationStats\x12.\n\x05state\x18\x01 \x01(\x0e\x32\x1f.swanlab.operation.v1.CoreState\x12\x14\n\x0ctotal_number\x18\x02 \x01(\x03\x12\x17\n\x0fuploaded_number\x18\x03 \x01(\x03\x12\x15\n\rtotal_records\x18\x04 \x01(\x03\x12\x18\n\x10uploaded_records\x18\x05 \x01(\x03\x12\x12\n\ntotal_size\x18\x06 \x01(\x03\x12\x15\n\ruploaded_size\x18\x07 \x01(\x03\x12\x0c\n\x04rate\x18\x08 \x01(\x01\x12\x31\n\x05\x66iles\x18\t \x03(\x0b\x32\".swanlab.operation.v1.FileProgress*X\n\tCoreState\x12\x1a\n\x16\x43ORE_STATE_NOT_STARTED\x10\x00\x12\x16\n\x12\x43ORE_STATE_RUNNING\x10\x01\x12\x17\n\x13\x43ORE_STATE_FINISHED\x10\x02\x42IZGgithub.com/swanhubx/swanlab/core/proto/swanlab/operation/v1;operationv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swanlab.operation.v1.operation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGgithub.com/swanhubx/swanlab/core/proto/swanlab/operation/v1;operationv1'
  _globals['_CORESTATE']._serialized_start=410
  _globals['_CORESTATE']._serialized_end=498
  _globals['_FILEPROGRESS']._serialized_start=62
  _globals['_FILEPROGRESS']._serialized_end=137
  _globals['_OPERATIONSTATS']._serialized_start=140
  _globals['_OPERATIONSTATS']._serialized_end=408
# @@protoc_insertion_point(module_scope)
