// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/record/v1/record.proto

package recordv1

import (
	v11 "github.com/swanhubx/swanlab/core/proto/swanlab/metric/column/v1"
	v12 "github.com/swanhubx/swanlab/core/proto/swanlab/metric/data/v1"
	v1 "github.com/swanhubx/swanlab/core/proto/swanlab/run/v1"
	v14 "github.com/swanhubx/swanlab/core/proto/swanlab/save/v1"
	v13 "github.com/swanhubx/swanlab/core/proto/swanlab/terminal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 所有消息的顶层信封。
//
// SwanLab 的运行日志以 append-only 的方式写入磁盘，每条写入均为一个 Record。
// num 字段保证全局单调递增，可用于重放和断点续传。
//
// 消息流示意：
//
//	init()  → StartRecord, MetadataRecord, ConfigRecord
//	log()   → MetricRecord（每个 key 一条）
//	stdout  → LogRecord（每行一条）
//	finish()→ FinishRecord
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 单调递增序号，由Core构建，用于缓冲区去重，约定：
	// 1. StartRecord 的 num 为-1
	// 2. FinishRecord 的 num 为-2
	// 3. config save 的 num 为-3
	// 4. metadata save 的 num 为-4
	// 5. requirements save 的 num 为-5
	// 6. conda save 的 num 为-6
	// 上述记录为全局唯一、去重Record，其余Record 的 num 为 1 开始的递增序号，小于-100的负数范围被用于特殊场景，例如sync时自动构建column record
	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	// Record 生成时间，仅作参考
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to RecordType:
	//
	//	*Record_Start
	//	*Record_Finish
	//	*Record_Column
	//	*Record_Scalar
	//	*Record_Media
	//	*Record_Log
	//	*Record_Save
	RecordType    isRecord_RecordType `protobuf_oneof:"record_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Record) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Record) GetRecordType() isRecord_RecordType {
	if x != nil {
		return x.RecordType
	}
	return nil
}

func (x *Record) GetStart() *v1.StartRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *Record) GetFinish() *v1.FinishRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Finish); ok {
			return x.Finish
		}
	}
	return nil
}

func (x *Record) GetColumn() *v11.ColumnRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Column); ok {
			return x.Column
		}
	}
	return nil
}

func (x *Record) GetScalar() *v12.ScalarRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Scalar); ok {
			return x.Scalar
		}
	}
	return nil
}

func (x *Record) GetMedia() *v12.MediaRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *Record) GetLog() *v13.LogRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *Record) GetSave() *v14.SaveRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Save); ok {
			return x.Save
		}
	}
	return nil
}

type isRecord_RecordType interface {
	isRecord_RecordType()
}

type Record_Start struct {
	// ── Run 生命周期 ──
	Start *v1.StartRecord `protobuf:"bytes,10,opt,name=start,proto3,oneof"`
}

type Record_Finish struct {
	Finish *v1.FinishRecord `protobuf:"bytes,11,opt,name=finish,proto3,oneof"`
}

type Record_Column struct {
	// ── 用户数据 ──
	Column *v11.ColumnRecord `protobuf:"bytes,12,opt,name=column,proto3,oneof"`
}

type Record_Scalar struct {
	Scalar *v12.ScalarRecord `protobuf:"bytes,13,opt,name=scalar,proto3,oneof"`
}

type Record_Media struct {
	Media *v12.MediaRecord `protobuf:"bytes,14,opt,name=media,proto3,oneof"`
}

type Record_Log struct {
	// ── 终端输出 ──
	Log *v13.LogRecord `protobuf:"bytes,16,opt,name=log,proto3,oneof"`
}

type Record_Save struct {
	// ── 文件保存 ──
	Save *v14.SaveRecord `protobuf:"bytes,20,opt,name=save,proto3,oneof"`
}

func (*Record_Start) isRecord_RecordType() {}

func (*Record_Finish) isRecord_RecordType() {}

func (*Record_Column) isRecord_RecordType() {}

func (*Record_Scalar) isRecord_RecordType() {}

func (*Record_Media) isRecord_RecordType() {}

func (*Record_Log) isRecord_RecordType() {}

func (*Record_Save) isRecord_RecordType() {}

var File_swanlab_record_v1_record_proto protoreflect.FileDescriptor

const file_swanlab_record_v1_record_proto_rawDesc = "" +
	"\n" +
	"\x1eswanlab/record/v1/record.proto\x12\x11swanlab.record.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18swanlab/run/v1/run.proto\x1a!swanlab/metric/data/v1/data.proto\x1a%swanlab/metric/column/v1/column.proto\x1a\x1dswanlab/terminal/v1/log.proto\x1a\x1aswanlab/save/v1/save.proto\"\xf6\x03\n" +
	"\x06Record\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\x05start\x18\n" +
	" \x01(\v2\x1b.swanlab.run.v1.StartRecordH\x00R\x05start\x126\n" +
	"\x06finish\x18\v \x01(\v2\x1c.swanlab.run.v1.FinishRecordH\x00R\x06finish\x12@\n" +
	"\x06column\x18\f \x01(\v2&.swanlab.metric.column.v1.ColumnRecordH\x00R\x06column\x12>\n" +
	"\x06scalar\x18\r \x01(\v2$.swanlab.metric.data.v1.ScalarRecordH\x00R\x06scalar\x12;\n" +
	"\x05media\x18\x0e \x01(\v2#.swanlab.metric.data.v1.MediaRecordH\x00R\x05media\x122\n" +
	"\x03log\x18\x10 \x01(\v2\x1e.swanlab.terminal.v1.LogRecordH\x00R\x03log\x121\n" +
	"\x04save\x18\x14 \x01(\v2\x1b.swanlab.save.v1.SaveRecordH\x00R\x04saveB\r\n" +
	"\vrecord_typeBCZAgithub.com/swanhubx/swanlab/core/proto/swanlab/record/v1;recordv1b\x06proto3"

var (
	file_swanlab_record_v1_record_proto_rawDescOnce sync.Once
	file_swanlab_record_v1_record_proto_rawDescData []byte
)

func file_swanlab_record_v1_record_proto_rawDescGZIP() []byte {
	file_swanlab_record_v1_record_proto_rawDescOnce.Do(func() {
		file_swanlab_record_v1_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_record_v1_record_proto_rawDesc), len(file_swanlab_record_v1_record_proto_rawDesc)))
	})
	return file_swanlab_record_v1_record_proto_rawDescData
}

var file_swanlab_record_v1_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_swanlab_record_v1_record_proto_goTypes = []any{
	(*Record)(nil),                // 0: swanlab.record.v1.Record
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*v1.StartRecord)(nil),        // 2: swanlab.run.v1.StartRecord
	(*v1.FinishRecord)(nil),       // 3: swanlab.run.v1.FinishRecord
	(*v11.ColumnRecord)(nil),      // 4: swanlab.metric.column.v1.ColumnRecord
	(*v12.ScalarRecord)(nil),      // 5: swanlab.metric.data.v1.ScalarRecord
	(*v12.MediaRecord)(nil),       // 6: swanlab.metric.data.v1.MediaRecord
	(*v13.LogRecord)(nil),         // 7: swanlab.terminal.v1.LogRecord
	(*v14.SaveRecord)(nil),        // 8: swanlab.save.v1.SaveRecord
}
var file_swanlab_record_v1_record_proto_depIdxs = []int32{
	1, // 0: swanlab.record.v1.Record.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: swanlab.record.v1.Record.start:type_name -> swanlab.run.v1.StartRecord
	3, // 2: swanlab.record.v1.Record.finish:type_name -> swanlab.run.v1.FinishRecord
	4, // 3: swanlab.record.v1.Record.column:type_name -> swanlab.metric.column.v1.ColumnRecord
	5, // 4: swanlab.record.v1.Record.scalar:type_name -> swanlab.metric.data.v1.ScalarRecord
	6, // 5: swanlab.record.v1.Record.media:type_name -> swanlab.metric.data.v1.MediaRecord
	7, // 6: swanlab.record.v1.Record.log:type_name -> swanlab.terminal.v1.LogRecord
	8, // 7: swanlab.record.v1.Record.save:type_name -> swanlab.save.v1.SaveRecord
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_swanlab_record_v1_record_proto_init() }
func file_swanlab_record_v1_record_proto_init() {
	if File_swanlab_record_v1_record_proto != nil {
		return
	}
	file_swanlab_record_v1_record_proto_msgTypes[0].OneofWrappers = []any{
		(*Record_Start)(nil),
		(*Record_Finish)(nil),
		(*Record_Column)(nil),
		(*Record_Scalar)(nil),
		(*Record_Media)(nil),
		(*Record_Log)(nil),
		(*Record_Save)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_record_v1_record_proto_rawDesc), len(file_swanlab_record_v1_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_record_v1_record_proto_goTypes,
		DependencyIndexes: file_swanlab_record_v1_record_proto_depIdxs,
		MessageInfos:      file_swanlab_record_v1_record_proto_msgTypes,
	}.Build()
	File_swanlab_record_v1_record_proto = out.File
	file_swanlab_record_v1_record_proto_goTypes = nil
	file_swanlab_record_v1_record_proto_depIdxs = nil
}
