// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/record/v1/record.proto

package recordv1

import (
	v12 "github.com/swanhubx/swanlab/core/proto/swanlab/config/v1"
	v1 "github.com/swanhubx/swanlab/core/proto/swanlab/metric/column/v1"
	v11 "github.com/swanhubx/swanlab/core/proto/swanlab/metric/data/v1"
	v15 "github.com/swanhubx/swanlab/core/proto/swanlab/run/v1"
	v14 "github.com/swanhubx/swanlab/core/proto/swanlab/save/v1"
	v13 "github.com/swanhubx/swanlab/core/proto/swanlab/system/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*v1.ColumnRecord     `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertColumnsRequest) Reset() {
	*x = UpsertColumnsRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertColumnsRequest) ProtoMessage() {}

func (x *UpsertColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertColumnsRequest.ProtoReflect.Descriptor instead.
func (*UpsertColumnsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertColumnsRequest) GetColumns() []*v1.ColumnRecord {
	if x != nil {
		return x.Columns
	}
	return nil
}

type UpsertScalarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v11.ScalarRecord    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertScalarsRequest) Reset() {
	*x = UpsertScalarsRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertScalarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertScalarsRequest) ProtoMessage() {}

func (x *UpsertScalarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertScalarsRequest.ProtoReflect.Descriptor instead.
func (*UpsertScalarsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertScalarsRequest) GetData() []*v11.ScalarRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpsertMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v11.MediaRecord     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMediaRequest) Reset() {
	*x = UpsertMediaRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMediaRequest) ProtoMessage() {}

func (x *UpsertMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMediaRequest.ProtoReflect.Descriptor instead.
func (*UpsertMediaRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertMediaRequest) GetData() []*v11.MediaRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpsertConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*v12.ConfigRecord    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertConfigsRequest) Reset() {
	*x = UpsertConfigsRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertConfigsRequest) ProtoMessage() {}

func (x *UpsertConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertConfigsRequest.ProtoReflect.Descriptor instead.
func (*UpsertConfigsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertConfigsRequest) GetConfigs() []*v12.ConfigRecord {
	if x != nil {
		return x.Configs
	}
	return nil
}

type UpsertConsolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consoles      []*v13.ConsoleRecord   `protobuf:"bytes,1,rep,name=consoles,proto3" json:"consoles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertConsolesRequest) Reset() {
	*x = UpsertConsolesRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertConsolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertConsolesRequest) ProtoMessage() {}

func (x *UpsertConsolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertConsolesRequest.ProtoReflect.Descriptor instead.
func (*UpsertConsolesRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertConsolesRequest) GetConsoles() []*v13.ConsoleRecord {
	if x != nil {
		return x.Consoles
	}
	return nil
}

type UpsertMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      []*v13.MetadataRecord  `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMetadataRequest) Reset() {
	*x = UpsertMetadataRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMetadataRequest) ProtoMessage() {}

func (x *UpsertMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpsertMetadataRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertMetadataRequest) GetMetadata() []*v13.MetadataRecord {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpsertRequirementsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Requirements  []*v13.RequirementsRecord `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequirementsRequest) Reset() {
	*x = UpsertRequirementsRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequirementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequirementsRequest) ProtoMessage() {}

func (x *UpsertRequirementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequirementsRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequirementsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertRequirementsRequest) GetRequirements() []*v13.RequirementsRecord {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type UpsertCondaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conda         []*v13.CondaRecord     `protobuf:"bytes,1,rep,name=conda,proto3" json:"conda,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCondaRequest) Reset() {
	*x = UpsertCondaRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCondaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCondaRequest) ProtoMessage() {}

func (x *UpsertCondaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCondaRequest.ProtoReflect.Descriptor instead.
func (*UpsertCondaRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertCondaRequest) GetConda() []*v13.CondaRecord {
	if x != nil {
		return x.Conda
	}
	return nil
}

type UpsertSavesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saves         []*v14.SaveRecord      `protobuf:"bytes,1,rep,name=saves,proto3" json:"saves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertSavesRequest) Reset() {
	*x = UpsertSavesRequest{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSavesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSavesRequest) ProtoMessage() {}

func (x *UpsertSavesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSavesRequest.ProtoReflect.Descriptor instead.
func (*UpsertSavesRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertSavesRequest) GetSaves() []*v14.SaveRecord {
	if x != nil {
		return x.Saves
	}
	return nil
}

// 所有消息的顶层信封。
//
// SwanLab 的运行日志以 append-only 的方式写入磁盘，每条写入均为一个 Record。
// num 字段保证全局单调递增，可用于重放和断点续传。
//
// 消息流示意：
//
//	init()  → StartRecord, MetadataRecord, ConfigRecord
//	log()   → MetricRecord（每个 key 一条）
//	stdout  → ConsoleRecord（每行一条）
//	finish()→ FinishRecord
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 单调递增序号，由Core构建，用于缓冲区去重，约定：
	// 1. StartRecord 的 num 为-1
	// 2. FinishRecord 的 num 为-2
	// 3. ConfigRecord 的 num 为-3
	// 4. MetadataRecord 的 num 为-4
	// 5. RequirementsRecord 的 num 为-5
	// 6. CondaRecord 的 num 为-6
	// 上述记录为全局唯一、去重Record，其余Record 的 num 为 1 开始的递增序号
	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	// Record 生成时间，仅作参考
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to RecordType:
	//
	//	*Record_Start
	//	*Record_Finish
	//	*Record_Column
	//	*Record_Scalar
	//	*Record_Media
	//	*Record_Config
	//	*Record_Console
	//	*Record_Metadata
	//	*Record_Requirements
	//	*Record_Conda
	//	*Record_Save
	RecordType    isRecord_RecordType `protobuf_oneof:"record_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_swanlab_record_v1_record_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_record_v1_record_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_swanlab_record_v1_record_proto_rawDescGZIP(), []int{9}
}

func (x *Record) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Record) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Record) GetRecordType() isRecord_RecordType {
	if x != nil {
		return x.RecordType
	}
	return nil
}

func (x *Record) GetStart() *v15.StartRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *Record) GetFinish() *v15.FinishRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Finish); ok {
			return x.Finish
		}
	}
	return nil
}

func (x *Record) GetColumn() *v1.ColumnRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Column); ok {
			return x.Column
		}
	}
	return nil
}

func (x *Record) GetScalar() *v11.ScalarRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Scalar); ok {
			return x.Scalar
		}
	}
	return nil
}

func (x *Record) GetMedia() *v11.MediaRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *Record) GetConfig() *v12.ConfigRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *Record) GetConsole() *v13.ConsoleRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Console); ok {
			return x.Console
		}
	}
	return nil
}

func (x *Record) GetMetadata() *v13.MetadataRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *Record) GetRequirements() *v13.RequirementsRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Requirements); ok {
			return x.Requirements
		}
	}
	return nil
}

func (x *Record) GetConda() *v13.CondaRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Conda); ok {
			return x.Conda
		}
	}
	return nil
}

func (x *Record) GetSave() *v14.SaveRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Save); ok {
			return x.Save
		}
	}
	return nil
}

type isRecord_RecordType interface {
	isRecord_RecordType()
}

type Record_Start struct {
	// ── Run 生命周期 ──
	Start *v15.StartRecord `protobuf:"bytes,10,opt,name=start,proto3,oneof"`
}

type Record_Finish struct {
	Finish *v15.FinishRecord `protobuf:"bytes,11,opt,name=finish,proto3,oneof"`
}

type Record_Column struct {
	// ── 用户数据 ──
	Column *v1.ColumnRecord `protobuf:"bytes,12,opt,name=column,proto3,oneof"`
}

type Record_Scalar struct {
	Scalar *v11.ScalarRecord `protobuf:"bytes,13,opt,name=scalar,proto3,oneof"`
}

type Record_Media struct {
	Media *v11.MediaRecord `protobuf:"bytes,14,opt,name=media,proto3,oneof"`
}

type Record_Config struct {
	Config *v12.ConfigRecord `protobuf:"bytes,15,opt,name=config,proto3,oneof"`
}

type Record_Console struct {
	// ── 终端输出 ──
	Console *v13.ConsoleRecord `protobuf:"bytes,16,opt,name=console,proto3,oneof"`
}

type Record_Metadata struct {
	// ── 主机元数据（一次性，init 时写入）──
	Metadata *v13.MetadataRecord `protobuf:"bytes,17,opt,name=metadata,proto3,oneof"`
}

type Record_Requirements struct {
	Requirements *v13.RequirementsRecord `protobuf:"bytes,18,opt,name=requirements,proto3,oneof"`
}

type Record_Conda struct {
	Conda *v13.CondaRecord `protobuf:"bytes,19,opt,name=conda,proto3,oneof"`
}

type Record_Save struct {
	// ── 文件保存 ──
	Save *v14.SaveRecord `protobuf:"bytes,20,opt,name=save,proto3,oneof"`
}

func (*Record_Start) isRecord_RecordType() {}

func (*Record_Finish) isRecord_RecordType() {}

func (*Record_Column) isRecord_RecordType() {}

func (*Record_Scalar) isRecord_RecordType() {}

func (*Record_Media) isRecord_RecordType() {}

func (*Record_Config) isRecord_RecordType() {}

func (*Record_Console) isRecord_RecordType() {}

func (*Record_Metadata) isRecord_RecordType() {}

func (*Record_Requirements) isRecord_RecordType() {}

func (*Record_Conda) isRecord_RecordType() {}

func (*Record_Save) isRecord_RecordType() {}

var File_swanlab_record_v1_record_proto protoreflect.FileDescriptor

const file_swanlab_record_v1_record_proto_rawDesc = "" +
	"\n" +
	"\x1eswanlab/record/v1/record.proto\x12\x11swanlab.record.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18swanlab/run/v1/run.proto\x1a!swanlab/metric/data/v1/data.proto\x1a%swanlab/metric/column/v1/column.proto\x1a\x1eswanlab/config/v1/config.proto\x1a\x1bswanlab/system/v1/env.proto\x1a\x1fswanlab/system/v1/console.proto\x1a\x1aswanlab/save/v1/save.proto\"X\n" +
	"\x14UpsertColumnsRequest\x12@\n" +
	"\acolumns\x18\x01 \x03(\v2&.swanlab.metric.column.v1.ColumnRecordR\acolumns\"P\n" +
	"\x14UpsertScalarsRequest\x128\n" +
	"\x04data\x18\x01 \x03(\v2$.swanlab.metric.data.v1.ScalarRecordR\x04data\"M\n" +
	"\x12UpsertMediaRequest\x127\n" +
	"\x04data\x18\x01 \x03(\v2#.swanlab.metric.data.v1.MediaRecordR\x04data\"Q\n" +
	"\x14UpsertConfigsRequest\x129\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1f.swanlab.config.v1.ConfigRecordR\aconfigs\"U\n" +
	"\x15UpsertConsolesRequest\x12<\n" +
	"\bconsoles\x18\x01 \x03(\v2 .swanlab.system.v1.ConsoleRecordR\bconsoles\"V\n" +
	"\x15UpsertMetadataRequest\x12=\n" +
	"\bmetadata\x18\x01 \x03(\v2!.swanlab.system.v1.MetadataRecordR\bmetadata\"f\n" +
	"\x19UpsertRequirementsRequest\x12I\n" +
	"\frequirements\x18\x01 \x03(\v2%.swanlab.system.v1.RequirementsRecordR\frequirements\"J\n" +
	"\x12UpsertCondaRequest\x124\n" +
	"\x05conda\x18\x01 \x03(\v2\x1e.swanlab.system.v1.CondaRecordR\x05conda\"G\n" +
	"\x12UpsertSavesRequest\x121\n" +
	"\x05saves\x18\x01 \x03(\v2\x1b.swanlab.save.v1.SaveRecordR\x05saves\"\x81\x06\n" +
	"\x06Record\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\x05start\x18\n" +
	" \x01(\v2\x1b.swanlab.run.v1.StartRecordH\x00R\x05start\x126\n" +
	"\x06finish\x18\v \x01(\v2\x1c.swanlab.run.v1.FinishRecordH\x00R\x06finish\x12@\n" +
	"\x06column\x18\f \x01(\v2&.swanlab.metric.column.v1.ColumnRecordH\x00R\x06column\x12>\n" +
	"\x06scalar\x18\r \x01(\v2$.swanlab.metric.data.v1.ScalarRecordH\x00R\x06scalar\x12;\n" +
	"\x05media\x18\x0e \x01(\v2#.swanlab.metric.data.v1.MediaRecordH\x00R\x05media\x129\n" +
	"\x06config\x18\x0f \x01(\v2\x1f.swanlab.config.v1.ConfigRecordH\x00R\x06config\x12<\n" +
	"\aconsole\x18\x10 \x01(\v2 .swanlab.system.v1.ConsoleRecordH\x00R\aconsole\x12?\n" +
	"\bmetadata\x18\x11 \x01(\v2!.swanlab.system.v1.MetadataRecordH\x00R\bmetadata\x12K\n" +
	"\frequirements\x18\x12 \x01(\v2%.swanlab.system.v1.RequirementsRecordH\x00R\frequirements\x126\n" +
	"\x05conda\x18\x13 \x01(\v2\x1e.swanlab.system.v1.CondaRecordH\x00R\x05conda\x121\n" +
	"\x04save\x18\x14 \x01(\v2\x1b.swanlab.save.v1.SaveRecordH\x00R\x04saveB\r\n" +
	"\vrecord_type2\x94\a\n" +
	"\rRecordService\x12M\n" +
	"\x0fDeliverRunStart\x12\x1b.swanlab.run.v1.StartRecord\x1a\x1d.swanlab.run.v1.StartResponse\x12P\n" +
	"\rUpsertColumns\x12'.swanlab.record.v1.UpsertColumnsRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\rUpsertScalars\x12'.swanlab.record.v1.UpsertScalarsRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vUpsertMedia\x12%.swanlab.record.v1.UpsertMediaRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\rUpsertConfigs\x12'.swanlab.record.v1.UpsertConfigsRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0eUpsertConsoles\x12(.swanlab.record.v1.UpsertConsolesRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x12UpsertRequirements\x12,.swanlab.record.v1.UpsertRequirementsRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vUpsertConda\x12%.swanlab.record.v1.UpsertCondaRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0eUpsertMetadata\x12(.swanlab.record.v1.UpsertMetadataRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x10DeliverRunFinish\x12\x1c.swanlab.run.v1.FinishRecord\x1a\x1e.swanlab.run.v1.FinishResponse\x12L\n" +
	"\vUpsertSaves\x12%.swanlab.record.v1.UpsertSavesRequest\x1a\x16.google.protobuf.EmptyBCZAgithub.com/swanhubx/swanlab/core/proto/swanlab/record/v1;recordv1b\x06proto3"

var (
	file_swanlab_record_v1_record_proto_rawDescOnce sync.Once
	file_swanlab_record_v1_record_proto_rawDescData []byte
)

func file_swanlab_record_v1_record_proto_rawDescGZIP() []byte {
	file_swanlab_record_v1_record_proto_rawDescOnce.Do(func() {
		file_swanlab_record_v1_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_record_v1_record_proto_rawDesc), len(file_swanlab_record_v1_record_proto_rawDesc)))
	})
	return file_swanlab_record_v1_record_proto_rawDescData
}

var file_swanlab_record_v1_record_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_swanlab_record_v1_record_proto_goTypes = []any{
	(*UpsertColumnsRequest)(nil),      // 0: swanlab.record.v1.UpsertColumnsRequest
	(*UpsertScalarsRequest)(nil),      // 1: swanlab.record.v1.UpsertScalarsRequest
	(*UpsertMediaRequest)(nil),        // 2: swanlab.record.v1.UpsertMediaRequest
	(*UpsertConfigsRequest)(nil),      // 3: swanlab.record.v1.UpsertConfigsRequest
	(*UpsertConsolesRequest)(nil),     // 4: swanlab.record.v1.UpsertConsolesRequest
	(*UpsertMetadataRequest)(nil),     // 5: swanlab.record.v1.UpsertMetadataRequest
	(*UpsertRequirementsRequest)(nil), // 6: swanlab.record.v1.UpsertRequirementsRequest
	(*UpsertCondaRequest)(nil),        // 7: swanlab.record.v1.UpsertCondaRequest
	(*UpsertSavesRequest)(nil),        // 8: swanlab.record.v1.UpsertSavesRequest
	(*Record)(nil),                    // 9: swanlab.record.v1.Record
	(*v1.ColumnRecord)(nil),           // 10: swanlab.metric.column.v1.ColumnRecord
	(*v11.ScalarRecord)(nil),          // 11: swanlab.metric.data.v1.ScalarRecord
	(*v11.MediaRecord)(nil),           // 12: swanlab.metric.data.v1.MediaRecord
	(*v12.ConfigRecord)(nil),          // 13: swanlab.config.v1.ConfigRecord
	(*v13.ConsoleRecord)(nil),         // 14: swanlab.system.v1.ConsoleRecord
	(*v13.MetadataRecord)(nil),        // 15: swanlab.system.v1.MetadataRecord
	(*v13.RequirementsRecord)(nil),    // 16: swanlab.system.v1.RequirementsRecord
	(*v13.CondaRecord)(nil),           // 17: swanlab.system.v1.CondaRecord
	(*v14.SaveRecord)(nil),            // 18: swanlab.save.v1.SaveRecord
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
	(*v15.StartRecord)(nil),           // 20: swanlab.run.v1.StartRecord
	(*v15.FinishRecord)(nil),          // 21: swanlab.run.v1.FinishRecord
	(*v15.StartResponse)(nil),         // 22: swanlab.run.v1.StartResponse
	(*emptypb.Empty)(nil),             // 23: google.protobuf.Empty
	(*v15.FinishResponse)(nil),        // 24: swanlab.run.v1.FinishResponse
}
var file_swanlab_record_v1_record_proto_depIdxs = []int32{
	10, // 0: swanlab.record.v1.UpsertColumnsRequest.columns:type_name -> swanlab.metric.column.v1.ColumnRecord
	11, // 1: swanlab.record.v1.UpsertScalarsRequest.data:type_name -> swanlab.metric.data.v1.ScalarRecord
	12, // 2: swanlab.record.v1.UpsertMediaRequest.data:type_name -> swanlab.metric.data.v1.MediaRecord
	13, // 3: swanlab.record.v1.UpsertConfigsRequest.configs:type_name -> swanlab.config.v1.ConfigRecord
	14, // 4: swanlab.record.v1.UpsertConsolesRequest.consoles:type_name -> swanlab.system.v1.ConsoleRecord
	15, // 5: swanlab.record.v1.UpsertMetadataRequest.metadata:type_name -> swanlab.system.v1.MetadataRecord
	16, // 6: swanlab.record.v1.UpsertRequirementsRequest.requirements:type_name -> swanlab.system.v1.RequirementsRecord
	17, // 7: swanlab.record.v1.UpsertCondaRequest.conda:type_name -> swanlab.system.v1.CondaRecord
	18, // 8: swanlab.record.v1.UpsertSavesRequest.saves:type_name -> swanlab.save.v1.SaveRecord
	19, // 9: swanlab.record.v1.Record.timestamp:type_name -> google.protobuf.Timestamp
	20, // 10: swanlab.record.v1.Record.start:type_name -> swanlab.run.v1.StartRecord
	21, // 11: swanlab.record.v1.Record.finish:type_name -> swanlab.run.v1.FinishRecord
	10, // 12: swanlab.record.v1.Record.column:type_name -> swanlab.metric.column.v1.ColumnRecord
	11, // 13: swanlab.record.v1.Record.scalar:type_name -> swanlab.metric.data.v1.ScalarRecord
	12, // 14: swanlab.record.v1.Record.media:type_name -> swanlab.metric.data.v1.MediaRecord
	13, // 15: swanlab.record.v1.Record.config:type_name -> swanlab.config.v1.ConfigRecord
	14, // 16: swanlab.record.v1.Record.console:type_name -> swanlab.system.v1.ConsoleRecord
	15, // 17: swanlab.record.v1.Record.metadata:type_name -> swanlab.system.v1.MetadataRecord
	16, // 18: swanlab.record.v1.Record.requirements:type_name -> swanlab.system.v1.RequirementsRecord
	17, // 19: swanlab.record.v1.Record.conda:type_name -> swanlab.system.v1.CondaRecord
	18, // 20: swanlab.record.v1.Record.save:type_name -> swanlab.save.v1.SaveRecord
	20, // 21: swanlab.record.v1.RecordService.DeliverRunStart:input_type -> swanlab.run.v1.StartRecord
	0,  // 22: swanlab.record.v1.RecordService.UpsertColumns:input_type -> swanlab.record.v1.UpsertColumnsRequest
	1,  // 23: swanlab.record.v1.RecordService.UpsertScalars:input_type -> swanlab.record.v1.UpsertScalarsRequest
	2,  // 24: swanlab.record.v1.RecordService.UpsertMedia:input_type -> swanlab.record.v1.UpsertMediaRequest
	3,  // 25: swanlab.record.v1.RecordService.UpsertConfigs:input_type -> swanlab.record.v1.UpsertConfigsRequest
	4,  // 26: swanlab.record.v1.RecordService.UpsertConsoles:input_type -> swanlab.record.v1.UpsertConsolesRequest
	6,  // 27: swanlab.record.v1.RecordService.UpsertRequirements:input_type -> swanlab.record.v1.UpsertRequirementsRequest
	7,  // 28: swanlab.record.v1.RecordService.UpsertConda:input_type -> swanlab.record.v1.UpsertCondaRequest
	5,  // 29: swanlab.record.v1.RecordService.UpsertMetadata:input_type -> swanlab.record.v1.UpsertMetadataRequest
	21, // 30: swanlab.record.v1.RecordService.DeliverRunFinish:input_type -> swanlab.run.v1.FinishRecord
	8,  // 31: swanlab.record.v1.RecordService.UpsertSaves:input_type -> swanlab.record.v1.UpsertSavesRequest
	22, // 32: swanlab.record.v1.RecordService.DeliverRunStart:output_type -> swanlab.run.v1.StartResponse
	23, // 33: swanlab.record.v1.RecordService.UpsertColumns:output_type -> google.protobuf.Empty
	23, // 34: swanlab.record.v1.RecordService.UpsertScalars:output_type -> google.protobuf.Empty
	23, // 35: swanlab.record.v1.RecordService.UpsertMedia:output_type -> google.protobuf.Empty
	23, // 36: swanlab.record.v1.RecordService.UpsertConfigs:output_type -> google.protobuf.Empty
	23, // 37: swanlab.record.v1.RecordService.UpsertConsoles:output_type -> google.protobuf.Empty
	23, // 38: swanlab.record.v1.RecordService.UpsertRequirements:output_type -> google.protobuf.Empty
	23, // 39: swanlab.record.v1.RecordService.UpsertConda:output_type -> google.protobuf.Empty
	23, // 40: swanlab.record.v1.RecordService.UpsertMetadata:output_type -> google.protobuf.Empty
	24, // 41: swanlab.record.v1.RecordService.DeliverRunFinish:output_type -> swanlab.run.v1.FinishResponse
	23, // 42: swanlab.record.v1.RecordService.UpsertSaves:output_type -> google.protobuf.Empty
	32, // [32:43] is the sub-list for method output_type
	21, // [21:32] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_swanlab_record_v1_record_proto_init() }
func file_swanlab_record_v1_record_proto_init() {
	if File_swanlab_record_v1_record_proto != nil {
		return
	}
	file_swanlab_record_v1_record_proto_msgTypes[9].OneofWrappers = []any{
		(*Record_Start)(nil),
		(*Record_Finish)(nil),
		(*Record_Column)(nil),
		(*Record_Scalar)(nil),
		(*Record_Media)(nil),
		(*Record_Config)(nil),
		(*Record_Console)(nil),
		(*Record_Metadata)(nil),
		(*Record_Requirements)(nil),
		(*Record_Conda)(nil),
		(*Record_Save)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_record_v1_record_proto_rawDesc), len(file_swanlab_record_v1_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swanlab_record_v1_record_proto_goTypes,
		DependencyIndexes: file_swanlab_record_v1_record_proto_depIdxs,
		MessageInfos:      file_swanlab_record_v1_record_proto_msgTypes,
	}.Build()
	File_swanlab_record_v1_record_proto = out.File
	file_swanlab_record_v1_record_proto_goTypes = nil
	file_swanlab_record_v1_record_proto_depIdxs = nil
}
