# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from swanlab.proto.core.collector.v1 import collector_service_pb2 as swanlab_dot_proto_dot_core_dot_collector_dot_v1_dot_collector__service__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in swanlab/proto/core/collector/v1/collector_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectorStub(object):
    """Collector is an RPC service responsible for aggregating and reporting data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.unary_unary(
                '/swanlab.proto.core.collector.v1.Collector/Upload',
                request_serializer=swanlab_dot_proto_dot_core_dot_collector_dot_v1_dot_collector__service__pb2.CollectorUploadRequest.SerializeToString,
                response_deserializer=swanlab_dot_proto_dot_core_dot_collector_dot_v1_dot_collector__service__pb2.CollectorUploadResponse.FromString,
                _registered_method=True)


class CollectorServicer(object):
    """Collector is an RPC service responsible for aggregating and reporting data
    """

    def Upload(self, request, context):
        """Upload allows clients to send data to the collector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.unary_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=swanlab_dot_proto_dot_core_dot_collector_dot_v1_dot_collector__service__pb2.CollectorUploadRequest.FromString,
                    response_serializer=swanlab_dot_proto_dot_core_dot_collector_dot_v1_dot_collector__service__pb2.CollectorUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swanlab.proto.core.collector.v1.Collector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swanlab.proto.core.collector.v1.Collector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Collector(object):
    """Collector is an RPC service responsible for aggregating and reporting data
    """

    @staticmethod
    def Upload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swanlab.proto.core.collector.v1.Collector/Upload',
            swanlab_dot_proto_dot_core_dot_collector_dot_v1_dot_collector__service__pb2.CollectorUploadRequest.SerializeToString,
            swanlab_dot_proto_dot_core_dot_collector_dot_v1_dot_collector__service__pb2.CollectorUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
