# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swanlab/settings/probe/v1/probe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swanlab/settings/probe/v1/probe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%swanlab/settings/probe/v1/probe.proto\x12\x19swanlab.settings.probe.v1\"\x0f\n\rProbeSettingsBRZPgithub.com/swanhubx/swanlab/core/proto/swanlab/settings/probe/v1;settingsprobev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swanlab.settings.probe.v1.probe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/swanhubx/swanlab/core/proto/swanlab/settings/probe/v1;settingsprobev1'
  _globals['_PROBESETTINGS']._serialized_start=68
  _globals['_PROBESETTINGS']._serialized_end=83
# @@protoc_insertion_point(module_scope)
