// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/grpc/core/v1/core.proto

package corev1

import (
	v14 "github.com/swanhubx/swanlab/core/proto/swanlab/config/v1"
	v16 "github.com/swanhubx/swanlab/core/proto/swanlab/env/v1"
	v12 "github.com/swanhubx/swanlab/core/proto/swanlab/metric/column/v1"
	v13 "github.com/swanhubx/swanlab/core/proto/swanlab/metric/data/v1"
	v11 "github.com/swanhubx/swanlab/core/proto/swanlab/run/v1"
	v17 "github.com/swanhubx/swanlab/core/proto/swanlab/save/v1"
	v1 "github.com/swanhubx/swanlab/core/proto/swanlab/settings/core/v1"
	v15 "github.com/swanhubx/swanlab/core/proto/swanlab/terminal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliverRunStart 请求，生命周期函数，运行正式开始
type DeliverRunStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreSettings  *v1.CoreSettings       `protobuf:"bytes,1,opt,name=core_settings,json=coreSettings,proto3" json:"core_settings,omitempty"` // Run 服务配置
	StartRecord   *v11.StartRecord       `protobuf:"bytes,2,opt,name=start_record,json=startRecord,proto3" json:"start_record,omitempty"`    // Run 创建记录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRunStartRequest) Reset() {
	*x = DeliverRunStartRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRunStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRunStartRequest) ProtoMessage() {}

func (x *DeliverRunStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRunStartRequest.ProtoReflect.Descriptor instead.
func (*DeliverRunStartRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverRunStartRequest) GetCoreSettings() *v1.CoreSettings {
	if x != nil {
		return x.CoreSettings
	}
	return nil
}

func (x *DeliverRunStartRequest) GetStartRecord() *v11.StartRecord {
	if x != nil {
		return x.StartRecord
	}
	return nil
}

// DeliverRunStart 响应
type DeliverRunStartResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                             // 请求是否成功
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                              // 请求失败的响应
	Run              *v11.StartRecord       `protobuf:"bytes,3,opt,name=run,proto3" json:"run,omitempty"`                                                      // 最终创建的 Run 记录
	Path             string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                                    // 对应的实验路径，格式为 /:username/:project_name/:slug(run_id)
	Name             string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                                                    // 对应的实验名称
	GlobalStep       int64                  `protobuf:"varint,6,opt,name=global_step,json=globalStep,proto3" json:"global_step,omitempty"`                     // 起始全局步数
	GlobalSystemStep int64                  `protobuf:"varint,7,opt,name=global_system_step,json=globalSystemStep,proto3" json:"global_system_step,omitempty"` // 起始全局系统步数
	NewExperiment    bool                   `protobuf:"varint,8,opt,name=new_experiment,json=newExperiment,proto3" json:"new_experiment,omitempty"`            // 是否是新实验
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeliverRunStartResponse) Reset() {
	*x = DeliverRunStartResponse{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRunStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRunStartResponse) ProtoMessage() {}

func (x *DeliverRunStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRunStartResponse.ProtoReflect.Descriptor instead.
func (*DeliverRunStartResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverRunStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliverRunStartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeliverRunStartResponse) GetRun() *v11.StartRecord {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *DeliverRunStartResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeliverRunStartResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeliverRunStartResponse) GetGlobalStep() int64 {
	if x != nil {
		return x.GlobalStep
	}
	return 0
}

func (x *DeliverRunStartResponse) GetGlobalSystemStep() int64 {
	if x != nil {
		return x.GlobalSystemStep
	}
	return 0
}

func (x *DeliverRunStartResponse) GetNewExperiment() bool {
	if x != nil {
		return x.NewExperiment
	}
	return false
}

// UpsertColumns 请求，异步插入一批列定义
type UpsertColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*v12.ColumnRecord    `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"` // 列定义列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertColumnsRequest) Reset() {
	*x = UpsertColumnsRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertColumnsRequest) ProtoMessage() {}

func (x *UpsertColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertColumnsRequest.ProtoReflect.Descriptor instead.
func (*UpsertColumnsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertColumnsRequest) GetColumns() []*v12.ColumnRecord {
	if x != nil {
		return x.Columns
	}
	return nil
}

// UpsertScalars 请求，异步插入一批标量数据
type UpsertScalarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v13.ScalarRecord    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 标量记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertScalarsRequest) Reset() {
	*x = UpsertScalarsRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertScalarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertScalarsRequest) ProtoMessage() {}

func (x *UpsertScalarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertScalarsRequest.ProtoReflect.Descriptor instead.
func (*UpsertScalarsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertScalarsRequest) GetData() []*v13.ScalarRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpsertMedia 请求，异步插入一批媒体数据
type UpsertMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v13.MediaRecord     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 媒体记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMediaRequest) Reset() {
	*x = UpsertMediaRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMediaRequest) ProtoMessage() {}

func (x *UpsertMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMediaRequest.ProtoReflect.Descriptor instead.
func (*UpsertMediaRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertMediaRequest) GetData() []*v13.MediaRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpsertConfigs 请求，异步插入一批配置更新
type UpsertConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*v14.ConfigRecord    `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"` // 配置记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertConfigsRequest) Reset() {
	*x = UpsertConfigsRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertConfigsRequest) ProtoMessage() {}

func (x *UpsertConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertConfigsRequest.ProtoReflect.Descriptor instead.
func (*UpsertConfigsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *UpsertConfigsRequest) GetConfigs() []*v14.ConfigRecord {
	if x != nil {
		return x.Configs
	}
	return nil
}

// UpsertLogs 请求，异步插入一批终端输出
type UpsertLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*v15.LogRecord       `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"` // 终端日志记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertLogsRequest) Reset() {
	*x = UpsertLogsRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertLogsRequest) ProtoMessage() {}

func (x *UpsertLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertLogsRequest.ProtoReflect.Descriptor instead.
func (*UpsertLogsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertLogsRequest) GetLogs() []*v15.LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

// UpsertMetadata 请求，异步插入一批主机元数据
type UpsertMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      []*v16.MetadataRecord  `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty"` // 元数据记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMetadataRequest) Reset() {
	*x = UpsertMetadataRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMetadataRequest) ProtoMessage() {}

func (x *UpsertMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpsertMetadataRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertMetadataRequest) GetMetadata() []*v16.MetadataRecord {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpsertRequirements 请求，异步插入一批 Python 依赖
type UpsertRequirementsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Requirements  []*v16.RequirementsRecord `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"` // 依赖记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequirementsRequest) Reset() {
	*x = UpsertRequirementsRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequirementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequirementsRequest) ProtoMessage() {}

func (x *UpsertRequirementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequirementsRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequirementsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertRequirementsRequest) GetRequirements() []*v16.RequirementsRecord {
	if x != nil {
		return x.Requirements
	}
	return nil
}

// UpsertConda 请求，异步插入一批 Conda 环境信息
type UpsertCondaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conda         []*v16.CondaRecord     `protobuf:"bytes,1,rep,name=conda,proto3" json:"conda,omitempty"` // Conda 记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCondaRequest) Reset() {
	*x = UpsertCondaRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCondaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCondaRequest) ProtoMessage() {}

func (x *UpsertCondaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCondaRequest.ProtoReflect.Descriptor instead.
func (*UpsertCondaRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertCondaRequest) GetConda() []*v16.CondaRecord {
	if x != nil {
		return x.Conda
	}
	return nil
}

// UpsertSaves 请求，异步插入一批文件保存记录
type UpsertSavesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saves         []*v17.SaveRecord      `protobuf:"bytes,1,rep,name=saves,proto3" json:"saves,omitempty"` // 保存记录列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertSavesRequest) Reset() {
	*x = UpsertSavesRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSavesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSavesRequest) ProtoMessage() {}

func (x *UpsertSavesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSavesRequest.ProtoReflect.Descriptor instead.
func (*UpsertSavesRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertSavesRequest) GetSaves() []*v17.SaveRecord {
	if x != nil {
		return x.Saves
	}
	return nil
}

// DeliverRunFinish 请求，生命周期函数，运行结束
type DeliverRunFinishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinishRecord  *v11.FinishRecord      `protobuf:"bytes,1,opt,name=finish_record,json=finishRecord,proto3" json:"finish_record,omitempty"` // Run 结束记录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRunFinishRequest) Reset() {
	*x = DeliverRunFinishRequest{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRunFinishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRunFinishRequest) ProtoMessage() {}

func (x *DeliverRunFinishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRunFinishRequest.ProtoReflect.Descriptor instead.
func (*DeliverRunFinishRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *DeliverRunFinishRequest) GetFinishRecord() *v11.FinishRecord {
	if x != nil {
		return x.FinishRecord
	}
	return nil
}

// DeliverRunFinish 响应
type DeliverRunFinishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 请求是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 请求失败的响应
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRunFinishResponse) Reset() {
	*x = DeliverRunFinishResponse{}
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRunFinishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRunFinishResponse) ProtoMessage() {}

func (x *DeliverRunFinishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v1_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRunFinishResponse.ProtoReflect.Descriptor instead.
func (*DeliverRunFinishResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v1_core_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverRunFinishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliverRunFinishResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_swanlab_grpc_core_v1_core_proto protoreflect.FileDescriptor

const file_swanlab_grpc_core_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x1fswanlab/grpc/core/v1/core.proto\x12\x14swanlab.grpc.core.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18swanlab/run/v1/run.proto\x1a!swanlab/metric/data/v1/data.proto\x1a%swanlab/metric/column/v1/column.proto\x1a\x1eswanlab/config/v1/config.proto\x1a\x18swanlab/env/v1/env.proto\x1a\x1dswanlab/terminal/v1/log.proto\x1a\x1aswanlab/save/v1/save.proto\x1a#swanlab/settings/core/v1/core.proto\"\xa5\x01\n" +
	"\x16DeliverRunStartRequest\x12K\n" +
	"\rcore_settings\x18\x01 \x01(\v2&.swanlab.settings.core.v1.CoreSettingsR\fcoreSettings\x12>\n" +
	"\fstart_record\x18\x02 \x01(\v2\x1b.swanlab.run.v1.StartRecordR\vstartRecord\"\x9a\x02\n" +
	"\x17DeliverRunStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x03run\x18\x03 \x01(\v2\x1b.swanlab.run.v1.StartRecordR\x03run\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1f\n" +
	"\vglobal_step\x18\x06 \x01(\x03R\n" +
	"globalStep\x12,\n" +
	"\x12global_system_step\x18\a \x01(\x03R\x10globalSystemStep\x12%\n" +
	"\x0enew_experiment\x18\b \x01(\bR\rnewExperiment\"X\n" +
	"\x14UpsertColumnsRequest\x12@\n" +
	"\acolumns\x18\x01 \x03(\v2&.swanlab.metric.column.v1.ColumnRecordR\acolumns\"P\n" +
	"\x14UpsertScalarsRequest\x128\n" +
	"\x04data\x18\x01 \x03(\v2$.swanlab.metric.data.v1.ScalarRecordR\x04data\"M\n" +
	"\x12UpsertMediaRequest\x127\n" +
	"\x04data\x18\x01 \x03(\v2#.swanlab.metric.data.v1.MediaRecordR\x04data\"Q\n" +
	"\x14UpsertConfigsRequest\x129\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1f.swanlab.config.v1.ConfigRecordR\aconfigs\"G\n" +
	"\x11UpsertLogsRequest\x122\n" +
	"\x04logs\x18\x01 \x03(\v2\x1e.swanlab.terminal.v1.LogRecordR\x04logs\"S\n" +
	"\x15UpsertMetadataRequest\x12:\n" +
	"\bmetadata\x18\x01 \x03(\v2\x1e.swanlab.env.v1.MetadataRecordR\bmetadata\"c\n" +
	"\x19UpsertRequirementsRequest\x12F\n" +
	"\frequirements\x18\x01 \x03(\v2\".swanlab.env.v1.RequirementsRecordR\frequirements\"G\n" +
	"\x12UpsertCondaRequest\x121\n" +
	"\x05conda\x18\x01 \x03(\v2\x1b.swanlab.env.v1.CondaRecordR\x05conda\"G\n" +
	"\x12UpsertSavesRequest\x121\n" +
	"\x05saves\x18\x01 \x03(\v2\x1b.swanlab.save.v1.SaveRecordR\x05saves\"\\\n" +
	"\x17DeliverRunFinishRequest\x12A\n" +
	"\rfinish_record\x18\x01 \x01(\v2\x1c.swanlab.run.v1.FinishRecordR\ffinishRecord\"N\n" +
	"\x18DeliverRunFinishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe7\a\n" +
	"\vCoreService\x12n\n" +
	"\x0fDeliverRunStart\x12,.swanlab.grpc.core.v1.DeliverRunStartRequest\x1a-.swanlab.grpc.core.v1.DeliverRunStartResponse\x12S\n" +
	"\rUpsertColumns\x12*.swanlab.grpc.core.v1.UpsertColumnsRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\rUpsertScalars\x12*.swanlab.grpc.core.v1.UpsertScalarsRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\vUpsertMedia\x12(.swanlab.grpc.core.v1.UpsertMediaRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\rUpsertConfigs\x12*.swanlab.grpc.core.v1.UpsertConfigsRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\n" +
	"UpsertLogs\x12'.swanlab.grpc.core.v1.UpsertLogsRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x12UpsertRequirements\x12/.swanlab.grpc.core.v1.UpsertRequirementsRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\vUpsertConda\x12(.swanlab.grpc.core.v1.UpsertCondaRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x0eUpsertMetadata\x12+.swanlab.grpc.core.v1.UpsertMetadataRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\vUpsertSaves\x12(.swanlab.grpc.core.v1.UpsertSavesRequest\x1a\x16.google.protobuf.Empty\x12q\n" +
	"\x10DeliverRunFinish\x12-.swanlab.grpc.core.v1.DeliverRunFinishRequest\x1a..swanlab.grpc.core.v1.DeliverRunFinishResponseBDZBgithub.com/swanhubx/swanlab/core/proto/swanlab/grpc/core/v1;corev1b\x06proto3"

var (
	file_swanlab_grpc_core_v1_core_proto_rawDescOnce sync.Once
	file_swanlab_grpc_core_v1_core_proto_rawDescData []byte
)

func file_swanlab_grpc_core_v1_core_proto_rawDescGZIP() []byte {
	file_swanlab_grpc_core_v1_core_proto_rawDescOnce.Do(func() {
		file_swanlab_grpc_core_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_grpc_core_v1_core_proto_rawDesc), len(file_swanlab_grpc_core_v1_core_proto_rawDesc)))
	})
	return file_swanlab_grpc_core_v1_core_proto_rawDescData
}

var file_swanlab_grpc_core_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_swanlab_grpc_core_v1_core_proto_goTypes = []any{
	(*DeliverRunStartRequest)(nil),    // 0: swanlab.grpc.core.v1.DeliverRunStartRequest
	(*DeliverRunStartResponse)(nil),   // 1: swanlab.grpc.core.v1.DeliverRunStartResponse
	(*UpsertColumnsRequest)(nil),      // 2: swanlab.grpc.core.v1.UpsertColumnsRequest
	(*UpsertScalarsRequest)(nil),      // 3: swanlab.grpc.core.v1.UpsertScalarsRequest
	(*UpsertMediaRequest)(nil),        // 4: swanlab.grpc.core.v1.UpsertMediaRequest
	(*UpsertConfigsRequest)(nil),      // 5: swanlab.grpc.core.v1.UpsertConfigsRequest
	(*UpsertLogsRequest)(nil),         // 6: swanlab.grpc.core.v1.UpsertLogsRequest
	(*UpsertMetadataRequest)(nil),     // 7: swanlab.grpc.core.v1.UpsertMetadataRequest
	(*UpsertRequirementsRequest)(nil), // 8: swanlab.grpc.core.v1.UpsertRequirementsRequest
	(*UpsertCondaRequest)(nil),        // 9: swanlab.grpc.core.v1.UpsertCondaRequest
	(*UpsertSavesRequest)(nil),        // 10: swanlab.grpc.core.v1.UpsertSavesRequest
	(*DeliverRunFinishRequest)(nil),   // 11: swanlab.grpc.core.v1.DeliverRunFinishRequest
	(*DeliverRunFinishResponse)(nil),  // 12: swanlab.grpc.core.v1.DeliverRunFinishResponse
	(*v1.CoreSettings)(nil),           // 13: swanlab.settings.core.v1.CoreSettings
	(*v11.StartRecord)(nil),           // 14: swanlab.run.v1.StartRecord
	(*v12.ColumnRecord)(nil),          // 15: swanlab.metric.column.v1.ColumnRecord
	(*v13.ScalarRecord)(nil),          // 16: swanlab.metric.data.v1.ScalarRecord
	(*v13.MediaRecord)(nil),           // 17: swanlab.metric.data.v1.MediaRecord
	(*v14.ConfigRecord)(nil),          // 18: swanlab.config.v1.ConfigRecord
	(*v15.LogRecord)(nil),             // 19: swanlab.terminal.v1.LogRecord
	(*v16.MetadataRecord)(nil),        // 20: swanlab.env.v1.MetadataRecord
	(*v16.RequirementsRecord)(nil),    // 21: swanlab.env.v1.RequirementsRecord
	(*v16.CondaRecord)(nil),           // 22: swanlab.env.v1.CondaRecord
	(*v17.SaveRecord)(nil),            // 23: swanlab.save.v1.SaveRecord
	(*v11.FinishRecord)(nil),          // 24: swanlab.run.v1.FinishRecord
	(*emptypb.Empty)(nil),             // 25: google.protobuf.Empty
}
var file_swanlab_grpc_core_v1_core_proto_depIdxs = []int32{
	13, // 0: swanlab.grpc.core.v1.DeliverRunStartRequest.core_settings:type_name -> swanlab.settings.core.v1.CoreSettings
	14, // 1: swanlab.grpc.core.v1.DeliverRunStartRequest.start_record:type_name -> swanlab.run.v1.StartRecord
	14, // 2: swanlab.grpc.core.v1.DeliverRunStartResponse.run:type_name -> swanlab.run.v1.StartRecord
	15, // 3: swanlab.grpc.core.v1.UpsertColumnsRequest.columns:type_name -> swanlab.metric.column.v1.ColumnRecord
	16, // 4: swanlab.grpc.core.v1.UpsertScalarsRequest.data:type_name -> swanlab.metric.data.v1.ScalarRecord
	17, // 5: swanlab.grpc.core.v1.UpsertMediaRequest.data:type_name -> swanlab.metric.data.v1.MediaRecord
	18, // 6: swanlab.grpc.core.v1.UpsertConfigsRequest.configs:type_name -> swanlab.config.v1.ConfigRecord
	19, // 7: swanlab.grpc.core.v1.UpsertLogsRequest.logs:type_name -> swanlab.terminal.v1.LogRecord
	20, // 8: swanlab.grpc.core.v1.UpsertMetadataRequest.metadata:type_name -> swanlab.env.v1.MetadataRecord
	21, // 9: swanlab.grpc.core.v1.UpsertRequirementsRequest.requirements:type_name -> swanlab.env.v1.RequirementsRecord
	22, // 10: swanlab.grpc.core.v1.UpsertCondaRequest.conda:type_name -> swanlab.env.v1.CondaRecord
	23, // 11: swanlab.grpc.core.v1.UpsertSavesRequest.saves:type_name -> swanlab.save.v1.SaveRecord
	24, // 12: swanlab.grpc.core.v1.DeliverRunFinishRequest.finish_record:type_name -> swanlab.run.v1.FinishRecord
	0,  // 13: swanlab.grpc.core.v1.CoreService.DeliverRunStart:input_type -> swanlab.grpc.core.v1.DeliverRunStartRequest
	2,  // 14: swanlab.grpc.core.v1.CoreService.UpsertColumns:input_type -> swanlab.grpc.core.v1.UpsertColumnsRequest
	3,  // 15: swanlab.grpc.core.v1.CoreService.UpsertScalars:input_type -> swanlab.grpc.core.v1.UpsertScalarsRequest
	4,  // 16: swanlab.grpc.core.v1.CoreService.UpsertMedia:input_type -> swanlab.grpc.core.v1.UpsertMediaRequest
	5,  // 17: swanlab.grpc.core.v1.CoreService.UpsertConfigs:input_type -> swanlab.grpc.core.v1.UpsertConfigsRequest
	6,  // 18: swanlab.grpc.core.v1.CoreService.UpsertLogs:input_type -> swanlab.grpc.core.v1.UpsertLogsRequest
	8,  // 19: swanlab.grpc.core.v1.CoreService.UpsertRequirements:input_type -> swanlab.grpc.core.v1.UpsertRequirementsRequest
	9,  // 20: swanlab.grpc.core.v1.CoreService.UpsertConda:input_type -> swanlab.grpc.core.v1.UpsertCondaRequest
	7,  // 21: swanlab.grpc.core.v1.CoreService.UpsertMetadata:input_type -> swanlab.grpc.core.v1.UpsertMetadataRequest
	10, // 22: swanlab.grpc.core.v1.CoreService.UpsertSaves:input_type -> swanlab.grpc.core.v1.UpsertSavesRequest
	11, // 23: swanlab.grpc.core.v1.CoreService.DeliverRunFinish:input_type -> swanlab.grpc.core.v1.DeliverRunFinishRequest
	1,  // 24: swanlab.grpc.core.v1.CoreService.DeliverRunStart:output_type -> swanlab.grpc.core.v1.DeliverRunStartResponse
	25, // 25: swanlab.grpc.core.v1.CoreService.UpsertColumns:output_type -> google.protobuf.Empty
	25, // 26: swanlab.grpc.core.v1.CoreService.UpsertScalars:output_type -> google.protobuf.Empty
	25, // 27: swanlab.grpc.core.v1.CoreService.UpsertMedia:output_type -> google.protobuf.Empty
	25, // 28: swanlab.grpc.core.v1.CoreService.UpsertConfigs:output_type -> google.protobuf.Empty
	25, // 29: swanlab.grpc.core.v1.CoreService.UpsertLogs:output_type -> google.protobuf.Empty
	25, // 30: swanlab.grpc.core.v1.CoreService.UpsertRequirements:output_type -> google.protobuf.Empty
	25, // 31: swanlab.grpc.core.v1.CoreService.UpsertConda:output_type -> google.protobuf.Empty
	25, // 32: swanlab.grpc.core.v1.CoreService.UpsertMetadata:output_type -> google.protobuf.Empty
	25, // 33: swanlab.grpc.core.v1.CoreService.UpsertSaves:output_type -> google.protobuf.Empty
	12, // 34: swanlab.grpc.core.v1.CoreService.DeliverRunFinish:output_type -> swanlab.grpc.core.v1.DeliverRunFinishResponse
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_swanlab_grpc_core_v1_core_proto_init() }
func file_swanlab_grpc_core_v1_core_proto_init() {
	if File_swanlab_grpc_core_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_grpc_core_v1_core_proto_rawDesc), len(file_swanlab_grpc_core_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swanlab_grpc_core_v1_core_proto_goTypes,
		DependencyIndexes: file_swanlab_grpc_core_v1_core_proto_depIdxs,
		MessageInfos:      file_swanlab_grpc_core_v1_core_proto_msgTypes,
	}.Build()
	File_swanlab_grpc_core_v1_core_proto = out.File
	file_swanlab_grpc_core_v1_core_proto_goTypes = nil
	file_swanlab_grpc_core_v1_core_proto_depIdxs = nil
}
