// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/metric/data/v1/media/text.proto

package datav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 一个 key 在某个 step 下记录的全部文本（1..N 条）。
type TextValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TextItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextValue) Reset() {
	*x = TextValue{}
	mi := &file_swanlab_metric_data_v1_media_text_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextValue) ProtoMessage() {}

func (x *TextValue) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_metric_data_v1_media_text_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextValue.ProtoReflect.Descriptor instead.
func (*TextValue) Descriptor() ([]byte, []int) {
	return file_swanlab_metric_data_v1_media_text_proto_rawDescGZIP(), []int{0}
}

func (x *TextValue) GetItems() []*TextItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单条文本内容。
type TextItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件名，如 "log_10_b3f4.txt"
	Filename      string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Sha256        string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Caption       string `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextItem) Reset() {
	*x = TextItem{}
	mi := &file_swanlab_metric_data_v1_media_text_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextItem) ProtoMessage() {}

func (x *TextItem) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_metric_data_v1_media_text_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextItem.ProtoReflect.Descriptor instead.
func (*TextItem) Descriptor() ([]byte, []int) {
	return file_swanlab_metric_data_v1_media_text_proto_rawDescGZIP(), []int{1}
}

func (x *TextItem) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TextItem) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *TextItem) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

var File_swanlab_metric_data_v1_media_text_proto protoreflect.FileDescriptor

const file_swanlab_metric_data_v1_media_text_proto_rawDesc = "" +
	"\n" +
	"'swanlab/metric/data/v1/media/text.proto\x12\x16swanlab.metric.data.v1\"C\n" +
	"\tTextValue\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .swanlab.metric.data.v1.TextItemR\x05items\"X\n" +
	"\bTextItem\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaptionBFZDgithub.com/swanhubx/swanlab/core/proto/swanlab/metric/data/v1;datav1b\x06proto3"

var (
	file_swanlab_metric_data_v1_media_text_proto_rawDescOnce sync.Once
	file_swanlab_metric_data_v1_media_text_proto_rawDescData []byte
)

func file_swanlab_metric_data_v1_media_text_proto_rawDescGZIP() []byte {
	file_swanlab_metric_data_v1_media_text_proto_rawDescOnce.Do(func() {
		file_swanlab_metric_data_v1_media_text_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_metric_data_v1_media_text_proto_rawDesc), len(file_swanlab_metric_data_v1_media_text_proto_rawDesc)))
	})
	return file_swanlab_metric_data_v1_media_text_proto_rawDescData
}

var file_swanlab_metric_data_v1_media_text_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_swanlab_metric_data_v1_media_text_proto_goTypes = []any{
	(*TextValue)(nil), // 0: swanlab.metric.data.v1.TextValue
	(*TextItem)(nil),  // 1: swanlab.metric.data.v1.TextItem
}
var file_swanlab_metric_data_v1_media_text_proto_depIdxs = []int32{
	1, // 0: swanlab.metric.data.v1.TextValue.items:type_name -> swanlab.metric.data.v1.TextItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_swanlab_metric_data_v1_media_text_proto_init() }
func file_swanlab_metric_data_v1_media_text_proto_init() {
	if File_swanlab_metric_data_v1_media_text_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_metric_data_v1_media_text_proto_rawDesc), len(file_swanlab_metric_data_v1_media_text_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_metric_data_v1_media_text_proto_goTypes,
		DependencyIndexes: file_swanlab_metric_data_v1_media_text_proto_depIdxs,
		MessageInfos:      file_swanlab_metric_data_v1_media_text_proto_msgTypes,
	}.Build()
	File_swanlab_metric_data_v1_media_text_proto = out.File
	file_swanlab_metric_data_v1_media_text_proto_goTypes = nil
	file_swanlab_metric_data_v1_media_text_proto_depIdxs = nil
}
