// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/system/v1/env.proto

package systemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 运行开始时采集一次的主机与环境元数据引用（swanlab-metadata.json）。
// 由于不同机器的硬件和软件环境差异极大，难以保证强类型安全。
// 路径引用约定为 "files/swanlab-metadata.json"，使用json解析。
type MetadataRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRecord) Reset() {
	*x = MetadataRecord{}
	mi := &file_swanlab_system_v1_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRecord) ProtoMessage() {}

func (x *MetadataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_system_v1_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRecord.ProtoReflect.Descriptor instead.
func (*MetadataRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_system_v1_env_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 运行开始时采集的 Python 包依赖引用（requirements.txt）。
// 路径引用约定为 "files/requirements.txt"，使用txt解析。
type RequirementsRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequirementsRecord) Reset() {
	*x = RequirementsRecord{}
	mi := &file_swanlab_system_v1_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequirementsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequirementsRecord) ProtoMessage() {}

func (x *RequirementsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_system_v1_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequirementsRecord.ProtoReflect.Descriptor instead.
func (*RequirementsRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_system_v1_env_proto_rawDescGZIP(), []int{1}
}

func (x *RequirementsRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 运行开始时采集的 Conda 环境引用（conda.yml）。
// 路径引用约定为 "files/conda.yml"，使用yaml解析。
type CondaRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CondaRecord) Reset() {
	*x = CondaRecord{}
	mi := &file_swanlab_system_v1_env_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CondaRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CondaRecord) ProtoMessage() {}

func (x *CondaRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_system_v1_env_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CondaRecord.ProtoReflect.Descriptor instead.
func (*CondaRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_system_v1_env_proto_rawDescGZIP(), []int{2}
}

func (x *CondaRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_swanlab_system_v1_env_proto protoreflect.FileDescriptor

const file_swanlab_system_v1_env_proto_rawDesc = "" +
	"\n" +
	"\x1bswanlab/system/v1/env.proto\x12\x11swanlab.system.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x0eMetadataRecord\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"N\n" +
	"\x12RequirementsRecord\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"G\n" +
	"\vCondaRecord\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampBCZAgithub.com/swanhubx/swanlab/core/proto/swanlab/system/v1;systemv1b\x06proto3"

var (
	file_swanlab_system_v1_env_proto_rawDescOnce sync.Once
	file_swanlab_system_v1_env_proto_rawDescData []byte
)

func file_swanlab_system_v1_env_proto_rawDescGZIP() []byte {
	file_swanlab_system_v1_env_proto_rawDescOnce.Do(func() {
		file_swanlab_system_v1_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_system_v1_env_proto_rawDesc), len(file_swanlab_system_v1_env_proto_rawDesc)))
	})
	return file_swanlab_system_v1_env_proto_rawDescData
}

var file_swanlab_system_v1_env_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_swanlab_system_v1_env_proto_goTypes = []any{
	(*MetadataRecord)(nil),        // 0: swanlab.system.v1.MetadataRecord
	(*RequirementsRecord)(nil),    // 1: swanlab.system.v1.RequirementsRecord
	(*CondaRecord)(nil),           // 2: swanlab.system.v1.CondaRecord
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_swanlab_system_v1_env_proto_depIdxs = []int32{
	3, // 0: swanlab.system.v1.MetadataRecord.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: swanlab.system.v1.RequirementsRecord.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: swanlab.system.v1.CondaRecord.timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_swanlab_system_v1_env_proto_init() }
func file_swanlab_system_v1_env_proto_init() {
	if File_swanlab_system_v1_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_system_v1_env_proto_rawDesc), len(file_swanlab_system_v1_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_system_v1_env_proto_goTypes,
		DependencyIndexes: file_swanlab_system_v1_env_proto_depIdxs,
		MessageInfos:      file_swanlab_system_v1_env_proto_msgTypes,
	}.Build()
	File_swanlab_system_v1_env_proto = out.File
	file_swanlab_system_v1_env_proto_goTypes = nil
	file_swanlab_system_v1_env_proto_depIdxs = nil
}
