// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/system/v1/env.proto

package systemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 运行开始时采集一次的主机与环境元数据引用（swanlab-metadata.json）。
// 由于不同机器的硬件和软件环境差异极大，难以保证强类型安全，因此采用文件路径引用的设计。
type MetadataRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 相对于 run_dir 的文件路径，如 "files/swanlab-metadata.json"
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRecord) Reset() {
	*x = MetadataRecord{}
	mi := &file_swanlab_system_v1_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRecord) ProtoMessage() {}

func (x *MetadataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_system_v1_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRecord.ProtoReflect.Descriptor instead.
func (*MetadataRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_system_v1_env_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// 运行开始时采集的 Python 包依赖引用（requirements.txt）。
type RequirementsRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 相对于 run_dir 的文件路径，如 "files/requirements.txt"
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequirementsRecord) Reset() {
	*x = RequirementsRecord{}
	mi := &file_swanlab_system_v1_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequirementsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequirementsRecord) ProtoMessage() {}

func (x *RequirementsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_system_v1_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequirementsRecord.ProtoReflect.Descriptor instead.
func (*RequirementsRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_system_v1_env_proto_rawDescGZIP(), []int{1}
}

func (x *RequirementsRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// 运行开始时采集的 Conda 环境引用（conda.yml）。
type CondaRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 相对于 run_dir 的文件路径，如 "files/conda.yml"
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CondaRecord) Reset() {
	*x = CondaRecord{}
	mi := &file_swanlab_system_v1_env_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CondaRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CondaRecord) ProtoMessage() {}

func (x *CondaRecord) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_system_v1_env_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CondaRecord.ProtoReflect.Descriptor instead.
func (*CondaRecord) Descriptor() ([]byte, []int) {
	return file_swanlab_system_v1_env_proto_rawDescGZIP(), []int{2}
}

func (x *CondaRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_swanlab_system_v1_env_proto protoreflect.FileDescriptor

const file_swanlab_system_v1_env_proto_rawDesc = "" +
	"\n" +
	"\x1bswanlab/system/v1/env.proto\x12\x11swanlab.system.v1\"$\n" +
	"\x0eMetadataRecord\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"(\n" +
	"\x12RequirementsRecord\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"!\n" +
	"\vCondaRecord\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04pathBCZAgithub.com/swanhubx/swanlab/core/proto/swanlab/system/v1;systemv1b\x06proto3"

var (
	file_swanlab_system_v1_env_proto_rawDescOnce sync.Once
	file_swanlab_system_v1_env_proto_rawDescData []byte
)

func file_swanlab_system_v1_env_proto_rawDescGZIP() []byte {
	file_swanlab_system_v1_env_proto_rawDescOnce.Do(func() {
		file_swanlab_system_v1_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_system_v1_env_proto_rawDesc), len(file_swanlab_system_v1_env_proto_rawDesc)))
	})
	return file_swanlab_system_v1_env_proto_rawDescData
}

var file_swanlab_system_v1_env_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_swanlab_system_v1_env_proto_goTypes = []any{
	(*MetadataRecord)(nil),     // 0: swanlab.system.v1.MetadataRecord
	(*RequirementsRecord)(nil), // 1: swanlab.system.v1.RequirementsRecord
	(*CondaRecord)(nil),        // 2: swanlab.system.v1.CondaRecord
}
var file_swanlab_system_v1_env_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_swanlab_system_v1_env_proto_init() }
func file_swanlab_system_v1_env_proto_init() {
	if File_swanlab_system_v1_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_system_v1_env_proto_rawDesc), len(file_swanlab_system_v1_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_system_v1_env_proto_goTypes,
		DependencyIndexes: file_swanlab_system_v1_env_proto_depIdxs,
		MessageInfos:      file_swanlab_system_v1_env_proto_msgTypes,
	}.Build()
	File_swanlab_system_v1_env_proto = out.File
	file_swanlab_system_v1_env_proto_goTypes = nil
	file_swanlab_system_v1_env_proto_depIdxs = nil
}
