// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: swanlab/grpc/core/v2/core.proto

package corev2

import (
	v12 "github.com/swanhubx/swanlab/core/proto/swanlab/metric/column/v1"
	v13 "github.com/swanhubx/swanlab/core/proto/swanlab/metric/data/v1"
	v16 "github.com/swanhubx/swanlab/core/proto/swanlab/operation/v1"
	v11 "github.com/swanhubx/swanlab/core/proto/swanlab/run/v1"
	v15 "github.com/swanhubx/swanlab/core/proto/swanlab/save/v1"
	v1 "github.com/swanhubx/swanlab/core/proto/swanlab/settings/core/v1"
	v14 "github.com/swanhubx/swanlab/core/proto/swanlab/terminal/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCapabilities 请求。当前无字段，预留后续扩展。
type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{0}
}

// GetCapabilities 响应，服务能力快照。能力位必须如实反映实现现状，
// 调用方应校验所需能力后再接入数据路径，能力缺失时不得继续写入。
type GetCapabilitiesResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion        string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`                           // 协议版本，与 Python SDK 期望版本锁步
	CoreVersion            string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`                                       // core 二进制编译版本（构建管线注入）
	Lifecycle              bool                   `protobuf:"varint,3,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`                                                             // 生命周期与进程管理能力
	SupportedModes         []string               `protobuf:"bytes,4,rep,name=supported_modes,json=supportedModes,proto3" json:"supported_modes,omitempty"`                              // 支持的 run 模式，如 online/local/offline
	Store                  bool                   `protobuf:"varint,5,opt,name=store,proto3" json:"store,omitempty"`                                                                     // 本地持久化能力
	Transport              bool                   `protobuf:"varint,6,opt,name=transport,proto3" json:"transport,omitempty"`                                                             // 云端上传能力
	Payload                bool                   `protobuf:"varint,7,opt,name=payload,proto3" json:"payload,omitempty"`                                                                 // 内联 payload 能力（online skip_store 模式）
	Sync                   bool                   `protobuf:"varint,8,opt,name=sync,proto3" json:"sync,omitempty"`                                                                       // 离线数据同步能力
	MaxReceiveMessageBytes int64                  `protobuf:"varint,9,opt,name=max_receive_message_bytes,json=maxReceiveMessageBytes,proto3" json:"max_receive_message_bytes,omitempty"` // 服务端单条消息接收上限，用于客户端协商
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetLifecycle() bool {
	if x != nil {
		return x.Lifecycle
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSupportedModes() []string {
	if x != nil {
		return x.SupportedModes
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetStore() bool {
	if x != nil {
		return x.Store
	}
	return false
}

func (x *GetCapabilitiesResponse) GetTransport() bool {
	if x != nil {
		return x.Transport
	}
	return false
}

func (x *GetCapabilitiesResponse) GetPayload() bool {
	if x != nil {
		return x.Payload
	}
	return false
}

func (x *GetCapabilitiesResponse) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

func (x *GetCapabilitiesResponse) GetMaxReceiveMessageBytes() int64 {
	if x != nil {
		return x.MaxReceiveMessageBytes
	}
	return 0
}

// TeardownService 请求。
type TeardownServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerToken    string                 `protobuf:"bytes,1,opt,name=owner_token,json=ownerToken,proto3" json:"owner_token,omitempty"` // 服务所有者令牌，仅 spawn owner 持有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownServiceRequest) Reset() {
	*x = TeardownServiceRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownServiceRequest) ProtoMessage() {}

func (x *TeardownServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownServiceRequest.ProtoReflect.Descriptor instead.
func (*TeardownServiceRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{2}
}

func (x *TeardownServiceRequest) GetOwnerToken() string {
	if x != nil {
		return x.OwnerToken
	}
	return ""
}

// TeardownService 响应。
type TeardownServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownServiceResponse) Reset() {
	*x = TeardownServiceResponse{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownServiceResponse) ProtoMessage() {}

func (x *TeardownServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownServiceResponse.ProtoReflect.Descriptor instead.
func (*TeardownServiceResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{3}
}

// DeliverRunStart 请求，生命周期函数，运行正式开始
type DeliverRunStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreSettings  *v1.CoreSettings       `protobuf:"bytes,1,opt,name=core_settings,json=coreSettings,proto3" json:"core_settings,omitempty"` // Run 服务配置
	StartRecord   *v11.StartRecord       `protobuf:"bytes,2,opt,name=start_record,json=startRecord,proto3" json:"start_record,omitempty"`    // Run 创建记录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRunStartRequest) Reset() {
	*x = DeliverRunStartRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRunStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRunStartRequest) ProtoMessage() {}

func (x *DeliverRunStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRunStartRequest.ProtoReflect.Descriptor instead.
func (*DeliverRunStartRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{4}
}

func (x *DeliverRunStartRequest) GetCoreSettings() *v1.CoreSettings {
	if x != nil {
		return x.CoreSettings
	}
	return nil
}

func (x *DeliverRunStartRequest) GetStartRecord() *v11.StartRecord {
	if x != nil {
		return x.StartRecord
	}
	return nil
}

// DeliverRunStart 响应
type DeliverRunStartResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                             // 请求是否成功
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                              // 请求失败的响应
	Run              *v11.StartRecord       `protobuf:"bytes,3,opt,name=run,proto3" json:"run,omitempty"`                                                      // 最终创建的 Run 记录
	Path             string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                                    // 对应的实验路径，格式为 /:username/:project_name/:slug(run_id)
	Name             string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                                                    // 对应的实验名称
	GlobalStep       int64                  `protobuf:"varint,6,opt,name=global_step,json=globalStep,proto3" json:"global_step,omitempty"`                     // 起始全局步数
	GlobalSystemStep int64                  `protobuf:"varint,7,opt,name=global_system_step,json=globalSystemStep,proto3" json:"global_system_step,omitempty"` // 起始全局系统步数
	NewExperiment    bool                   `protobuf:"varint,8,opt,name=new_experiment,json=newExperiment,proto3" json:"new_experiment,omitempty"`            // 是否是新实验
	RunHandle        string                 `protobuf:"bytes,9,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"`                         // 服务端生成的 opaque 会话标识，后续所有 run 级 RPC 必须携带
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeliverRunStartResponse) Reset() {
	*x = DeliverRunStartResponse{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRunStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRunStartResponse) ProtoMessage() {}

func (x *DeliverRunStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRunStartResponse.ProtoReflect.Descriptor instead.
func (*DeliverRunStartResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{5}
}

func (x *DeliverRunStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliverRunStartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeliverRunStartResponse) GetRun() *v11.StartRecord {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *DeliverRunStartResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeliverRunStartResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeliverRunStartResponse) GetGlobalStep() int64 {
	if x != nil {
		return x.GlobalStep
	}
	return 0
}

func (x *DeliverRunStartResponse) GetGlobalSystemStep() int64 {
	if x != nil {
		return x.GlobalSystemStep
	}
	return 0
}

func (x *DeliverRunStartResponse) GetNewExperiment() bool {
	if x != nil {
		return x.NewExperiment
	}
	return false
}

func (x *DeliverRunStartResponse) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// UpsertColumns 请求，异步插入一批列定义
type UpsertColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*v12.ColumnRecord    `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`                      // 列定义列表
	RunHandle     string                 `protobuf:"bytes,2,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"` // 目标 run 会话标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertColumnsRequest) Reset() {
	*x = UpsertColumnsRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertColumnsRequest) ProtoMessage() {}

func (x *UpsertColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertColumnsRequest.ProtoReflect.Descriptor instead.
func (*UpsertColumnsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertColumnsRequest) GetColumns() []*v12.ColumnRecord {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *UpsertColumnsRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// UpsertScalars 请求，异步插入一批标量数据
type UpsertScalarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v13.ScalarRecord    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`                            // 标量记录列表
	RunHandle     string                 `protobuf:"bytes,2,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"` // 目标 run 会话标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertScalarsRequest) Reset() {
	*x = UpsertScalarsRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertScalarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertScalarsRequest) ProtoMessage() {}

func (x *UpsertScalarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertScalarsRequest.ProtoReflect.Descriptor instead.
func (*UpsertScalarsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertScalarsRequest) GetData() []*v13.ScalarRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpsertScalarsRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// UpsertMedia 请求，异步插入一批媒体数据
type UpsertMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*v13.MediaRecord     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`                            // 媒体记录列表
	RunHandle     string                 `protobuf:"bytes,2,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"` // 目标 run 会话标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMediaRequest) Reset() {
	*x = UpsertMediaRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMediaRequest) ProtoMessage() {}

func (x *UpsertMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMediaRequest.ProtoReflect.Descriptor instead.
func (*UpsertMediaRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertMediaRequest) GetData() []*v13.MediaRecord {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpsertMediaRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// UpsertLogs 请求，异步插入一批终端输出
type UpsertLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*v14.LogRecord       `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`                            // 终端日志记录列表
	RunHandle     string                 `protobuf:"bytes,2,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"` // 目标 run 会话标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertLogsRequest) Reset() {
	*x = UpsertLogsRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertLogsRequest) ProtoMessage() {}

func (x *UpsertLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertLogsRequest.ProtoReflect.Descriptor instead.
func (*UpsertLogsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertLogsRequest) GetLogs() []*v14.LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *UpsertLogsRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// UpsertSaves 请求，异步插入一批文件保存记录
type UpsertSavesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saves         []*v15.SaveRecord      `protobuf:"bytes,1,rep,name=saves,proto3" json:"saves,omitempty"`                          // 保存记录列表
	RunHandle     string                 `protobuf:"bytes,2,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"` // 目标 run 会话标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertSavesRequest) Reset() {
	*x = UpsertSavesRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSavesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSavesRequest) ProtoMessage() {}

func (x *UpsertSavesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSavesRequest.ProtoReflect.Descriptor instead.
func (*UpsertSavesRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertSavesRequest) GetSaves() []*v15.SaveRecord {
	if x != nil {
		return x.Saves
	}
	return nil
}

func (x *UpsertSavesRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// DeliverRunFinish 请求，生命周期函数，运行结束
type DeliverRunFinishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinishRecord  *v11.FinishRecord      `protobuf:"bytes,1,opt,name=finish_record,json=finishRecord,proto3" json:"finish_record,omitempty"` // Run 结束记录
	RunHandle     string                 `protobuf:"bytes,2,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"`          // 目标 run 会话标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRunFinishRequest) Reset() {
	*x = DeliverRunFinishRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRunFinishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRunFinishRequest) ProtoMessage() {}

func (x *DeliverRunFinishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRunFinishRequest.ProtoReflect.Descriptor instead.
func (*DeliverRunFinishRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{11}
}

func (x *DeliverRunFinishRequest) GetFinishRecord() *v11.FinishRecord {
	if x != nil {
		return x.FinishRecord
	}
	return nil
}

func (x *DeliverRunFinishRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// DeliverRunFinish 响应
type DeliverRunFinishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 请求是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 请求失败的响应
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRunFinishResponse) Reset() {
	*x = DeliverRunFinishResponse{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRunFinishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRunFinishResponse) ProtoMessage() {}

func (x *DeliverRunFinishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRunFinishResponse.ProtoReflect.Descriptor instead.
func (*DeliverRunFinishResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverRunFinishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliverRunFinishResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetOperationStats 请求。
type GetOperationStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunHandle     string                 `protobuf:"bytes,1,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"` // 目标 run 会话标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationStatsRequest) Reset() {
	*x = GetOperationStatsRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationStatsRequest) ProtoMessage() {}

func (x *GetOperationStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationStatsRequest.ProtoReflect.Descriptor instead.
func (*GetOperationStatsRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{13}
}

func (x *GetOperationStatsRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// GetOperationStats 响应
type GetOperationStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 请求是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 请求失败的响应
	Stats         *v16.OperationStats    `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`      // Core 当前运行状态和上传进度快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationStatsResponse) Reset() {
	*x = GetOperationStatsResponse{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationStatsResponse) ProtoMessage() {}

func (x *GetOperationStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationStatsResponse.ProtoReflect.Descriptor instead.
func (*GetOperationStatsResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{14}
}

func (x *GetOperationStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOperationStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetOperationStatsResponse) GetStats() *v16.OperationStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// ConfirmRunFinish 请求。
type ConfirmRunFinishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunHandle     string                 `protobuf:"bytes,1,opt,name=run_handle,json=runHandle,proto3" json:"run_handle,omitempty"` // 目标 run 会话标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRunFinishRequest) Reset() {
	*x = ConfirmRunFinishRequest{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRunFinishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRunFinishRequest) ProtoMessage() {}

func (x *ConfirmRunFinishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRunFinishRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRunFinishRequest) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{15}
}

func (x *ConfirmRunFinishRequest) GetRunHandle() string {
	if x != nil {
		return x.RunHandle
	}
	return ""
}

// ConfirmRunFinish 响应
type ConfirmRunFinishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 请求是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 请求失败的响应
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRunFinishResponse) Reset() {
	*x = ConfirmRunFinishResponse{}
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRunFinishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRunFinishResponse) ProtoMessage() {}

func (x *ConfirmRunFinishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_grpc_core_v2_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRunFinishResponse.ProtoReflect.Descriptor instead.
func (*ConfirmRunFinishResponse) Descriptor() ([]byte, []int) {
	return file_swanlab_grpc_core_v2_core_proto_rawDescGZIP(), []int{16}
}

func (x *ConfirmRunFinishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmRunFinishResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_swanlab_grpc_core_v2_core_proto protoreflect.FileDescriptor

const file_swanlab_grpc_core_v2_core_proto_rawDesc = "" +
	"\n" +
	"\x1fswanlab/grpc/core/v2/core.proto\x12\x14swanlab.grpc.core.v2\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18swanlab/run/v1/run.proto\x1a!swanlab/metric/data/v1/data.proto\x1a%swanlab/metric/column/v1/column.proto\x1a\x1dswanlab/terminal/v1/log.proto\x1a\x1aswanlab/save/v1/save.proto\x1a$swanlab/operation/v1/operation.proto\x1a#swanlab/settings/core/v1/core.proto\"\x18\n" +
	"\x16GetCapabilitiesRequest\"\xcb\x02\n" +
	"\x17GetCapabilitiesResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12\x1c\n" +
	"\tlifecycle\x18\x03 \x01(\bR\tlifecycle\x12'\n" +
	"\x0fsupported_modes\x18\x04 \x03(\tR\x0esupportedModes\x12\x14\n" +
	"\x05store\x18\x05 \x01(\bR\x05store\x12\x1c\n" +
	"\ttransport\x18\x06 \x01(\bR\ttransport\x12\x18\n" +
	"\apayload\x18\a \x01(\bR\apayload\x12\x12\n" +
	"\x04sync\x18\b \x01(\bR\x04sync\x129\n" +
	"\x19max_receive_message_bytes\x18\t \x01(\x03R\x16maxReceiveMessageBytes\"9\n" +
	"\x16TeardownServiceRequest\x12\x1f\n" +
	"\vowner_token\x18\x01 \x01(\tR\n" +
	"ownerToken\"\x19\n" +
	"\x17TeardownServiceResponse\"\xa5\x01\n" +
	"\x16DeliverRunStartRequest\x12K\n" +
	"\rcore_settings\x18\x01 \x01(\v2&.swanlab.settings.core.v1.CoreSettingsR\fcoreSettings\x12>\n" +
	"\fstart_record\x18\x02 \x01(\v2\x1b.swanlab.run.v1.StartRecordR\vstartRecord\"\xb9\x02\n" +
	"\x17DeliverRunStartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x03run\x18\x03 \x01(\v2\x1b.swanlab.run.v1.StartRecordR\x03run\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1f\n" +
	"\vglobal_step\x18\x06 \x01(\x03R\n" +
	"globalStep\x12,\n" +
	"\x12global_system_step\x18\a \x01(\x03R\x10globalSystemStep\x12%\n" +
	"\x0enew_experiment\x18\b \x01(\bR\rnewExperiment\x12\x1d\n" +
	"\n" +
	"run_handle\x18\t \x01(\tR\trunHandle\"w\n" +
	"\x14UpsertColumnsRequest\x12@\n" +
	"\acolumns\x18\x01 \x03(\v2&.swanlab.metric.column.v1.ColumnRecordR\acolumns\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x02 \x01(\tR\trunHandle\"o\n" +
	"\x14UpsertScalarsRequest\x128\n" +
	"\x04data\x18\x01 \x03(\v2$.swanlab.metric.data.v1.ScalarRecordR\x04data\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x02 \x01(\tR\trunHandle\"l\n" +
	"\x12UpsertMediaRequest\x127\n" +
	"\x04data\x18\x01 \x03(\v2#.swanlab.metric.data.v1.MediaRecordR\x04data\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x02 \x01(\tR\trunHandle\"f\n" +
	"\x11UpsertLogsRequest\x122\n" +
	"\x04logs\x18\x01 \x03(\v2\x1e.swanlab.terminal.v1.LogRecordR\x04logs\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x02 \x01(\tR\trunHandle\"f\n" +
	"\x12UpsertSavesRequest\x121\n" +
	"\x05saves\x18\x01 \x03(\v2\x1b.swanlab.save.v1.SaveRecordR\x05saves\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x02 \x01(\tR\trunHandle\"{\n" +
	"\x17DeliverRunFinishRequest\x12A\n" +
	"\rfinish_record\x18\x01 \x01(\v2\x1c.swanlab.run.v1.FinishRecordR\ffinishRecord\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x02 \x01(\tR\trunHandle\"N\n" +
	"\x18DeliverRunFinishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x18GetOperationStatsRequest\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x01 \x01(\tR\trunHandle\"\x8b\x01\n" +
	"\x19GetOperationStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x05stats\x18\x03 \x01(\v2$.swanlab.operation.v1.OperationStatsR\x05stats\"8\n" +
	"\x17ConfirmRunFinishRequest\x12\x1d\n" +
	"\n" +
	"run_handle\x18\x01 \x01(\tR\trunHandle\"N\n" +
	"\x18ConfirmRunFinishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd4\b\n" +
	"\vCoreService\x12n\n" +
	"\x0fGetCapabilities\x12,.swanlab.grpc.core.v2.GetCapabilitiesRequest\x1a-.swanlab.grpc.core.v2.GetCapabilitiesResponse\x12n\n" +
	"\x0fTeardownService\x12,.swanlab.grpc.core.v2.TeardownServiceRequest\x1a-.swanlab.grpc.core.v2.TeardownServiceResponse\x12n\n" +
	"\x0fDeliverRunStart\x12,.swanlab.grpc.core.v2.DeliverRunStartRequest\x1a-.swanlab.grpc.core.v2.DeliverRunStartResponse\x12S\n" +
	"\rUpsertColumns\x12*.swanlab.grpc.core.v2.UpsertColumnsRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\rUpsertScalars\x12*.swanlab.grpc.core.v2.UpsertScalarsRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\vUpsertMedia\x12(.swanlab.grpc.core.v2.UpsertMediaRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\n" +
	"UpsertLogs\x12'.swanlab.grpc.core.v2.UpsertLogsRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\vUpsertSaves\x12(.swanlab.grpc.core.v2.UpsertSavesRequest\x1a\x16.google.protobuf.Empty\x12q\n" +
	"\x10DeliverRunFinish\x12-.swanlab.grpc.core.v2.DeliverRunFinishRequest\x1a..swanlab.grpc.core.v2.DeliverRunFinishResponse\x12t\n" +
	"\x11GetOperationStats\x12..swanlab.grpc.core.v2.GetOperationStatsRequest\x1a/.swanlab.grpc.core.v2.GetOperationStatsResponse\x12q\n" +
	"\x10ConfirmRunFinish\x12-.swanlab.grpc.core.v2.ConfirmRunFinishRequest\x1a..swanlab.grpc.core.v2.ConfirmRunFinishResponseBDZBgithub.com/swanhubx/swanlab/core/proto/swanlab/grpc/core/v2;corev2b\x06proto3"

var (
	file_swanlab_grpc_core_v2_core_proto_rawDescOnce sync.Once
	file_swanlab_grpc_core_v2_core_proto_rawDescData []byte
)

func file_swanlab_grpc_core_v2_core_proto_rawDescGZIP() []byte {
	file_swanlab_grpc_core_v2_core_proto_rawDescOnce.Do(func() {
		file_swanlab_grpc_core_v2_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_grpc_core_v2_core_proto_rawDesc), len(file_swanlab_grpc_core_v2_core_proto_rawDesc)))
	})
	return file_swanlab_grpc_core_v2_core_proto_rawDescData
}

var file_swanlab_grpc_core_v2_core_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_swanlab_grpc_core_v2_core_proto_goTypes = []any{
	(*GetCapabilitiesRequest)(nil),    // 0: swanlab.grpc.core.v2.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),   // 1: swanlab.grpc.core.v2.GetCapabilitiesResponse
	(*TeardownServiceRequest)(nil),    // 2: swanlab.grpc.core.v2.TeardownServiceRequest
	(*TeardownServiceResponse)(nil),   // 3: swanlab.grpc.core.v2.TeardownServiceResponse
	(*DeliverRunStartRequest)(nil),    // 4: swanlab.grpc.core.v2.DeliverRunStartRequest
	(*DeliverRunStartResponse)(nil),   // 5: swanlab.grpc.core.v2.DeliverRunStartResponse
	(*UpsertColumnsRequest)(nil),      // 6: swanlab.grpc.core.v2.UpsertColumnsRequest
	(*UpsertScalarsRequest)(nil),      // 7: swanlab.grpc.core.v2.UpsertScalarsRequest
	(*UpsertMediaRequest)(nil),        // 8: swanlab.grpc.core.v2.UpsertMediaRequest
	(*UpsertLogsRequest)(nil),         // 9: swanlab.grpc.core.v2.UpsertLogsRequest
	(*UpsertSavesRequest)(nil),        // 10: swanlab.grpc.core.v2.UpsertSavesRequest
	(*DeliverRunFinishRequest)(nil),   // 11: swanlab.grpc.core.v2.DeliverRunFinishRequest
	(*DeliverRunFinishResponse)(nil),  // 12: swanlab.grpc.core.v2.DeliverRunFinishResponse
	(*GetOperationStatsRequest)(nil),  // 13: swanlab.grpc.core.v2.GetOperationStatsRequest
	(*GetOperationStatsResponse)(nil), // 14: swanlab.grpc.core.v2.GetOperationStatsResponse
	(*ConfirmRunFinishRequest)(nil),   // 15: swanlab.grpc.core.v2.ConfirmRunFinishRequest
	(*ConfirmRunFinishResponse)(nil),  // 16: swanlab.grpc.core.v2.ConfirmRunFinishResponse
	(*v1.CoreSettings)(nil),           // 17: swanlab.settings.core.v1.CoreSettings
	(*v11.StartRecord)(nil),           // 18: swanlab.run.v1.StartRecord
	(*v12.ColumnRecord)(nil),          // 19: swanlab.metric.column.v1.ColumnRecord
	(*v13.ScalarRecord)(nil),          // 20: swanlab.metric.data.v1.ScalarRecord
	(*v13.MediaRecord)(nil),           // 21: swanlab.metric.data.v1.MediaRecord
	(*v14.LogRecord)(nil),             // 22: swanlab.terminal.v1.LogRecord
	(*v15.SaveRecord)(nil),            // 23: swanlab.save.v1.SaveRecord
	(*v11.FinishRecord)(nil),          // 24: swanlab.run.v1.FinishRecord
	(*v16.OperationStats)(nil),        // 25: swanlab.operation.v1.OperationStats
	(*emptypb.Empty)(nil),             // 26: google.protobuf.Empty
}
var file_swanlab_grpc_core_v2_core_proto_depIdxs = []int32{
	17, // 0: swanlab.grpc.core.v2.DeliverRunStartRequest.core_settings:type_name -> swanlab.settings.core.v1.CoreSettings
	18, // 1: swanlab.grpc.core.v2.DeliverRunStartRequest.start_record:type_name -> swanlab.run.v1.StartRecord
	18, // 2: swanlab.grpc.core.v2.DeliverRunStartResponse.run:type_name -> swanlab.run.v1.StartRecord
	19, // 3: swanlab.grpc.core.v2.UpsertColumnsRequest.columns:type_name -> swanlab.metric.column.v1.ColumnRecord
	20, // 4: swanlab.grpc.core.v2.UpsertScalarsRequest.data:type_name -> swanlab.metric.data.v1.ScalarRecord
	21, // 5: swanlab.grpc.core.v2.UpsertMediaRequest.data:type_name -> swanlab.metric.data.v1.MediaRecord
	22, // 6: swanlab.grpc.core.v2.UpsertLogsRequest.logs:type_name -> swanlab.terminal.v1.LogRecord
	23, // 7: swanlab.grpc.core.v2.UpsertSavesRequest.saves:type_name -> swanlab.save.v1.SaveRecord
	24, // 8: swanlab.grpc.core.v2.DeliverRunFinishRequest.finish_record:type_name -> swanlab.run.v1.FinishRecord
	25, // 9: swanlab.grpc.core.v2.GetOperationStatsResponse.stats:type_name -> swanlab.operation.v1.OperationStats
	0,  // 10: swanlab.grpc.core.v2.CoreService.GetCapabilities:input_type -> swanlab.grpc.core.v2.GetCapabilitiesRequest
	2,  // 11: swanlab.grpc.core.v2.CoreService.TeardownService:input_type -> swanlab.grpc.core.v2.TeardownServiceRequest
	4,  // 12: swanlab.grpc.core.v2.CoreService.DeliverRunStart:input_type -> swanlab.grpc.core.v2.DeliverRunStartRequest
	6,  // 13: swanlab.grpc.core.v2.CoreService.UpsertColumns:input_type -> swanlab.grpc.core.v2.UpsertColumnsRequest
	7,  // 14: swanlab.grpc.core.v2.CoreService.UpsertScalars:input_type -> swanlab.grpc.core.v2.UpsertScalarsRequest
	8,  // 15: swanlab.grpc.core.v2.CoreService.UpsertMedia:input_type -> swanlab.grpc.core.v2.UpsertMediaRequest
	9,  // 16: swanlab.grpc.core.v2.CoreService.UpsertLogs:input_type -> swanlab.grpc.core.v2.UpsertLogsRequest
	10, // 17: swanlab.grpc.core.v2.CoreService.UpsertSaves:input_type -> swanlab.grpc.core.v2.UpsertSavesRequest
	11, // 18: swanlab.grpc.core.v2.CoreService.DeliverRunFinish:input_type -> swanlab.grpc.core.v2.DeliverRunFinishRequest
	13, // 19: swanlab.grpc.core.v2.CoreService.GetOperationStats:input_type -> swanlab.grpc.core.v2.GetOperationStatsRequest
	15, // 20: swanlab.grpc.core.v2.CoreService.ConfirmRunFinish:input_type -> swanlab.grpc.core.v2.ConfirmRunFinishRequest
	1,  // 21: swanlab.grpc.core.v2.CoreService.GetCapabilities:output_type -> swanlab.grpc.core.v2.GetCapabilitiesResponse
	3,  // 22: swanlab.grpc.core.v2.CoreService.TeardownService:output_type -> swanlab.grpc.core.v2.TeardownServiceResponse
	5,  // 23: swanlab.grpc.core.v2.CoreService.DeliverRunStart:output_type -> swanlab.grpc.core.v2.DeliverRunStartResponse
	26, // 24: swanlab.grpc.core.v2.CoreService.UpsertColumns:output_type -> google.protobuf.Empty
	26, // 25: swanlab.grpc.core.v2.CoreService.UpsertScalars:output_type -> google.protobuf.Empty
	26, // 26: swanlab.grpc.core.v2.CoreService.UpsertMedia:output_type -> google.protobuf.Empty
	26, // 27: swanlab.grpc.core.v2.CoreService.UpsertLogs:output_type -> google.protobuf.Empty
	26, // 28: swanlab.grpc.core.v2.CoreService.UpsertSaves:output_type -> google.protobuf.Empty
	12, // 29: swanlab.grpc.core.v2.CoreService.DeliverRunFinish:output_type -> swanlab.grpc.core.v2.DeliverRunFinishResponse
	14, // 30: swanlab.grpc.core.v2.CoreService.GetOperationStats:output_type -> swanlab.grpc.core.v2.GetOperationStatsResponse
	16, // 31: swanlab.grpc.core.v2.CoreService.ConfirmRunFinish:output_type -> swanlab.grpc.core.v2.ConfirmRunFinishResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_swanlab_grpc_core_v2_core_proto_init() }
func file_swanlab_grpc_core_v2_core_proto_init() {
	if File_swanlab_grpc_core_v2_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_grpc_core_v2_core_proto_rawDesc), len(file_swanlab_grpc_core_v2_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swanlab_grpc_core_v2_core_proto_goTypes,
		DependencyIndexes: file_swanlab_grpc_core_v2_core_proto_depIdxs,
		MessageInfos:      file_swanlab_grpc_core_v2_core_proto_msgTypes,
	}.Build()
	File_swanlab_grpc_core_v2_core_proto = out.File
	file_swanlab_grpc_core_v2_core_proto_goTypes = nil
	file_swanlab_grpc_core_v2_core_proto_depIdxs = nil
}
