name: Test When PR

on:
  push:
    branches:
      - feature/auto-test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-media.txt
          pip install -r requirements-dev.txt

      - name: Test
        run: |
          export SWANLAB_RUNTIME=test
          export SWANLAB_WEB_HOST=${{ secrets.SWANLAB_WEB_HOST }}
          export SWANLAB_API_HOST=https://web.dev001.swanlab.cn/api
          export SWANLAB_API_KEY=${{ secrets.SWANLAB_API_KEY }}
          export PYTHONPATH=$PYTHONPATH:. 
          pytest test/unit
