// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: swanlab/settings/probe/v1/probe.proto

package settingsprobev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeSettings) Reset() {
	*x = ProbeSettings{}
	mi := &file_swanlab_settings_probe_v1_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSettings) ProtoMessage() {}

func (x *ProbeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_swanlab_settings_probe_v1_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSettings.ProtoReflect.Descriptor instead.
func (*ProbeSettings) Descriptor() ([]byte, []int) {
	return file_swanlab_settings_probe_v1_probe_proto_rawDescGZIP(), []int{0}
}

var File_swanlab_settings_probe_v1_probe_proto protoreflect.FileDescriptor

const file_swanlab_settings_probe_v1_probe_proto_rawDesc = "" +
	"\n" +
	"%swanlab/settings/probe/v1/probe.proto\x12\x19swanlab.settings.probe.v1\"\x0f\n" +
	"\rProbeSettingsBRZPgithub.com/swanhubx/swanlab/core/proto/swanlab/settings/probe/v1;settingsprobev1b\x06proto3"

var (
	file_swanlab_settings_probe_v1_probe_proto_rawDescOnce sync.Once
	file_swanlab_settings_probe_v1_probe_proto_rawDescData []byte
)

func file_swanlab_settings_probe_v1_probe_proto_rawDescGZIP() []byte {
	file_swanlab_settings_probe_v1_probe_proto_rawDescOnce.Do(func() {
		file_swanlab_settings_probe_v1_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swanlab_settings_probe_v1_probe_proto_rawDesc), len(file_swanlab_settings_probe_v1_probe_proto_rawDesc)))
	})
	return file_swanlab_settings_probe_v1_probe_proto_rawDescData
}

var file_swanlab_settings_probe_v1_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_swanlab_settings_probe_v1_probe_proto_goTypes = []any{
	(*ProbeSettings)(nil), // 0: swanlab.settings.probe.v1.ProbeSettings
}
var file_swanlab_settings_probe_v1_probe_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_swanlab_settings_probe_v1_probe_proto_init() }
func file_swanlab_settings_probe_v1_probe_proto_init() {
	if File_swanlab_settings_probe_v1_probe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swanlab_settings_probe_v1_probe_proto_rawDesc), len(file_swanlab_settings_probe_v1_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swanlab_settings_probe_v1_probe_proto_goTypes,
		DependencyIndexes: file_swanlab_settings_probe_v1_probe_proto_depIdxs,
		MessageInfos:      file_swanlab_settings_probe_v1_probe_proto_msgTypes,
	}.Build()
	File_swanlab_settings_probe_v1_probe_proto = out.File
	file_swanlab_settings_probe_v1_probe_proto_goTypes = nil
	file_swanlab_settings_probe_v1_probe_proto_depIdxs = nil
}
