#!/usr/bin/env python
# -*- coding: utf-8 -*-
r"""
@DATE: 2024-01-01 18:00:04
@File: swanlab/data/sdk.py
@IDE: vscode
@Description:
    在此处封装swanlab在日志记录模式下的各种接口
"""
import atexit, sys, traceback, os
from datetime import datetime
from .run import SwanLabRun, SwanLabConfig, register
from typing import Optional, Union
from ..log import swanlog
from .modules import DataType
from typing import Dict
from ..env import init_env, ROOT, is_login, get_user_api_key
from .utils.file import check_dir_and_create, formate_abs_path
from ..db import Project, connect
from ..utils import version_limit, FONT, get_package_version, check_load_json_yaml
from ..utils.package import get_host_web
from ..auth import get_exp_token, terminal_login, code_login
from ..error import NotLoginError, ValidationError
import asyncio


run: Optional["SwanLabRun"] = None
"""Global runtime instance. After the user calls finish(), run will be set to None."""

inited: bool = False
"""Indicates whether init() has been called in the current process."""

config: Optional["SwanLabConfig"] = SwanLabConfig(None)
"""
Allows users to record experiment configurations through swanlab.config.
Before calling the init() function, config cannot be read or written, even if it is a SwanLabConfig object.
After calling the init() function, swanlab.config is equivalent to run.config.
Configuration information synchronization is achieved through class variables.
When the run object is initialized, it will operate on the SwanLabConfig object to write the configuration.
"""


def login(api_key: str):
    """
    Login to SwanLab Cloud. If you already have logged in, you can use this function to relogin.

    Parameters
    ----------
    api_key : str
        authentication key.
    """
    # 如果已经登录且保存，判断一下当前api_key是否和本地api_key一致，如果一致，直接返回
    # 如果不一致，继续下面的步骤
    if is_login() and api_key == get_user_api_key():
        return
    # 否则进行登录
    code_login(api_key)


def init_from_path(init_path: str):
    """
    Start a new experiment according to the configuration file.

    Parameters
    ----------
    config_path : str
        The path to the configuration file, this is a required parameter.
        If you provide this parameter, SwanLab will read the configuration from the file.
        The configuration file must be in the format of json or yaml.
    """

    if not isinstance(init_path, str):
        raise ValueError("init_path must be a string")

    if not os.path.isabs(init_path):
        init_path = os.path.abspath(init_path)

    init_data = check_load_json_yaml(init_path, "init_path")

    return init(**init_data)


def init(
    experiment_name: str = None,
    description: str = None,
    config: Union[dict, str] = None,
    logdir: str = None,
    suffix: str = "default",
    # cloud: bool = False,
    # project: str = None,
    # organization: str = None,
    load: str = None,
    **kwargs,
) -> SwanLabRun:
    """
    Start a new run to track and log.
    Once you have called this function, you can use 'swanlab.log' to log data to the current run.
    Meanwhile, you can use 'swanlab.finish' to finish the current run and close the current experiment.
    After calling this function, SwanLab will begin to record the console output of the current process, and register a callback function to the exit function.

    Parameters
    ----------
    experiment_name : str, optional
        The experiment name you currently have open. If this parameter is not provided, SwanLab will generate one for you by default.
    description : str, optional
        The experiment description you currently have open, used for a more detailed introduction or labeling of the current experiment.
        If you do not provide this parameter, you can modify it later in the web interface.
    config : Union[dict, str], optional
        If you provide as a dict, it will be used as the configuration of the current experiment.
        If you provide as a string, SwanLab will read the configuration from the file. And the configuration file must be in the format of `json` or `yaml`.
        Anyway, you can modify the configuration later after this function is called.
    logdir : str, optional
        The folder will store all the log information generated during the execution of Swanlab.
        If the parameter is None, Swanlab will generate a folder named "swanlog" in the same path as the code execution to store the data.
        If you want to visualize the generated log files, simply run the command `swanlab watch` in the same path where the code is executed (without entering the "swanlog" folder).
        You can also specify your own folder, but you must ensure that the folder exists and preferably does not contain anything other than data generated by Swanlab.
        In this case, if you want to view the logs, you must use something like `swanlab watch -l ./your_specified_folder` to specify the folder path.
    suffix : str, optional
        The suffix of the experiment name, the default is 'default'.
        If this parameter is 'default', suffix will be '%b%d-%h-%m-%s_<hostname>'(example:'Feb03_14-45-37_windowsX'), which represents the current time.
        example: experiment_name = 'example', suffix = 'default' -> 'example_Feb03_14-45-37_windowsX';
        If this parameter is None, no suffix will be added.
        If this paramter is a string, the suffix will be the string you provided.
        Attention: experiment_name + suffix must be unique, otherwise the experiment will not be created.
    cloud : bool, optional
        Whether to use the cloud mode, the default is False.
        If you use the cloud mode, the log file will be stored in the cloud, which will still be saved locally.
        If you are not using cloud mode, the `project` and `organization` fields are invalid.
    project : str, optional
        The project name of the current experiment, the default is None, which means the current project name is the same as the current working directory.
        If you are using cloud mode, you must provide the project name.
    organization : str, optional
        The organization name of the current experiment, the default is None, which means the log file will be stored in your personal space.
    load : str, optional
        If you pass this parameter,swanlab will search for the configuration file you specified (which must be in JSON or YAML format) and automatically fill in some explicit parameters of this function for you (excluding parameters in `**kwargs` and the parameters if they are None).
        In terms of priority, if the parameters passed to init are `None`, swanlab will attempt to replace them from the configuration file you provided;
        otherwise, it will use the parameters you passed as the definitive ones.
    log_level : str, optional
        The default log level for logging to the terminal in Swanlab is "info", but it can be chosen as "debug", "info", "warning", "error", or "critical".
        This is unrelated to the `swanlab.log` function and is typically used for development and debugging purposes.
        Therefore, it is only passed implicitly through the `**kwargs` parameter without explicit prompting in this context.
    """
    global run, inited
    # 如果已经初始化过了，直接返回run
    if inited:
        swanlog.warning("You have already initialized a run, the init function will be ignored")
        return run
    # ---------------------------------- 一些变量、格式检查 ----------------------------------
    # 如果传入了load，则加载load文件，如果load文件不存在，报错
    if load:
        load_data = check_load_json_yaml(load, "load")
        # 尝试更改传入的参数为None的情况，如果传入的参数不是None，不做任何操作
        experiment_name = _load_data(load_data, "experiment_name", experiment_name)
        description = _load_data(load_data, "description", description)
        config = _load_data(load_data, "config", config)
        logdir = _load_data(load_data, "logdir", logdir)
        suffix = _load_data(load_data, "suffix", suffix)
    # 初始化logdir参数，接下来logdir被设置为绝对路径且当前程序有写权限
    logdir = _init_logdir(logdir)
    # 初始化confi参数
    config = _init_config(config)
    # 检查logdir内文件的版本，如果<=0.1.4则报错
    version_limit(logdir, mode="init")
    # 初始化环境变量
    init_env()
    # ---------------------------------- 用户登录、格式、权限校验 ----------------------------------
    # 1. 如果没有登录，提示登录
    # 2. 如果登录了，发起请求，如果请求失败，重新登录，返回步骤1
    # token = _get_exp_token(cloud=cloud)
    # 连接本地数据库，要求路径必须存在，但是如果数据库文件不存在，会自动创建
    connect(autocreate=True)
    # 初始化项目数据库
    Project.init(os.path.basename(os.getcwd()))
    # 注册实验
    run = register(
        experiment_name=experiment_name,
        description=description,
        config=config,
        log_level=kwargs.get("log_level", "info"),
        suffix=suffix,
    )
    # 如果使用云端模式，在此开启其他线程负责同步数据

    # 注册异常处理函数
    sys.excepthook = __except_handler
    # 注册清理函数
    atexit.register(__clean_handler)
    swanlog.debug("SwanLab Runtime has initialized")
    swanlog.debug("SwanLab will take over all the print information of the terminal from now on")
    # 展示相关信息信息
    swanlog.info("Tracking run with swanlab version " + get_package_version())
    swanlog.info("Run data will be saved locally in " + FONT.magenta(FONT.bold(formate_abs_path(run.settings.run_dir))))
    # not cloud and swanlog.info("Experiment_name: " + FONT.yellow(run.settings.exp_name))
    swanlog.info("Experiment_name: " + FONT.yellow(run.settings.exp_name))
    # 云端版本有一些额外的信息展示
    # cloud and swanlog.info("Syncing run " + FONT.yellow(run.settings.exp_name) + " to the cloud")
    swanlog.info(
        "🌟 Run `"
        + FONT.bold("swanlab watch -l {}".format(formate_abs_path(run.settings.swanlog_dir)))
        + "` to view SwanLab Experiment Dashboard locally"
    )
    # project_url = get_host_web() + "/" + "{project_name}"
    # experiment_url = project_url + "/" + token
    # cloud and swanlog.info("🏠 View project at " + FONT.blue(FONT.underline(project_url)))
    # cloud and swanlog.info("🚀 View run at " + FONT.blue(FONT.underline(experiment_url)))
    inited = True
    return run


def log(data: Dict[str, DataType], step: int = None):
    """
    Log a row of data to the current run.

    Parameters
    ----------
    data : Dict[str, DataType]
        Data must be a dict.
        The key must be a string with 0-9, a-z, A-Z, " ", "_", "-", "/".
        The value must be a `float`, `float convertible object`, `int` or `swanlab.data.BaseType`.
    step : int, optional
        The step number of the current data, if not provided, it will be automatically incremented.
        If step is duplicated, the data will be ignored.
    """
    if not inited:
        raise RuntimeError("You must call swanlab.data.init() before using log()")
    if inited and run is None:
        return swanlog.error("After calling finish(), you can no longer log data to the current experiment")

    l = run.log(data, step)
    # swanlog.reset_temporary_logging()
    return l


def finish():
    """
    Finish the current run and close the current experiment
    Normally, swanlab will run this function automatically,
    but you can also execute it manually and mark the experiment as 'completed'.
    Once the experiment is marked as 'completed', no more data can be logged to the experiment by 'swanlab.log'.
    """
    global run
    if not inited:
        raise RuntimeError("You must call swanlab.data.init() before using finish()")
    if run is None:
        return swanlog.error("After calling finish(), you can no longer close the current experiment")
    run.success()
    swanlog.setSuccess()
    swanlog.reset_console()
    run = None


def _init_logdir(logdir: str) -> str:
    """
    处理通过init传入的logdir存在的一些情况
    """
    # 如果传入了logdir，则将logdir设置为环境变量，代表日志文件存放的路径
    if logdir is not None:
        try:
            logdir = check_dir_and_create(logdir)
        except ValueError:
            raise ValueError("logdir must be a str.")
        except IOError:
            raise IOError("logdir must be a path and have Write permission.")
        os.environ[ROOT] = logdir
    # 如果没有传入logdir，则使用默认的logdir, 即当前工作目录下的swanlog文件夹，但是需要保证目录存在
    else:
        logdir = os.path.abspath("swanlog")
        try:
            os.makedirs(logdir, exist_ok=True)
            if not os.access(logdir, os.W_OK):
                raise IOError
        except:
            raise IOError("logdir must have Write permission.")
    return logdir


def _init_config(config: Union[dict, str]):
    """初始化传入的config参数"""
    if isinstance(config, dict) or config is None:
        return config
    print(FONT.swanlab("The parameter config is loaded from the configuration file: {}".format(config)))
    return check_load_json_yaml(config, "config")


def _load_data(load_data: dict, key: str, value):
    """从load_data中加载数据，如果value不是None"""
    if value is not None:
        tip = "The parameter {} is loaded from the configuration file: {}".format(FONT.bold(key), value)
        print(FONT.swanlab(tip))
        return value
    d = load_data.get(key, None)
    if d is not None:
        tip = "The parameter {} is loaded from the configuration file: {}".format(FONT.bold(key), d)
        print(FONT.swanlab(tip))
    return d


def _get_exp_token(cloud: bool = False):
    """获取当前实验的相关信息
    可能包含实验的token、实验的id、用户信息等信息
    无论是否使用cloud模式，此函数都会执行，都会返回token，不使用cloud模式返回None，对于后面代码而言，token如果为None，说明没有登录
    """
    token = None
    if cloud:
        # 登录成功会返回当前实验的token
        while True:
            try:
                token = asyncio.run(get_exp_token())
                break
            except NotLoginError:
                # 如果没有登录，提示登录
                terminal_login()
    return token


def __clean_handler():
    """定义清理函数"""
    if run is None:
        return swanlog.debug("SwanLab Runtime has been cleaned manually.")
    if not swanlog.isError:
        swanlog.info(
            "The current experiment {} has been completed, SwanLab will close it automatically".format(
                run.settings.exp_name
            )
        )
        run.success()
        swanlog.setSuccess()
        swanlog.reset_console()


# 定义异常处理函数
def __except_handler(tp, val, tb):
    """定义异常处理函数"""
    if run is None:
        return swanlog.warning("SwanLab Runtime has been cleaned manually, the exception will be ignored")
    swanlog.error("Error happended while training, SwanLab will throw it")
    # 标记实验失败
    run.fail()
    swanlog.setError()
    # 记录异常信息
    # 追踪信息
    traceList = traceback.format_tb(tb)
    html = repr(tp) + "\n"
    html += repr(val) + "\n"
    for line in traceList:
        html += line + "\n"

    if os.path.exists(run.settings.error_path):
        swanlog.warning("Error log file already exists, append error log to it")
    # 写入日志文件
    with open(run.settings.error_path, "a") as fError:
        print(datetime.now(), file=fError)
        print(html, file=fError)
    # 重置控制台记录器
    swanlog.reset_console()
    raise tp(val)
